# generated by scripts/postprocess_generated_models.py -- do not edit manually
"""Auto-generated Exception subclasses, one per `ErrorType` enum member.

Each subclass inherits from `ApifyApiError` so existing `except ApifyApiError` handlers
keep working. `ApifyApiError.__new__` uses `API_ERROR_CLASS_BY_TYPE` to dispatch to the
specific subclass based on the `type` field of the API error response.
"""

from __future__ import annotations

from apify_client._docs import docs_group
from apify_client.errors import ApifyApiError


@docs_group('Errors')
class Field3DSecureAuthFailedError(ApifyApiError):
    """Raised when the Apify API returns a `3d-secure-auth-failed` error."""


@docs_group('Errors')
class AccessRightAlreadyExistsError(ApifyApiError):
    """Raised when the Apify API returns a `access-right-already-exists` error."""


@docs_group('Errors')
class ActionNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `action-not-found` error."""


@docs_group('Errors')
class ActorAlreadyRentedError(ApifyApiError):
    """Raised when the Apify API returns a `actor-already-rented` error."""


@docs_group('Errors')
class ActorCanNotBeRentedError(ApifyApiError):
    """Raised when the Apify API returns a `actor-can-not-be-rented` error."""


@docs_group('Errors')
class ActorDisabledError(ApifyApiError):
    """Raised when the Apify API returns a `actor-disabled` error."""


@docs_group('Errors')
class ActorIsNotRentedError(ApifyApiError):
    """Raised when the Apify API returns a `actor-is-not-rented` error."""


@docs_group('Errors')
class ActorMemoryLimitExceededError(ApifyApiError):
    """Raised when the Apify API returns a `actor-memory-limit-exceeded` error."""


@docs_group('Errors')
class ActorNameExistsNewOwnerError(ApifyApiError):
    """Raised when the Apify API returns a `actor-name-exists-new-owner` error."""


@docs_group('Errors')
class ActorNameNotUniqueError(ApifyApiError):
    """Raised when the Apify API returns a `actor-name-not-unique` error."""


@docs_group('Errors')
class ActorNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `actor-not-found` error."""


@docs_group('Errors')
class ActorNotGithubActorError(ApifyApiError):
    """Raised when the Apify API returns a `actor-not-github-actor` error."""


@docs_group('Errors')
class ActorNotPublicError(ApifyApiError):
    """Raised when the Apify API returns a `actor-not-public` error."""


@docs_group('Errors')
class ActorPermissionLevelNotSupportedForAgenticPaymentsError(ApifyApiError):
    """Raised when the Apify API returns a `actor-permission-level-not-supported-for-agentic-payments` error."""


@docs_group('Errors')
class ActorReviewAlreadyExistsError(ApifyApiError):
    """Raised when the Apify API returns a `actor-review-already-exists` error."""


@docs_group('Errors')
class ActorRunFailedError(ApifyApiError):
    """Raised when the Apify API returns a `actor-run-failed` error."""


@docs_group('Errors')
class ActorStandbyNotSupportedForAgenticPaymentsError(ApifyApiError):
    """Raised when the Apify API returns a `actor-standby-not-supported-for-agentic-payments` error."""


@docs_group('Errors')
class ActorTaskNameNotUniqueError(ApifyApiError):
    """Raised when the Apify API returns a `actor-task-name-not-unique` error."""


@docs_group('Errors')
class AgenticPaymentInfoRetrievalError(ApifyApiError):
    """Raised when the Apify API returns a `agentic-payment-info-retrieval-error` error."""


@docs_group('Errors')
class AgenticPaymentInformationMissingError(ApifyApiError):
    """Raised when the Apify API returns a `agentic-payment-information-missing` error."""


@docs_group('Errors')
class AgenticPaymentInsufficientAmountError(ApifyApiError):
    """Raised when the Apify API returns a `agentic-payment-insufficient-amount` error."""


@docs_group('Errors')
class AgenticPaymentProviderInternalError(ApifyApiError):
    """Raised when the Apify API returns a `agentic-payment-provider-internal-error` error."""


@docs_group('Errors')
class AgenticPaymentProviderUnauthorizedError(ApifyApiError):
    """Raised when the Apify API returns a `agentic-payment-provider-unauthorized` error."""


@docs_group('Errors')
class AirtableWebhookDeprecatedError(ApifyApiError):
    """Raised when the Apify API returns a `airtable-webhook-deprecated` error."""


@docs_group('Errors')
class AlreadySubscribedToPaidActorError(ApifyApiError):
    """Raised when the Apify API returns a `already-subscribed-to-paid-actor` error."""


@docs_group('Errors')
class ApifyPlanRequiredToUsePaidActorError(ApifyApiError):
    """Raised when the Apify API returns a `apify-plan-required-to-use-paid-actor` error."""


@docs_group('Errors')
class ApifySignupNotAllowedError(ApifyApiError):
    """Raised when the Apify API returns a `apify-signup-not-allowed` error."""


@docs_group('Errors')
class AuthMethodNotSupportedError(ApifyApiError):
    """Raised when the Apify API returns a `auth-method-not-supported` error."""


@docs_group('Errors')
class AuthorizationServerNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `authorization-server-not-found` error."""


@docs_group('Errors')
class AutoIssueDateInvalidError(ApifyApiError):
    """Raised when the Apify API returns a `auto-issue-date-invalid` error."""


@docs_group('Errors')
class BackgroundCheckRequiredError(ApifyApiError):
    """Raised when the Apify API returns a `background-check-required` error."""


@docs_group('Errors')
class BillingSystemError(ApifyApiError):
    """Raised when the Apify API returns a `billing-system-error` error."""


@docs_group('Errors')
class BlackFridayPlanExpiredError(ApifyApiError):
    """Raised when the Apify API returns a `black-friday-plan-expired` error."""


@docs_group('Errors')
class BraintreeError(ApifyApiError):
    """Raised when the Apify API returns a `braintree-error` error."""


@docs_group('Errors')
class BraintreeNotLinkedError(ApifyApiError):
    """Raised when the Apify API returns a `braintree-not-linked` error."""


@docs_group('Errors')
class BraintreeOperationTimedOutError(ApifyApiError):
    """Raised when the Apify API returns a `braintree-operation-timed-out` error."""


@docs_group('Errors')
class BraintreeUnsupportedCurrencyError(ApifyApiError):
    """Raised when the Apify API returns a `braintree-unsupported-currency` error."""


@docs_group('Errors')
class BuildNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `build-not-found` error."""


@docs_group('Errors')
class BuildOutdatedError(ApifyApiError):
    """Raised when the Apify API returns a `build-outdated` error."""


@docs_group('Errors')
class CannotAddApifyEventsToPpeActorError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-add-apify-events-to-ppe-actor` error."""


@docs_group('Errors')
class CannotAddMultiplePricingInfosError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-add-multiple-pricing-infos` error."""


@docs_group('Errors')
class CannotAddPricingInfoThatAltersPastError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-add-pricing-info-that-alters-past` error."""


@docs_group('Errors')
class CannotAddSecondFuturePricingInfoError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-add-second-future-pricing-info` error."""


@docs_group('Errors')
class CannotBuildActorFromWebhookError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-build-actor-from-webhook` error."""


@docs_group('Errors')
class CannotChangeBillingIntervalError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-change-billing-interval` error."""


@docs_group('Errors')
class CannotChangeOwnerError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-change-owner` error."""


@docs_group('Errors')
class CannotChargeApifyEventError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-charge-apify-event` error."""


@docs_group('Errors')
class CannotChargeNonPayPerEventActorError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-charge-non-pay-per-event-actor` error."""


@docs_group('Errors')
class CannotCommentAsOtherUserError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-comment-as-other-user` error."""


@docs_group('Errors')
class CannotCopyActorTaskError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-copy-actor-task` error."""


@docs_group('Errors')
class CannotCreatePayoutError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-create-payout` error."""


@docs_group('Errors')
class CannotCreatePublicActorError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-create-public-actor` error."""


@docs_group('Errors')
class CannotCreateTaxTransactionError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-create-tax-transaction` error."""


@docs_group('Errors')
class CannotDeleteCriticalActorError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-delete-critical-actor` error."""


@docs_group('Errors')
class CannotDeleteInvoiceError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-delete-invoice` error."""


@docs_group('Errors')
class CannotDeletePaidActorError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-delete-paid-actor` error."""


@docs_group('Errors')
class CannotDisableOneTimeEventForApifyStartEventError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-disable-one-time-event-for-apify-start-event` error."""


@docs_group('Errors')
class CannotDisableOrganizationWithEnabledMembersError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-disable-organization-with-enabled-members` error."""


@docs_group('Errors')
class CannotDisableUserWithSubscriptionError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-disable-user-with-subscription` error."""


@docs_group('Errors')
class CannotLinkOauthToUnverifiedEmailError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-link-oauth-to-unverified-email` error."""


@docs_group('Errors')
class CannotMetamorphToPayPerResultActorError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-metamorph-to-pay-per-result-actor` error."""


@docs_group('Errors')
class CannotModifyActorPricingTooFrequentlyError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-modify-actor-pricing-too-frequently` error."""


@docs_group('Errors')
class CannotModifyActorPricingWithImmediateEffectError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-modify-actor-pricing-with-immediate-effect` error."""


@docs_group('Errors')
class CannotOverridePaidActorTrialError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-override-paid-actor-trial` error."""


@docs_group('Errors')
class CannotPermanentlyDeleteSubscriptionError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-permanently-delete-subscription` error."""


@docs_group('Errors')
class CannotPublishActorError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-publish-actor` error."""


@docs_group('Errors')
class CannotReduceLastFullTokenError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-reduce-last-full-token` error."""


@docs_group('Errors')
class CannotReimburseMoreThanOriginalChargeError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-reimburse-more-than-original-charge` error."""


@docs_group('Errors')
class CannotReimburseNonRentalChargeError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-reimburse-non-rental-charge` error."""


@docs_group('Errors')
class CannotRemoveOwnActorFromRecentlyUsedError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-remove-own-actor-from-recently-used` error."""


@docs_group('Errors')
class CannotRemovePaymentMethodError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-remove-payment-method` error."""


@docs_group('Errors')
class CannotRemovePricingInfoError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-remove-pricing-info` error."""


@docs_group('Errors')
class CannotRemoveRunningRunError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-remove-running-run` error."""


@docs_group('Errors')
class CannotRemoveUserWithPublicActorsError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-remove-user-with-public-actors` error."""


@docs_group('Errors')
class CannotRemoveUserWithSubscriptionError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-remove-user-with-subscription` error."""


@docs_group('Errors')
class CannotRemoveUserWithUnpaidInvoiceError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-remove-user-with-unpaid-invoice` error."""


@docs_group('Errors')
class CannotRenameEnvVarError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-rename-env-var` error."""


@docs_group('Errors')
class CannotRentPaidActorError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-rent-paid-actor` error."""


@docs_group('Errors')
class CannotReviewOwnActorError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-review-own-actor` error."""


@docs_group('Errors')
class CannotSetAccessRightsForOwnerError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-set-access-rights-for-owner` error."""


@docs_group('Errors')
class CannotSetIsStatusMessageTerminalError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-set-is-status-message-terminal` error."""


@docs_group('Errors')
class CannotUnpublishCriticalActorError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-unpublish-critical-actor` error."""


@docs_group('Errors')
class CannotUnpublishPaidActorError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-unpublish-paid-actor` error."""


@docs_group('Errors')
class CannotUnpublishProfileError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-unpublish-profile` error."""


@docs_group('Errors')
class CannotUpdateInvoiceFieldError(ApifyApiError):
    """Raised when the Apify API returns a `cannot-update-invoice-field` error."""


@docs_group('Errors')
class ConcurrentRunsLimitExceededError(ApifyApiError):
    """Raised when the Apify API returns a `concurrent-runs-limit-exceeded` error."""


@docs_group('Errors')
class ConcurrentUpdateDetectedError(ApifyApiError):
    """Raised when the Apify API returns a `concurrent-update-detected` error."""


@docs_group('Errors')
class ConferenceTokenNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `conference-token-not-found` error."""


@docs_group('Errors')
class ContentEncodingForbiddenForHtmlError(ApifyApiError):
    """Raised when the Apify API returns a `content-encoding-forbidden-for-html` error."""


@docs_group('Errors')
class CouponAlreadyRedeemedError(ApifyApiError):
    """Raised when the Apify API returns a `coupon-already-redeemed` error."""


@docs_group('Errors')
class CouponExpiredError(ApifyApiError):
    """Raised when the Apify API returns a `coupon-expired` error."""


@docs_group('Errors')
class CouponForNewCustomersError(ApifyApiError):
    """Raised when the Apify API returns a `coupon-for-new-customers` error."""


@docs_group('Errors')
class CouponForSubscribedUsersError(ApifyApiError):
    """Raised when the Apify API returns a `coupon-for-subscribed-users` error."""


@docs_group('Errors')
class CouponLimitsAreInConflictWithCurrentLimitsError(ApifyApiError):
    """Raised when the Apify API returns a `coupon-limits-are-in-conflict-with-current-limits` error."""


@docs_group('Errors')
class CouponMaxNumberOfRedemptionsReachedError(ApifyApiError):
    """Raised when the Apify API returns a `coupon-max-number-of-redemptions-reached` error."""


@docs_group('Errors')
class CouponNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `coupon-not-found` error."""


@docs_group('Errors')
class CouponNotUniqueError(ApifyApiError):
    """Raised when the Apify API returns a `coupon-not-unique` error."""


@docs_group('Errors')
class CouponsDisabledError(ApifyApiError):
    """Raised when the Apify API returns a `coupons-disabled` error."""


@docs_group('Errors')
class CreateGithubIssueNotAllowedError(ApifyApiError):
    """Raised when the Apify API returns a `create-github-issue-not-allowed` error."""


@docs_group('Errors')
class CreatorPlanNotAvailableError(ApifyApiError):
    """Raised when the Apify API returns a `creator-plan-not-available` error."""


@docs_group('Errors')
class CronExpressionInvalidError(ApifyApiError):
    """Raised when the Apify API returns a `cron-expression-invalid` error."""


@docs_group('Errors')
class DailyAiTokenLimitExceededError(ApifyApiError):
    """Raised when the Apify API returns a `daily-ai-token-limit-exceeded` error."""


@docs_group('Errors')
class DailyPublicationLimitExceededError(ApifyApiError):
    """Raised when the Apify API returns a `daily-publication-limit-exceeded` error."""


@docs_group('Errors')
class DatasetDoesNotHaveFieldsSchemaError(ApifyApiError):
    """Raised when the Apify API returns a `dataset-does-not-have-fields-schema` error."""


@docs_group('Errors')
class DatasetDoesNotHaveSchemaError(ApifyApiError):
    """Raised when the Apify API returns a `dataset-does-not-have-schema` error."""


@docs_group('Errors')
class DatasetLockedError(ApifyApiError):
    """Raised when the Apify API returns a `dataset-locked` error."""


@docs_group('Errors')
class DatasetSchemaInvalidError(ApifyApiError):
    """Raised when the Apify API returns a `dataset-schema-invalid` error."""


@docs_group('Errors')
class DcrNotSupportedError(ApifyApiError):
    """Raised when the Apify API returns a `dcr-not-supported` error."""


@docs_group('Errors')
class DefaultDatasetNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `default-dataset-not-found` error."""


@docs_group('Errors')
class DeletingDefaultBuildError(ApifyApiError):
    """Raised when the Apify API returns a `deleting-default-build` error."""


@docs_group('Errors')
class DeletingUnfinishedBuildError(ApifyApiError):
    """Raised when the Apify API returns a `deleting-unfinished-build` error."""


@docs_group('Errors')
class EmailAlreadyTakenError(ApifyApiError):
    """Raised when the Apify API returns a `email-already-taken` error."""


@docs_group('Errors')
class EmailAlreadyTakenRemovedUserError(ApifyApiError):
    """Raised when the Apify API returns a `email-already-taken-removed-user` error."""


@docs_group('Errors')
class EmailDomainNotAllowedForCouponError(ApifyApiError):
    """Raised when the Apify API returns a `email-domain-not-allowed-for-coupon` error."""


@docs_group('Errors')
class EmailInvalidError(ApifyApiError):
    """Raised when the Apify API returns a `email-invalid` error."""


@docs_group('Errors')
class EmailNotAllowedError(ApifyApiError):
    """Raised when the Apify API returns a `email-not-allowed` error."""


@docs_group('Errors')
class EmailNotValidError(ApifyApiError):
    """Raised when the Apify API returns a `email-not-valid` error."""


@docs_group('Errors')
class EmailUpdateTooSoonError(ApifyApiError):
    """Raised when the Apify API returns a `email-update-too-soon` error."""


@docs_group('Errors')
class ElevatedPermissionsNeededError(ApifyApiError):
    """Raised when the Apify API returns a `elevated-permissions-needed` error."""


@docs_group('Errors')
class EnvVarAlreadyExistsError(ApifyApiError):
    """Raised when the Apify API returns a `env-var-already-exists` error."""


@docs_group('Errors')
class ExchangeRateFetchFailedError(ApifyApiError):
    """Raised when the Apify API returns a `exchange-rate-fetch-failed` error."""


@docs_group('Errors')
class ExpiredConferenceTokenError(ApifyApiError):
    """Raised when the Apify API returns a `expired-conference-token` error."""


@docs_group('Errors')
class FailedToChargeUserError(ApifyApiError):
    """Raised when the Apify API returns a `failed-to-charge-user` error."""


@docs_group('Errors')
class FinalInvoiceNegativeError(ApifyApiError):
    """Raised when the Apify API returns a `final-invoice-negative` error."""


@docs_group('Errors')
class GithubBranchEmptyError(ApifyApiError):
    """Raised when the Apify API returns a `github-branch-empty` error."""


@docs_group('Errors')
class GithubIssueAlreadyExistsError(ApifyApiError):
    """Raised when the Apify API returns a `github-issue-already-exists` error."""


@docs_group('Errors')
class GithubPublicKeyNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `github-public-key-not-found` error."""


@docs_group('Errors')
class GithubRepositoryNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `github-repository-not-found` error."""


@docs_group('Errors')
class GithubSignatureDoesNotMatchPayloadError(ApifyApiError):
    """Raised when the Apify API returns a `github-signature-does-not-match-payload` error."""


@docs_group('Errors')
class GithubUserNotAuthorizedForIssuesError(ApifyApiError):
    """Raised when the Apify API returns a `github-user-not-authorized-for-issues` error."""


@docs_group('Errors')
class GmailNotAllowedError(ApifyApiError):
    """Raised when the Apify API returns a `gmail-not-allowed` error."""


@docs_group('Errors')
class IdDoesNotMatchError(ApifyApiError):
    """Raised when the Apify API returns a `id-does-not-match` error."""


@docs_group('Errors')
class IncompatibleBillingIntervalError(ApifyApiError):
    """Raised when the Apify API returns a `incompatible-billing-interval` error."""


@docs_group('Errors')
class IncompletePayoutBillingInfoError(ApifyApiError):
    """Raised when the Apify API returns a `incomplete-payout-billing-info` error."""


@docs_group('Errors')
class InconsistentCurrenciesError(ApifyApiError):
    """Raised when the Apify API returns a `inconsistent-currencies` error."""


@docs_group('Errors')
class IncorrectPricingModifierPrefixError(ApifyApiError):
    """Raised when the Apify API returns a `incorrect-pricing-modifier-prefix` error."""


@docs_group('Errors')
class InputJsonInvalidCharactersError(ApifyApiError):
    """Raised when the Apify API returns a `input-json-invalid-characters` error."""


@docs_group('Errors')
class InputJsonNotObjectError(ApifyApiError):
    """Raised when the Apify API returns a `input-json-not-object` error."""


@docs_group('Errors')
class InputJsonTooLongError(ApifyApiError):
    """Raised when the Apify API returns a `input-json-too-long` error."""


@docs_group('Errors')
class InputUpdateCollisionError(ApifyApiError):
    """Raised when the Apify API returns a `input-update-collision` error."""


@docs_group('Errors')
class InsufficientPermissionsError(ApifyApiError):
    """Raised when the Apify API returns a `insufficient-permissions` error."""


@docs_group('Errors')
class InsufficientPermissionsToChangeFieldError(ApifyApiError):
    """Raised when the Apify API returns a `insufficient-permissions-to-change-field` error."""


@docs_group('Errors')
class InsufficientSecurityMeasuresError(ApifyApiError):
    """Raised when the Apify API returns a `insufficient-security-measures` error."""


@docs_group('Errors')
class InsufficientTaxCountryEvidenceError(ApifyApiError):
    """Raised when the Apify API returns a `insufficient-tax-country-evidence` error."""


@docs_group('Errors')
class IntegrationAuthError(ApifyApiError):
    """Raised when the Apify API returns a `integration-auth-error` error."""


@docs_group('Errors')
class InternalServerError(ApifyApiError):
    """Raised when the Apify API returns a `internal-server-error` error."""


@docs_group('Errors')
class InvalidBillingInfoError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-billing-info` error."""


@docs_group('Errors')
class InvalidBillingPeriodForPayoutError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-billing-period-for-payout` error."""


@docs_group('Errors')
class InvalidBuildError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-build` error."""


@docs_group('Errors')
class InvalidClientKeyError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-client-key` error."""


@docs_group('Errors')
class InvalidCollectionError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-collection` error."""


@docs_group('Errors')
class InvalidConferenceLoginPasswordError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-conference-login-password` error."""


@docs_group('Errors')
class InvalidContentTypeHeaderError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-content-type-header` error."""


@docs_group('Errors')
class InvalidCredentialsError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-credentials` error."""


@docs_group('Errors')
class InvalidGitAuthTokenError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-git-auth-token` error."""


@docs_group('Errors')
class InvalidGithubIssueUrlError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-github-issue-url` error."""


@docs_group('Errors')
class InvalidHeaderError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-header` error."""


@docs_group('Errors')
class InvalidIdError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-id` error."""


@docs_group('Errors')
class InvalidIdempotencyKeyError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-idempotency-key` error."""


@docs_group('Errors')
class InvalidInputError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-input` error."""


@docs_group('Errors')
class InvalidInputSchemaError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-input-schema` error."""


@docs_group('Errors')
class InvalidInvoiceError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-invoice` error."""


@docs_group('Errors')
class InvalidInvoiceTypeError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-invoice-type` error."""


@docs_group('Errors')
class InvalidIssueDateError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-issue-date` error."""


@docs_group('Errors')
class InvalidLabelParamsError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-label-params` error."""


@docs_group('Errors')
class InvalidMainAccountUserIdError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-main-account-user-id` error."""


@docs_group('Errors')
class InvalidOauthAppError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-oauth-app` error."""


@docs_group('Errors')
class InvalidOauthScopeError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-oauth-scope` error."""


@docs_group('Errors')
class InvalidOneTimeInvoiceError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-one-time-invoice` error."""


@docs_group('Errors')
class InvalidParameterError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-parameter` error."""


@docs_group('Errors')
class InvalidPayoutStatusError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-payout-status` error."""


@docs_group('Errors')
class InvalidPictureUrlError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-picture-url` error."""


@docs_group('Errors')
class InvalidRecordKeyError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-record-key` error."""


@docs_group('Errors')
class InvalidRequestError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-request` error."""


@docs_group('Errors')
class InvalidResourceTypeError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-resource-type` error."""


@docs_group('Errors')
class InvalidSignatureError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-signature` error."""


@docs_group('Errors')
class InvalidSubscriptionPlanError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-subscription-plan` error."""


@docs_group('Errors')
class InvalidTaxNumberError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-tax-number` error."""


@docs_group('Errors')
class InvalidTaxNumberFormatError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-tax-number-format` error."""


@docs_group('Errors')
class InvalidTokenError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-token` error."""


@docs_group('Errors')
class InvalidTokenTypeError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-token-type` error."""


@docs_group('Errors')
class InvalidTwoFactorCodeError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-two-factor-code` error."""


@docs_group('Errors')
class InvalidTwoFactorCodeOrRecoveryCodeError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-two-factor-code-or-recovery-code` error."""


@docs_group('Errors')
class InvalidTwoFactorRecoveryCodeError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-two-factor-recovery-code` error."""


@docs_group('Errors')
class InvalidUsernameError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-username` error."""


@docs_group('Errors')
class InvalidValueError(ApifyApiError):
    """Raised when the Apify API returns a `invalid-value` error."""


@docs_group('Errors')
class InvitationInvalidResourceTypeError(ApifyApiError):
    """Raised when the Apify API returns a `invitation-invalid-resource-type` error."""


@docs_group('Errors')
class InvitationNoLongerValidError(ApifyApiError):
    """Raised when the Apify API returns a `invitation-no-longer-valid` error."""


@docs_group('Errors')
class InvoiceCanceledError(ApifyApiError):
    """Raised when the Apify API returns a `invoice-canceled` error."""


@docs_group('Errors')
class InvoiceCannotBeRefundedDueToTooHighAmountError(ApifyApiError):
    """Raised when the Apify API returns a `invoice-cannot-be-refunded-due-to-too-high-amount` error."""


@docs_group('Errors')
class InvoiceIncompleteError(ApifyApiError):
    """Raised when the Apify API returns a `invoice-incomplete` error."""


@docs_group('Errors')
class InvoiceIsDraftError(ApifyApiError):
    """Raised when the Apify API returns a `invoice-is-draft` error."""


@docs_group('Errors')
class InvoiceLockedError(ApifyApiError):
    """Raised when the Apify API returns a `invoice-locked` error."""


@docs_group('Errors')
class InvoiceMustBeBufferError(ApifyApiError):
    """Raised when the Apify API returns a `invoice-must-be-buffer` error."""


@docs_group('Errors')
class InvoiceNotCanceledError(ApifyApiError):
    """Raised when the Apify API returns a `invoice-not-canceled` error."""


@docs_group('Errors')
class InvoiceNotDraftError(ApifyApiError):
    """Raised when the Apify API returns a `invoice-not-draft` error."""


@docs_group('Errors')
class InvoiceNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `invoice-not-found` error."""


@docs_group('Errors')
class InvoiceOutdatedError(ApifyApiError):
    """Raised when the Apify API returns a `invoice-outdated` error."""


@docs_group('Errors')
class InvoicePaidAlreadyError(ApifyApiError):
    """Raised when the Apify API returns a `invoice-paid-already` error."""


@docs_group('Errors')
class IssueAlreadyConnectedToGithubError(ApifyApiError):
    """Raised when the Apify API returns a `issue-already-connected-to-github` error."""


@docs_group('Errors')
class IssueNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `issue-not-found` error."""


@docs_group('Errors')
class IssuesBadRequestError(ApifyApiError):
    """Raised when the Apify API returns a `issues-bad-request` error."""


@docs_group('Errors')
class IssuerNotRegisteredError(ApifyApiError):
    """Raised when the Apify API returns a `issuer-not-registered` error."""


@docs_group('Errors')
class JobFinishedError(ApifyApiError):
    """Raised when the Apify API returns a `job-finished` error."""


@docs_group('Errors')
class LabelAlreadyLinkedError(ApifyApiError):
    """Raised when the Apify API returns a `label-already-linked` error."""


@docs_group('Errors')
class LastApiTokenError(ApifyApiError):
    """Raised when the Apify API returns a `last-api-token` error."""


@docs_group('Errors')
class LimitReachedError(ApifyApiError):
    """Raised when the Apify API returns a `limit-reached` error."""


@docs_group('Errors')
class MaxItemsMustBeGreaterThanZeroError(ApifyApiError):
    """Raised when the Apify API returns a `max-items-must-be-greater-than-zero` error."""


@docs_group('Errors')
class MaxMetamorphsExceededError(ApifyApiError):
    """Raised when the Apify API returns a `max-metamorphs-exceeded` error."""


@docs_group('Errors')
class MaxTotalChargeUsdBelowMinimumError(ApifyApiError):
    """Raised when the Apify API returns a `max-total-charge-usd-below-minimum` error."""


@docs_group('Errors')
class MaxTotalChargeUsdMustBeGreaterThanZeroError(ApifyApiError):
    """Raised when the Apify API returns a `max-total-charge-usd-must-be-greater-than-zero` error."""


@docs_group('Errors')
class MethodNotAllowedError(ApifyApiError):
    """Raised when the Apify API returns a `method-not-allowed` error."""


@docs_group('Errors')
class MigrationDisabledError(ApifyApiError):
    """Raised when the Apify API returns a `migration-disabled` error."""


@docs_group('Errors')
class MissingActorRightsError(ApifyApiError):
    """Raised when the Apify API returns a `missing-actor-rights` error."""


@docs_group('Errors')
class MissingApiTokenError(ApifyApiError):
    """Raised when the Apify API returns a `missing-api-token` error."""


@docs_group('Errors')
class MissingBillingInfoError(ApifyApiError):
    """Raised when the Apify API returns a `missing-billing-info` error."""


@docs_group('Errors')
class MissingLineItemsError(ApifyApiError):
    """Raised when the Apify API returns a `missing-line-items` error."""


@docs_group('Errors')
class MissingPaymentDateError(ApifyApiError):
    """Raised when the Apify API returns a `missing-payment-date` error."""


@docs_group('Errors')
class MissingPayoutBillingInfoError(ApifyApiError):
    """Raised when the Apify API returns a `missing-payout-billing-info` error."""


@docs_group('Errors')
class MissingProxyPasswordError(ApifyApiError):
    """Raised when the Apify API returns a `missing-proxy-password` error."""


@docs_group('Errors')
class MissingReportingFieldsError(ApifyApiError):
    """Raised when the Apify API returns a `missing-reporting-fields` error."""


@docs_group('Errors')
class MissingResourceNameError(ApifyApiError):
    """Raised when the Apify API returns a `missing-resource-name` error."""


@docs_group('Errors')
class MissingSettingsError(ApifyApiError):
    """Raised when the Apify API returns a `missing-settings` error."""


@docs_group('Errors')
class MissingUsernameError(ApifyApiError):
    """Raised when the Apify API returns a `missing-username` error."""


@docs_group('Errors')
class MonthlyUsageLimitTooLowError(ApifyApiError):
    """Raised when the Apify API returns a `monthly-usage-limit-too-low` error."""


@docs_group('Errors')
class MoreThanOneUpdateNotAllowedError(ApifyApiError):
    """Raised when the Apify API returns a `more-than-one-update-not-allowed` error."""


@docs_group('Errors')
class MultipleRecordsFoundError(ApifyApiError):
    """Raised when the Apify API returns a `multiple-records-found` error."""


@docs_group('Errors')
class MustBeAdminError(ApifyApiError):
    """Raised when the Apify API returns a `must-be-admin` error."""


@docs_group('Errors')
class NameNotUniqueError(ApifyApiError):
    """Raised when the Apify API returns a `name-not-unique` error."""


@docs_group('Errors')
class NextRuntimeComputationFailedError(ApifyApiError):
    """Raised when the Apify API returns a `next-runtime-computation-failed` error."""


@docs_group('Errors')
class NoColumnsInExportedDatasetError(ApifyApiError):
    """Raised when the Apify API returns a `no-columns-in-exported-dataset` error."""


@docs_group('Errors')
class NoPaymentAttemptForRefundFoundError(ApifyApiError):
    """Raised when the Apify API returns a `no-payment-attempt-for-refund-found` error."""


@docs_group('Errors')
class NoPaymentMethodAvailableError(ApifyApiError):
    """Raised when the Apify API returns a `no-payment-method-available` error."""


@docs_group('Errors')
class NoTeamAccountSeatsAvailableError(ApifyApiError):
    """Raised when the Apify API returns a `no-team-account-seats-available` error."""


@docs_group('Errors')
class NonTemporaryEmailError(ApifyApiError):
    """Raised when the Apify API returns a `non-temporary-email` error."""


@docs_group('Errors')
class NotEnoughUsageToRunPaidActorError(ApifyApiError):
    """Raised when the Apify API returns a `not-enough-usage-to-run-paid-actor` error."""


@docs_group('Errors')
class ApiNotImplementedError(ApifyApiError):
    """Raised when the Apify API returns a `not-implemented` error."""


@docs_group('Errors')
class NotSupportedCurrenciesError(ApifyApiError):
    """Raised when the Apify API returns a `not-supported-currencies` error."""


@docs_group('Errors')
class OAuthServiceAlreadyConnectedError(ApifyApiError):
    """Raised when the Apify API returns a `o-auth-service-already-connected` error."""


@docs_group('Errors')
class OAuthServiceNotConnectedError(ApifyApiError):
    """Raised when the Apify API returns a `o-auth-service-not-connected` error."""


@docs_group('Errors')
class OauthResourceAccessFailedError(ApifyApiError):
    """Raised when the Apify API returns a `oauth-resource-access-failed` error."""


@docs_group('Errors')
class OneTimeInvoiceAlreadyMarkedPaidError(ApifyApiError):
    """Raised when the Apify API returns a `one-time-invoice-already-marked-paid` error."""


@docs_group('Errors')
class OnlyDraftsCanBeDeletedError(ApifyApiError):
    """Raised when the Apify API returns a `only-drafts-can-be-deleted` error."""


@docs_group('Errors')
class OperationCanceledError(ApifyApiError):
    """Raised when the Apify API returns a `operation-canceled` error."""


@docs_group('Errors')
class OperationNotAllowedError(ApifyApiError):
    """Raised when the Apify API returns a `operation-not-allowed` error."""


@docs_group('Errors')
class OperationTimedOutError(ApifyApiError):
    """Raised when the Apify API returns a `operation-timed-out` error."""


@docs_group('Errors')
class OrganizationCannotOwnItselfError(ApifyApiError):
    """Raised when the Apify API returns a `organization-cannot-own-itself` error."""


@docs_group('Errors')
class OrganizationRoleNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `organization-role-not-found` error."""


@docs_group('Errors')
class OverlappingPayoutBillingPeriodsError(ApifyApiError):
    """Raised when the Apify API returns a `overlapping-payout-billing-periods` error."""


@docs_group('Errors')
class OwnTokenRequiredError(ApifyApiError):
    """Raised when the Apify API returns a `own-token-required` error."""


@docs_group('Errors')
class PageNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `page-not-found` error."""


@docs_group('Errors')
class ParamNotOneOfError(ApifyApiError):
    """Raised when the Apify API returns a `param-not-one-of` error."""


@docs_group('Errors')
class ParameterRequiredError(ApifyApiError):
    """Raised when the Apify API returns a `parameter-required` error."""


@docs_group('Errors')
class ParametersMismatchedError(ApifyApiError):
    """Raised when the Apify API returns a `parameters-mismatched` error."""


@docs_group('Errors')
class PasswordResetEmailAlreadySentError(ApifyApiError):
    """Raised when the Apify API returns a `password-reset-email-already-sent` error."""


@docs_group('Errors')
class PasswordResetTokenExpiredError(ApifyApiError):
    """Raised when the Apify API returns a `password-reset-token-expired` error."""


@docs_group('Errors')
class PayAsYouGoWithoutMonthlyIntervalError(ApifyApiError):
    """Raised when the Apify API returns a `pay-as-you-go-without-monthly-interval` error."""


@docs_group('Errors')
class PaymentAttemptStatusMessageRequiredError(ApifyApiError):
    """Raised when the Apify API returns a `payment-attempt-status-message-required` error."""


@docs_group('Errors')
class PayoutAlreadyPaidError(ApifyApiError):
    """Raised when the Apify API returns a `payout-already-paid` error."""


@docs_group('Errors')
class PayoutCanceledError(ApifyApiError):
    """Raised when the Apify API returns a `payout-canceled` error."""


@docs_group('Errors')
class PayoutInvalidStateError(ApifyApiError):
    """Raised when the Apify API returns a `payout-invalid-state` error."""


@docs_group('Errors')
class PayoutMustBeApprovedToBeMarkedPaidError(ApifyApiError):
    """Raised when the Apify API returns a `payout-must-be-approved-to-be-marked-paid` error."""


@docs_group('Errors')
class PayoutNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `payout-not-found` error."""


@docs_group('Errors')
class PayoutNumberAlreadyExistsError(ApifyApiError):
    """Raised when the Apify API returns a `payout-number-already-exists` error."""


@docs_group('Errors')
class PhoneNumberInvalidError(ApifyApiError):
    """Raised when the Apify API returns a `phone-number-invalid` error."""


@docs_group('Errors')
class PhoneNumberLandlineError(ApifyApiError):
    """Raised when the Apify API returns a `phone-number-landline` error."""


@docs_group('Errors')
class PhoneNumberOptedOutError(ApifyApiError):
    """Raised when the Apify API returns a `phone-number-opted-out` error."""


@docs_group('Errors')
class PhoneVerificationDisabledError(ApifyApiError):
    """Raised when the Apify API returns a `phone-verification-disabled` error."""


@docs_group('Errors')
class PlatformFeatureDisabledError(ApifyApiError):
    """Raised when the Apify API returns a `platform-feature-disabled` error."""


@docs_group('Errors')
class PriceOverridesValidationFailedError(ApifyApiError):
    """Raised when the Apify API returns a `price-overrides-validation-failed` error."""


@docs_group('Errors')
class PricingModelNotSupportedError(ApifyApiError):
    """Raised when the Apify API returns a `pricing-model-not-supported` error."""


@docs_group('Errors')
class PromotionalPlanNotAvailableError(ApifyApiError):
    """Raised when the Apify API returns a `promotional-plan-not-available` error."""


@docs_group('Errors')
class ProxyAuthIpNotUniqueError(ApifyApiError):
    """Raised when the Apify API returns a `proxy-auth-ip-not-unique` error."""


@docs_group('Errors')
class PublicActorDisabledError(ApifyApiError):
    """Raised when the Apify API returns a `public-actor-disabled` error."""


@docs_group('Errors')
class QueryTimeoutError(ApifyApiError):
    """Raised when the Apify API returns a `query-timeout` error."""


@docs_group('Errors')
class QuotedPriceOutdatedError(ApifyApiError):
    """Raised when the Apify API returns a `quoted-price-outdated` error."""


@docs_group('Errors')
class RateLimitExceededError(ApifyApiError):
    """Raised when the Apify API returns a `rate-limit-exceeded` error."""


@docs_group('Errors')
class RecaptchaInvalidError(ApifyApiError):
    """Raised when the Apify API returns a `recaptcha-invalid` error."""


@docs_group('Errors')
class RecaptchaRequiredError(ApifyApiError):
    """Raised when the Apify API returns a `recaptcha-required` error."""


@docs_group('Errors')
class RecordNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `record-not-found` error."""


@docs_group('Errors')
class RecordNotPublicError(ApifyApiError):
    """Raised when the Apify API returns a `record-not-public` error."""


@docs_group('Errors')
class RecordOrTokenNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `record-or-token-not-found` error."""


@docs_group('Errors')
class RecordTooLargeError(ApifyApiError):
    """Raised when the Apify API returns a `record-too-large` error."""


@docs_group('Errors')
class RedirectUriMismatchError(ApifyApiError):
    """Raised when the Apify API returns a `redirect-uri-mismatch` error."""


@docs_group('Errors')
class ReducedPlanNotAvailableError(ApifyApiError):
    """Raised when the Apify API returns a `reduced-plan-not-available` error."""


@docs_group('Errors')
class RentalChargeAlreadyReimbursedError(ApifyApiError):
    """Raised when the Apify API returns a `rental-charge-already-reimbursed` error."""


@docs_group('Errors')
class RentalNotAllowedError(ApifyApiError):
    """Raised when the Apify API returns a `rental-not-allowed` error."""


@docs_group('Errors')
class RequestAbortedPrematurelyError(ApifyApiError):
    """Raised when the Apify API returns a `request-aborted-prematurely` error."""


@docs_group('Errors')
class RequestHandledOrLockedError(ApifyApiError):
    """Raised when the Apify API returns a `request-handled-or-locked` error."""


@docs_group('Errors')
class RequestIdInvalidError(ApifyApiError):
    """Raised when the Apify API returns a `request-id-invalid` error."""


@docs_group('Errors')
class RequestQueueDuplicateRequestsError(ApifyApiError):
    """Raised when the Apify API returns a `request-queue-duplicate-requests` error."""


@docs_group('Errors')
class RequestTooLargeError(ApifyApiError):
    """Raised when the Apify API returns a `request-too-large` error."""


@docs_group('Errors')
class RequestedDatasetViewDoesNotExistError(ApifyApiError):
    """Raised when the Apify API returns a `requested-dataset-view-does-not-exist` error."""


@docs_group('Errors')
class ResumeTokenExpiredError(ApifyApiError):
    """Raised when the Apify API returns a `resume-token-expired` error."""


@docs_group('Errors')
class RunFailedError(ApifyApiError):
    """Raised when the Apify API returns a `run-failed` error."""


@docs_group('Errors')
class RunTimeoutExceededError(ApifyApiError):
    """Raised when the Apify API returns a `run-timeout-exceeded` error."""


@docs_group('Errors')
class RussiaIsEvilError(ApifyApiError):
    """Raised when the Apify API returns a `russia-is-evil` error."""


@docs_group('Errors')
class SameUserError(ApifyApiError):
    """Raised when the Apify API returns a `same-user` error."""


@docs_group('Errors')
class ScheduleActorNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `schedule-actor-not-found` error."""


@docs_group('Errors')
class ScheduleActorTaskNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `schedule-actor-task-not-found` error."""


@docs_group('Errors')
class ScheduleNameNotUniqueError(ApifyApiError):
    """Raised when the Apify API returns a `schedule-name-not-unique` error."""


@docs_group('Errors')
class SchemaValidationError(ApifyApiError):
    """Raised when the Apify API returns a `schema-validation` error."""


@docs_group('Errors')
class SchemaValidationErrorError(ApifyApiError):
    """Raised when the Apify API returns a `schema-validation-error` error."""


@docs_group('Errors')
class SchemaValidationFailedError(ApifyApiError):
    """Raised when the Apify API returns a `schema-validation-failed` error."""


@docs_group('Errors')
class SignUpMethodNotAllowedError(ApifyApiError):
    """Raised when the Apify API returns a `sign-up-method-not-allowed` error."""


@docs_group('Errors')
class SlackIntegrationNotCustomError(ApifyApiError):
    """Raised when the Apify API returns a `slack-integration-not-custom` error."""


@docs_group('Errors')
class SocketClosedError(ApifyApiError):
    """Raised when the Apify API returns a `socket-closed` error."""


@docs_group('Errors')
class SocketDestroyedError(ApifyApiError):
    """Raised when the Apify API returns a `socket-destroyed` error."""


@docs_group('Errors')
class StoreSchemaInvalidError(ApifyApiError):
    """Raised when the Apify API returns a `store-schema-invalid` error."""


@docs_group('Errors')
class StoreTermsNotAcceptedError(ApifyApiError):
    """Raised when the Apify API returns a `store-terms-not-accepted` error."""


@docs_group('Errors')
class StripeEnabledError(ApifyApiError):
    """Raised when the Apify API returns a `stripe-enabled` error."""


@docs_group('Errors')
class StripeGenericDeclineError(ApifyApiError):
    """Raised when the Apify API returns a `stripe-generic-decline` error."""


@docs_group('Errors')
class StripeNotEnabledError(ApifyApiError):
    """Raised when the Apify API returns a `stripe-not-enabled` error."""


@docs_group('Errors')
class StripeNotEnabledForUserError(ApifyApiError):
    """Raised when the Apify API returns a `stripe-not-enabled-for-user` error."""


@docs_group('Errors')
class TaggedBuildRequiredError(ApifyApiError):
    """Raised when the Apify API returns a `tagged-build-required` error."""


@docs_group('Errors')
class TaxCountryInvalidError(ApifyApiError):
    """Raised when the Apify API returns a `tax-country-invalid` error."""


@docs_group('Errors')
class TaxNumberInvalidError(ApifyApiError):
    """Raised when the Apify API returns a `tax-number-invalid` error."""


@docs_group('Errors')
class TaxNumberValidationFailedError(ApifyApiError):
    """Raised when the Apify API returns a `tax-number-validation-failed` error."""


@docs_group('Errors')
class TaxamoCallFailedError(ApifyApiError):
    """Raised when the Apify API returns a `taxamo-call-failed` error."""


@docs_group('Errors')
class TaxamoRequestFailedError(ApifyApiError):
    """Raised when the Apify API returns a `taxamo-request-failed` error."""


@docs_group('Errors')
class TestingError(ApifyApiError):
    """Raised when the Apify API returns a `testing-error` error."""


@docs_group('Errors')
class TokenNotProvidedError(ApifyApiError):
    """Raised when the Apify API returns a `token-not-provided` error."""


@docs_group('Errors')
class TooFewVersionsError(ApifyApiError):
    """Raised when the Apify API returns a `too-few-versions` error."""


@docs_group('Errors')
class TooManyActorTasksError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-actor-tasks` error."""


@docs_group('Errors')
class TooManyActorsError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-actors` error."""


@docs_group('Errors')
class TooManyLabelsOnResourceError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-labels-on-resource` error."""


@docs_group('Errors')
class TooManyMcpConnectorsError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-mcp-connectors` error."""


@docs_group('Errors')
class TooManyOAuthAppsError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-o-auth-apps` error."""


@docs_group('Errors')
class TooManyOrganizationsError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-organizations` error."""


@docs_group('Errors')
class TooManyRequestsError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-requests` error."""


@docs_group('Errors')
class TooManySchedulesError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-schedules` error."""


@docs_group('Errors')
class TooManyUiAccessKeysError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-ui-access-keys` error."""


@docs_group('Errors')
class TooManyUserLabelsError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-user-labels` error."""


@docs_group('Errors')
class TooManyValuesError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-values` error."""


@docs_group('Errors')
class TooManyVersionsError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-versions` error."""


@docs_group('Errors')
class TooManyWebhooksError(ApifyApiError):
    """Raised when the Apify API returns a `too-many-webhooks` error."""


@docs_group('Errors')
class UnexpectedRouteError(ApifyApiError):
    """Raised when the Apify API returns a `unexpected-route` error."""


@docs_group('Errors')
class UnknownBuildTagError(ApifyApiError):
    """Raised when the Apify API returns a `unknown-build-tag` error."""


@docs_group('Errors')
class UnknownPaymentProviderError(ApifyApiError):
    """Raised when the Apify API returns a `unknown-payment-provider` error."""


@docs_group('Errors')
class UnsubscribeTokenInvalidError(ApifyApiError):
    """Raised when the Apify API returns a `unsubscribe-token-invalid` error."""


@docs_group('Errors')
class UnsupportedActorPricingModelForAgenticPaymentsError(ApifyApiError):
    """Raised when the Apify API returns a `unsupported-actor-pricing-model-for-agentic-payments` error."""


@docs_group('Errors')
class UnsupportedContentEncodingError(ApifyApiError):
    """Raised when the Apify API returns a `unsupported-content-encoding` error."""


@docs_group('Errors')
class UnsupportedFileTypeForIssueError(ApifyApiError):
    """Raised when the Apify API returns a `unsupported-file-type-for-issue` error."""


@docs_group('Errors')
class UnsupportedFileTypeImageExpectedError(ApifyApiError):
    """Raised when the Apify API returns a `unsupported-file-type-image-expected` error."""


@docs_group('Errors')
class UnsupportedFileTypeTextOrJsonExpectedError(ApifyApiError):
    """Raised when the Apify API returns a `unsupported-file-type-text-or-json-expected` error."""


@docs_group('Errors')
class UnsupportedPermissionError(ApifyApiError):
    """Raised when the Apify API returns a `unsupported-permission` error."""


@docs_group('Errors')
class UpcomingSubscriptionBillNotUpToDateError(ApifyApiError):
    """Raised when the Apify API returns a `upcoming-subscription-bill-not-up-to-date` error."""


@docs_group('Errors')
class UserAlreadyExistsError(ApifyApiError):
    """Raised when the Apify API returns a `user-already-exists` error."""


@docs_group('Errors')
class UserAlreadyVerifiedError(ApifyApiError):
    """Raised when the Apify API returns a `user-already-verified` error."""


@docs_group('Errors')
class UserCreatesOrganizationsTooFastError(ApifyApiError):
    """Raised when the Apify API returns a `user-creates-organizations-too-fast` error."""


@docs_group('Errors')
class UserDisabledError(ApifyApiError):
    """Raised when the Apify API returns a `user-disabled` error."""


@docs_group('Errors')
class UserEmailIsDisposableError(ApifyApiError):
    """Raised when the Apify API returns a `user-email-is-disposable` error."""


@docs_group('Errors')
class UserEmailNotSetError(ApifyApiError):
    """Raised when the Apify API returns a `user-email-not-set` error."""


@docs_group('Errors')
class UserEmailNotVerifiedError(ApifyApiError):
    """Raised when the Apify API returns a `user-email-not-verified` error."""


@docs_group('Errors')
class UserHasNoSubscriptionError(ApifyApiError):
    """Raised when the Apify API returns a `user-has-no-subscription` error."""


@docs_group('Errors')
class UserIntegrationNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `user-integration-not-found` error."""


@docs_group('Errors')
class UserIsAlreadyInvitedError(ApifyApiError):
    """Raised when the Apify API returns a `user-is-already-invited` error."""


@docs_group('Errors')
class UserIsAlreadyOrganizationMemberError(ApifyApiError):
    """Raised when the Apify API returns a `user-is-already-organization-member` error."""


@docs_group('Errors')
class UserIsNotMemberOfOrganizationError(ApifyApiError):
    """Raised when the Apify API returns a `user-is-not-member-of-organization` error."""


@docs_group('Errors')
class UserIsNotOrganizationError(ApifyApiError):
    """Raised when the Apify API returns a `user-is-not-organization` error."""


@docs_group('Errors')
class UserIsOrganizationError(ApifyApiError):
    """Raised when the Apify API returns a `user-is-organization` error."""


@docs_group('Errors')
class UserIsOrganizationOwnerError(ApifyApiError):
    """Raised when the Apify API returns a `user-is-organization-owner` error."""


@docs_group('Errors')
class UserIsRemovedError(ApifyApiError):
    """Raised when the Apify API returns a `user-is-removed` error."""


@docs_group('Errors')
class UserNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `user-not-found` error."""


@docs_group('Errors')
class UserNotLoggedInError(ApifyApiError):
    """Raised when the Apify API returns a `user-not-logged-in` error."""


@docs_group('Errors')
class UserNotVerifiedError(ApifyApiError):
    """Raised when the Apify API returns a `user-not-verified` error."""


@docs_group('Errors')
class UserOrTokenNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `user-or-token-not-found` error."""


@docs_group('Errors')
class UserPlanNotAllowedForCouponError(ApifyApiError):
    """Raised when the Apify API returns a `user-plan-not-allowed-for-coupon` error."""


@docs_group('Errors')
class UserProblemWithCardError(ApifyApiError):
    """Raised when the Apify API returns a `user-problem-with-card` error."""


@docs_group('Errors')
class UserRecordNotFoundError(ApifyApiError):
    """Raised when the Apify API returns a `user-record-not-found` error."""


@docs_group('Errors')
class UsernameAlreadyTakenError(ApifyApiError):
    """Raised when the Apify API returns a `username-already-taken` error."""


@docs_group('Errors')
class UsernameMissingError(ApifyApiError):
    """Raised when the Apify API returns a `username-missing` error."""


@docs_group('Errors')
class UsernameNotAllowedError(ApifyApiError):
    """Raised when the Apify API returns a `username-not-allowed` error."""


@docs_group('Errors')
class UsernameRemovalForbiddenError(ApifyApiError):
    """Raised when the Apify API returns a `username-removal-forbidden` error."""


@docs_group('Errors')
class UsernameRequiredError(ApifyApiError):
    """Raised when the Apify API returns a `username-required` error."""


@docs_group('Errors')
class VerificationEmailAlreadySentError(ApifyApiError):
    """Raised when the Apify API returns a `verification-email-already-sent` error."""


@docs_group('Errors')
class VerificationTokenExpiredError(ApifyApiError):
    """Raised when the Apify API returns a `verification-token-expired` error."""


@docs_group('Errors')
class VersionAlreadyExistsError(ApifyApiError):
    """Raised when the Apify API returns a `version-already-exists` error."""


@docs_group('Errors')
class VersionsSizeExceededError(ApifyApiError):
    """Raised when the Apify API returns a `versions-size-exceeded` error."""


@docs_group('Errors')
class WeakPasswordError(ApifyApiError):
    """Raised when the Apify API returns a `weak-password` error."""


@docs_group('Errors')
class X402AgenticPaymentAlreadyFinalizedError(ApifyApiError):
    """Raised when the Apify API returns a `x402-agentic-payment-already-finalized` error."""


@docs_group('Errors')
class X402AgenticPaymentInsufficientAmountError(ApifyApiError):
    """Raised when the Apify API returns a `x402-agentic-payment-insufficient-amount` error."""


@docs_group('Errors')
class X402AgenticPaymentMalformedTokenError(ApifyApiError):
    """Raised when the Apify API returns a `x402-agentic-payment-malformed-token` error."""


@docs_group('Errors')
class X402AgenticPaymentSettlementFailedError(ApifyApiError):
    """Raised when the Apify API returns a `x402-agentic-payment-settlement-failed` error."""


@docs_group('Errors')
class X402AgenticPaymentSettlementInProgressError(ApifyApiError):
    """Raised when the Apify API returns a `x402-agentic-payment-settlement-in-progress` error."""


@docs_group('Errors')
class X402AgenticPaymentSettlementStuckError(ApifyApiError):
    """Raised when the Apify API returns a `x402-agentic-payment-settlement-stuck` error."""


@docs_group('Errors')
class X402AgenticPaymentUnauthorizedError(ApifyApiError):
    """Raised when the Apify API returns a `x402-agentic-payment-unauthorized` error."""


@docs_group('Errors')
class X402PaymentRequiredError(ApifyApiError):
    """Raised when the Apify API returns a `x402-payment-required` error."""


@docs_group('Errors')
class ZeroInvoiceError(ApifyApiError):
    """Raised when the Apify API returns a `zero-invoice` error."""


API_ERROR_CLASS_BY_TYPE: dict[str, type[ApifyApiError]] = {
    '3d-secure-auth-failed': Field3DSecureAuthFailedError,
    'access-right-already-exists': AccessRightAlreadyExistsError,
    'action-not-found': ActionNotFoundError,
    'actor-already-rented': ActorAlreadyRentedError,
    'actor-can-not-be-rented': ActorCanNotBeRentedError,
    'actor-disabled': ActorDisabledError,
    'actor-is-not-rented': ActorIsNotRentedError,
    'actor-memory-limit-exceeded': ActorMemoryLimitExceededError,
    'actor-name-exists-new-owner': ActorNameExistsNewOwnerError,
    'actor-name-not-unique': ActorNameNotUniqueError,
    'actor-not-found': ActorNotFoundError,
    'actor-not-github-actor': ActorNotGithubActorError,
    'actor-not-public': ActorNotPublicError,
    'actor-permission-level-not-supported-for-agentic-payments': ActorPermissionLevelNotSupportedForAgenticPaymentsError,
    'actor-review-already-exists': ActorReviewAlreadyExistsError,
    'actor-run-failed': ActorRunFailedError,
    'actor-standby-not-supported-for-agentic-payments': ActorStandbyNotSupportedForAgenticPaymentsError,
    'actor-task-name-not-unique': ActorTaskNameNotUniqueError,
    'agentic-payment-info-retrieval-error': AgenticPaymentInfoRetrievalError,
    'agentic-payment-information-missing': AgenticPaymentInformationMissingError,
    'agentic-payment-insufficient-amount': AgenticPaymentInsufficientAmountError,
    'agentic-payment-provider-internal-error': AgenticPaymentProviderInternalError,
    'agentic-payment-provider-unauthorized': AgenticPaymentProviderUnauthorizedError,
    'airtable-webhook-deprecated': AirtableWebhookDeprecatedError,
    'already-subscribed-to-paid-actor': AlreadySubscribedToPaidActorError,
    'apify-plan-required-to-use-paid-actor': ApifyPlanRequiredToUsePaidActorError,
    'apify-signup-not-allowed': ApifySignupNotAllowedError,
    'auth-method-not-supported': AuthMethodNotSupportedError,
    'authorization-server-not-found': AuthorizationServerNotFoundError,
    'auto-issue-date-invalid': AutoIssueDateInvalidError,
    'background-check-required': BackgroundCheckRequiredError,
    'billing-system-error': BillingSystemError,
    'black-friday-plan-expired': BlackFridayPlanExpiredError,
    'braintree-error': BraintreeError,
    'braintree-not-linked': BraintreeNotLinkedError,
    'braintree-operation-timed-out': BraintreeOperationTimedOutError,
    'braintree-unsupported-currency': BraintreeUnsupportedCurrencyError,
    'build-not-found': BuildNotFoundError,
    'build-outdated': BuildOutdatedError,
    'cannot-add-apify-events-to-ppe-actor': CannotAddApifyEventsToPpeActorError,
    'cannot-add-multiple-pricing-infos': CannotAddMultiplePricingInfosError,
    'cannot-add-pricing-info-that-alters-past': CannotAddPricingInfoThatAltersPastError,
    'cannot-add-second-future-pricing-info': CannotAddSecondFuturePricingInfoError,
    'cannot-build-actor-from-webhook': CannotBuildActorFromWebhookError,
    'cannot-change-billing-interval': CannotChangeBillingIntervalError,
    'cannot-change-owner': CannotChangeOwnerError,
    'cannot-charge-apify-event': CannotChargeApifyEventError,
    'cannot-charge-non-pay-per-event-actor': CannotChargeNonPayPerEventActorError,
    'cannot-comment-as-other-user': CannotCommentAsOtherUserError,
    'cannot-copy-actor-task': CannotCopyActorTaskError,
    'cannot-create-payout': CannotCreatePayoutError,
    'cannot-create-public-actor': CannotCreatePublicActorError,
    'cannot-create-tax-transaction': CannotCreateTaxTransactionError,
    'cannot-delete-critical-actor': CannotDeleteCriticalActorError,
    'cannot-delete-invoice': CannotDeleteInvoiceError,
    'cannot-delete-paid-actor': CannotDeletePaidActorError,
    'cannot-disable-one-time-event-for-apify-start-event': CannotDisableOneTimeEventForApifyStartEventError,
    'cannot-disable-organization-with-enabled-members': CannotDisableOrganizationWithEnabledMembersError,
    'cannot-disable-user-with-subscription': CannotDisableUserWithSubscriptionError,
    'cannot-link-oauth-to-unverified-email': CannotLinkOauthToUnverifiedEmailError,
    'cannot-metamorph-to-pay-per-result-actor': CannotMetamorphToPayPerResultActorError,
    'cannot-modify-actor-pricing-too-frequently': CannotModifyActorPricingTooFrequentlyError,
    'cannot-modify-actor-pricing-with-immediate-effect': CannotModifyActorPricingWithImmediateEffectError,
    'cannot-override-paid-actor-trial': CannotOverridePaidActorTrialError,
    'cannot-permanently-delete-subscription': CannotPermanentlyDeleteSubscriptionError,
    'cannot-publish-actor': CannotPublishActorError,
    'cannot-reduce-last-full-token': CannotReduceLastFullTokenError,
    'cannot-reimburse-more-than-original-charge': CannotReimburseMoreThanOriginalChargeError,
    'cannot-reimburse-non-rental-charge': CannotReimburseNonRentalChargeError,
    'cannot-remove-own-actor-from-recently-used': CannotRemoveOwnActorFromRecentlyUsedError,
    'cannot-remove-payment-method': CannotRemovePaymentMethodError,
    'cannot-remove-pricing-info': CannotRemovePricingInfoError,
    'cannot-remove-running-run': CannotRemoveRunningRunError,
    'cannot-remove-user-with-public-actors': CannotRemoveUserWithPublicActorsError,
    'cannot-remove-user-with-subscription': CannotRemoveUserWithSubscriptionError,
    'cannot-remove-user-with-unpaid-invoice': CannotRemoveUserWithUnpaidInvoiceError,
    'cannot-rename-env-var': CannotRenameEnvVarError,
    'cannot-rent-paid-actor': CannotRentPaidActorError,
    'cannot-review-own-actor': CannotReviewOwnActorError,
    'cannot-set-access-rights-for-owner': CannotSetAccessRightsForOwnerError,
    'cannot-set-is-status-message-terminal': CannotSetIsStatusMessageTerminalError,
    'cannot-unpublish-critical-actor': CannotUnpublishCriticalActorError,
    'cannot-unpublish-paid-actor': CannotUnpublishPaidActorError,
    'cannot-unpublish-profile': CannotUnpublishProfileError,
    'cannot-update-invoice-field': CannotUpdateInvoiceFieldError,
    'concurrent-runs-limit-exceeded': ConcurrentRunsLimitExceededError,
    'concurrent-update-detected': ConcurrentUpdateDetectedError,
    'conference-token-not-found': ConferenceTokenNotFoundError,
    'content-encoding-forbidden-for-html': ContentEncodingForbiddenForHtmlError,
    'coupon-already-redeemed': CouponAlreadyRedeemedError,
    'coupon-expired': CouponExpiredError,
    'coupon-for-new-customers': CouponForNewCustomersError,
    'coupon-for-subscribed-users': CouponForSubscribedUsersError,
    'coupon-limits-are-in-conflict-with-current-limits': CouponLimitsAreInConflictWithCurrentLimitsError,
    'coupon-max-number-of-redemptions-reached': CouponMaxNumberOfRedemptionsReachedError,
    'coupon-not-found': CouponNotFoundError,
    'coupon-not-unique': CouponNotUniqueError,
    'coupons-disabled': CouponsDisabledError,
    'create-github-issue-not-allowed': CreateGithubIssueNotAllowedError,
    'creator-plan-not-available': CreatorPlanNotAvailableError,
    'cron-expression-invalid': CronExpressionInvalidError,
    'daily-ai-token-limit-exceeded': DailyAiTokenLimitExceededError,
    'daily-publication-limit-exceeded': DailyPublicationLimitExceededError,
    'dataset-does-not-have-fields-schema': DatasetDoesNotHaveFieldsSchemaError,
    'dataset-does-not-have-schema': DatasetDoesNotHaveSchemaError,
    'dataset-locked': DatasetLockedError,
    'dataset-schema-invalid': DatasetSchemaInvalidError,
    'dcr-not-supported': DcrNotSupportedError,
    'default-dataset-not-found': DefaultDatasetNotFoundError,
    'deleting-default-build': DeletingDefaultBuildError,
    'deleting-unfinished-build': DeletingUnfinishedBuildError,
    'email-already-taken': EmailAlreadyTakenError,
    'email-already-taken-removed-user': EmailAlreadyTakenRemovedUserError,
    'email-domain-not-allowed-for-coupon': EmailDomainNotAllowedForCouponError,
    'email-invalid': EmailInvalidError,
    'email-not-allowed': EmailNotAllowedError,
    'email-not-valid': EmailNotValidError,
    'email-update-too-soon': EmailUpdateTooSoonError,
    'elevated-permissions-needed': ElevatedPermissionsNeededError,
    'env-var-already-exists': EnvVarAlreadyExistsError,
    'exchange-rate-fetch-failed': ExchangeRateFetchFailedError,
    'expired-conference-token': ExpiredConferenceTokenError,
    'failed-to-charge-user': FailedToChargeUserError,
    'final-invoice-negative': FinalInvoiceNegativeError,
    'github-branch-empty': GithubBranchEmptyError,
    'github-issue-already-exists': GithubIssueAlreadyExistsError,
    'github-public-key-not-found': GithubPublicKeyNotFoundError,
    'github-repository-not-found': GithubRepositoryNotFoundError,
    'github-signature-does-not-match-payload': GithubSignatureDoesNotMatchPayloadError,
    'github-user-not-authorized-for-issues': GithubUserNotAuthorizedForIssuesError,
    'gmail-not-allowed': GmailNotAllowedError,
    'id-does-not-match': IdDoesNotMatchError,
    'incompatible-billing-interval': IncompatibleBillingIntervalError,
    'incomplete-payout-billing-info': IncompletePayoutBillingInfoError,
    'inconsistent-currencies': InconsistentCurrenciesError,
    'incorrect-pricing-modifier-prefix': IncorrectPricingModifierPrefixError,
    'input-json-invalid-characters': InputJsonInvalidCharactersError,
    'input-json-not-object': InputJsonNotObjectError,
    'input-json-too-long': InputJsonTooLongError,
    'input-update-collision': InputUpdateCollisionError,
    'insufficient-permissions': InsufficientPermissionsError,
    'insufficient-permissions-to-change-field': InsufficientPermissionsToChangeFieldError,
    'insufficient-security-measures': InsufficientSecurityMeasuresError,
    'insufficient-tax-country-evidence': InsufficientTaxCountryEvidenceError,
    'integration-auth-error': IntegrationAuthError,
    'internal-server-error': InternalServerError,
    'invalid-billing-info': InvalidBillingInfoError,
    'invalid-billing-period-for-payout': InvalidBillingPeriodForPayoutError,
    'invalid-build': InvalidBuildError,
    'invalid-client-key': InvalidClientKeyError,
    'invalid-collection': InvalidCollectionError,
    'invalid-conference-login-password': InvalidConferenceLoginPasswordError,
    'invalid-content-type-header': InvalidContentTypeHeaderError,
    'invalid-credentials': InvalidCredentialsError,
    'invalid-git-auth-token': InvalidGitAuthTokenError,
    'invalid-github-issue-url': InvalidGithubIssueUrlError,
    'invalid-header': InvalidHeaderError,
    'invalid-id': InvalidIdError,
    'invalid-idempotency-key': InvalidIdempotencyKeyError,
    'invalid-input': InvalidInputError,
    'invalid-input-schema': InvalidInputSchemaError,
    'invalid-invoice': InvalidInvoiceError,
    'invalid-invoice-type': InvalidInvoiceTypeError,
    'invalid-issue-date': InvalidIssueDateError,
    'invalid-label-params': InvalidLabelParamsError,
    'invalid-main-account-user-id': InvalidMainAccountUserIdError,
    'invalid-oauth-app': InvalidOauthAppError,
    'invalid-oauth-scope': InvalidOauthScopeError,
    'invalid-one-time-invoice': InvalidOneTimeInvoiceError,
    'invalid-parameter': InvalidParameterError,
    'invalid-payout-status': InvalidPayoutStatusError,
    'invalid-picture-url': InvalidPictureUrlError,
    'invalid-record-key': InvalidRecordKeyError,
    'invalid-request': InvalidRequestError,
    'invalid-resource-type': InvalidResourceTypeError,
    'invalid-signature': InvalidSignatureError,
    'invalid-subscription-plan': InvalidSubscriptionPlanError,
    'invalid-tax-number': InvalidTaxNumberError,
    'invalid-tax-number-format': InvalidTaxNumberFormatError,
    'invalid-token': InvalidTokenError,
    'invalid-token-type': InvalidTokenTypeError,
    'invalid-two-factor-code': InvalidTwoFactorCodeError,
    'invalid-two-factor-code-or-recovery-code': InvalidTwoFactorCodeOrRecoveryCodeError,
    'invalid-two-factor-recovery-code': InvalidTwoFactorRecoveryCodeError,
    'invalid-username': InvalidUsernameError,
    'invalid-value': InvalidValueError,
    'invitation-invalid-resource-type': InvitationInvalidResourceTypeError,
    'invitation-no-longer-valid': InvitationNoLongerValidError,
    'invoice-canceled': InvoiceCanceledError,
    'invoice-cannot-be-refunded-due-to-too-high-amount': InvoiceCannotBeRefundedDueToTooHighAmountError,
    'invoice-incomplete': InvoiceIncompleteError,
    'invoice-is-draft': InvoiceIsDraftError,
    'invoice-locked': InvoiceLockedError,
    'invoice-must-be-buffer': InvoiceMustBeBufferError,
    'invoice-not-canceled': InvoiceNotCanceledError,
    'invoice-not-draft': InvoiceNotDraftError,
    'invoice-not-found': InvoiceNotFoundError,
    'invoice-outdated': InvoiceOutdatedError,
    'invoice-paid-already': InvoicePaidAlreadyError,
    'issue-already-connected-to-github': IssueAlreadyConnectedToGithubError,
    'issue-not-found': IssueNotFoundError,
    'issues-bad-request': IssuesBadRequestError,
    'issuer-not-registered': IssuerNotRegisteredError,
    'job-finished': JobFinishedError,
    'label-already-linked': LabelAlreadyLinkedError,
    'last-api-token': LastApiTokenError,
    'limit-reached': LimitReachedError,
    'max-items-must-be-greater-than-zero': MaxItemsMustBeGreaterThanZeroError,
    'max-metamorphs-exceeded': MaxMetamorphsExceededError,
    'max-total-charge-usd-below-minimum': MaxTotalChargeUsdBelowMinimumError,
    'max-total-charge-usd-must-be-greater-than-zero': MaxTotalChargeUsdMustBeGreaterThanZeroError,
    'method-not-allowed': MethodNotAllowedError,
    'migration-disabled': MigrationDisabledError,
    'missing-actor-rights': MissingActorRightsError,
    'missing-api-token': MissingApiTokenError,
    'missing-billing-info': MissingBillingInfoError,
    'missing-line-items': MissingLineItemsError,
    'missing-payment-date': MissingPaymentDateError,
    'missing-payout-billing-info': MissingPayoutBillingInfoError,
    'missing-proxy-password': MissingProxyPasswordError,
    'missing-reporting-fields': MissingReportingFieldsError,
    'missing-resource-name': MissingResourceNameError,
    'missing-settings': MissingSettingsError,
    'missing-username': MissingUsernameError,
    'monthly-usage-limit-too-low': MonthlyUsageLimitTooLowError,
    'more-than-one-update-not-allowed': MoreThanOneUpdateNotAllowedError,
    'multiple-records-found': MultipleRecordsFoundError,
    'must-be-admin': MustBeAdminError,
    'name-not-unique': NameNotUniqueError,
    'next-runtime-computation-failed': NextRuntimeComputationFailedError,
    'no-columns-in-exported-dataset': NoColumnsInExportedDatasetError,
    'no-payment-attempt-for-refund-found': NoPaymentAttemptForRefundFoundError,
    'no-payment-method-available': NoPaymentMethodAvailableError,
    'no-team-account-seats-available': NoTeamAccountSeatsAvailableError,
    'non-temporary-email': NonTemporaryEmailError,
    'not-enough-usage-to-run-paid-actor': NotEnoughUsageToRunPaidActorError,
    'not-implemented': ApiNotImplementedError,
    'not-supported-currencies': NotSupportedCurrenciesError,
    'o-auth-service-already-connected': OAuthServiceAlreadyConnectedError,
    'o-auth-service-not-connected': OAuthServiceNotConnectedError,
    'oauth-resource-access-failed': OauthResourceAccessFailedError,
    'one-time-invoice-already-marked-paid': OneTimeInvoiceAlreadyMarkedPaidError,
    'only-drafts-can-be-deleted': OnlyDraftsCanBeDeletedError,
    'operation-canceled': OperationCanceledError,
    'operation-not-allowed': OperationNotAllowedError,
    'operation-timed-out': OperationTimedOutError,
    'organization-cannot-own-itself': OrganizationCannotOwnItselfError,
    'organization-role-not-found': OrganizationRoleNotFoundError,
    'overlapping-payout-billing-periods': OverlappingPayoutBillingPeriodsError,
    'own-token-required': OwnTokenRequiredError,
    'page-not-found': PageNotFoundError,
    'param-not-one-of': ParamNotOneOfError,
    'parameter-required': ParameterRequiredError,
    'parameters-mismatched': ParametersMismatchedError,
    'password-reset-email-already-sent': PasswordResetEmailAlreadySentError,
    'password-reset-token-expired': PasswordResetTokenExpiredError,
    'pay-as-you-go-without-monthly-interval': PayAsYouGoWithoutMonthlyIntervalError,
    'payment-attempt-status-message-required': PaymentAttemptStatusMessageRequiredError,
    'payout-already-paid': PayoutAlreadyPaidError,
    'payout-canceled': PayoutCanceledError,
    'payout-invalid-state': PayoutInvalidStateError,
    'payout-must-be-approved-to-be-marked-paid': PayoutMustBeApprovedToBeMarkedPaidError,
    'payout-not-found': PayoutNotFoundError,
    'payout-number-already-exists': PayoutNumberAlreadyExistsError,
    'phone-number-invalid': PhoneNumberInvalidError,
    'phone-number-landline': PhoneNumberLandlineError,
    'phone-number-opted-out': PhoneNumberOptedOutError,
    'phone-verification-disabled': PhoneVerificationDisabledError,
    'platform-feature-disabled': PlatformFeatureDisabledError,
    'price-overrides-validation-failed': PriceOverridesValidationFailedError,
    'pricing-model-not-supported': PricingModelNotSupportedError,
    'promotional-plan-not-available': PromotionalPlanNotAvailableError,
    'proxy-auth-ip-not-unique': ProxyAuthIpNotUniqueError,
    'public-actor-disabled': PublicActorDisabledError,
    'query-timeout': QueryTimeoutError,
    'quoted-price-outdated': QuotedPriceOutdatedError,
    'rate-limit-exceeded': RateLimitExceededError,
    'recaptcha-invalid': RecaptchaInvalidError,
    'recaptcha-required': RecaptchaRequiredError,
    'record-not-found': RecordNotFoundError,
    'record-not-public': RecordNotPublicError,
    'record-or-token-not-found': RecordOrTokenNotFoundError,
    'record-too-large': RecordTooLargeError,
    'redirect-uri-mismatch': RedirectUriMismatchError,
    'reduced-plan-not-available': ReducedPlanNotAvailableError,
    'rental-charge-already-reimbursed': RentalChargeAlreadyReimbursedError,
    'rental-not-allowed': RentalNotAllowedError,
    'request-aborted-prematurely': RequestAbortedPrematurelyError,
    'request-handled-or-locked': RequestHandledOrLockedError,
    'request-id-invalid': RequestIdInvalidError,
    'request-queue-duplicate-requests': RequestQueueDuplicateRequestsError,
    'request-too-large': RequestTooLargeError,
    'requested-dataset-view-does-not-exist': RequestedDatasetViewDoesNotExistError,
    'resume-token-expired': ResumeTokenExpiredError,
    'run-failed': RunFailedError,
    'run-timeout-exceeded': RunTimeoutExceededError,
    'russia-is-evil': RussiaIsEvilError,
    'same-user': SameUserError,
    'schedule-actor-not-found': ScheduleActorNotFoundError,
    'schedule-actor-task-not-found': ScheduleActorTaskNotFoundError,
    'schedule-name-not-unique': ScheduleNameNotUniqueError,
    'schema-validation': SchemaValidationError,
    'schema-validation-error': SchemaValidationErrorError,
    'schema-validation-failed': SchemaValidationFailedError,
    'sign-up-method-not-allowed': SignUpMethodNotAllowedError,
    'slack-integration-not-custom': SlackIntegrationNotCustomError,
    'socket-closed': SocketClosedError,
    'socket-destroyed': SocketDestroyedError,
    'store-schema-invalid': StoreSchemaInvalidError,
    'store-terms-not-accepted': StoreTermsNotAcceptedError,
    'stripe-enabled': StripeEnabledError,
    'stripe-generic-decline': StripeGenericDeclineError,
    'stripe-not-enabled': StripeNotEnabledError,
    'stripe-not-enabled-for-user': StripeNotEnabledForUserError,
    'tagged-build-required': TaggedBuildRequiredError,
    'tax-country-invalid': TaxCountryInvalidError,
    'tax-number-invalid': TaxNumberInvalidError,
    'tax-number-validation-failed': TaxNumberValidationFailedError,
    'taxamo-call-failed': TaxamoCallFailedError,
    'taxamo-request-failed': TaxamoRequestFailedError,
    'testing-error': TestingError,
    'token-not-provided': TokenNotProvidedError,
    'too-few-versions': TooFewVersionsError,
    'too-many-actor-tasks': TooManyActorTasksError,
    'too-many-actors': TooManyActorsError,
    'too-many-labels-on-resource': TooManyLabelsOnResourceError,
    'too-many-mcp-connectors': TooManyMcpConnectorsError,
    'too-many-o-auth-apps': TooManyOAuthAppsError,
    'too-many-organizations': TooManyOrganizationsError,
    'too-many-requests': TooManyRequestsError,
    'too-many-schedules': TooManySchedulesError,
    'too-many-ui-access-keys': TooManyUiAccessKeysError,
    'too-many-user-labels': TooManyUserLabelsError,
    'too-many-values': TooManyValuesError,
    'too-many-versions': TooManyVersionsError,
    'too-many-webhooks': TooManyWebhooksError,
    'unexpected-route': UnexpectedRouteError,
    'unknown-build-tag': UnknownBuildTagError,
    'unknown-payment-provider': UnknownPaymentProviderError,
    'unsubscribe-token-invalid': UnsubscribeTokenInvalidError,
    'unsupported-actor-pricing-model-for-agentic-payments': UnsupportedActorPricingModelForAgenticPaymentsError,
    'unsupported-content-encoding': UnsupportedContentEncodingError,
    'unsupported-file-type-for-issue': UnsupportedFileTypeForIssueError,
    'unsupported-file-type-image-expected': UnsupportedFileTypeImageExpectedError,
    'unsupported-file-type-text-or-json-expected': UnsupportedFileTypeTextOrJsonExpectedError,
    'unsupported-permission': UnsupportedPermissionError,
    'upcoming-subscription-bill-not-up-to-date': UpcomingSubscriptionBillNotUpToDateError,
    'user-already-exists': UserAlreadyExistsError,
    'user-already-verified': UserAlreadyVerifiedError,
    'user-creates-organizations-too-fast': UserCreatesOrganizationsTooFastError,
    'user-disabled': UserDisabledError,
    'user-email-is-disposable': UserEmailIsDisposableError,
    'user-email-not-set': UserEmailNotSetError,
    'user-email-not-verified': UserEmailNotVerifiedError,
    'user-has-no-subscription': UserHasNoSubscriptionError,
    'user-integration-not-found': UserIntegrationNotFoundError,
    'user-is-already-invited': UserIsAlreadyInvitedError,
    'user-is-already-organization-member': UserIsAlreadyOrganizationMemberError,
    'user-is-not-member-of-organization': UserIsNotMemberOfOrganizationError,
    'user-is-not-organization': UserIsNotOrganizationError,
    'user-is-organization': UserIsOrganizationError,
    'user-is-organization-owner': UserIsOrganizationOwnerError,
    'user-is-removed': UserIsRemovedError,
    'user-not-found': UserNotFoundError,
    'user-not-logged-in': UserNotLoggedInError,
    'user-not-verified': UserNotVerifiedError,
    'user-or-token-not-found': UserOrTokenNotFoundError,
    'user-plan-not-allowed-for-coupon': UserPlanNotAllowedForCouponError,
    'user-problem-with-card': UserProblemWithCardError,
    'user-record-not-found': UserRecordNotFoundError,
    'username-already-taken': UsernameAlreadyTakenError,
    'username-missing': UsernameMissingError,
    'username-not-allowed': UsernameNotAllowedError,
    'username-removal-forbidden': UsernameRemovalForbiddenError,
    'username-required': UsernameRequiredError,
    'verification-email-already-sent': VerificationEmailAlreadySentError,
    'verification-token-expired': VerificationTokenExpiredError,
    'version-already-exists': VersionAlreadyExistsError,
    'versions-size-exceeded': VersionsSizeExceededError,
    'weak-password': WeakPasswordError,
    'x402-agentic-payment-already-finalized': X402AgenticPaymentAlreadyFinalizedError,
    'x402-agentic-payment-insufficient-amount': X402AgenticPaymentInsufficientAmountError,
    'x402-agentic-payment-malformed-token': X402AgenticPaymentMalformedTokenError,
    'x402-agentic-payment-settlement-failed': X402AgenticPaymentSettlementFailedError,
    'x402-agentic-payment-settlement-in-progress': X402AgenticPaymentSettlementInProgressError,
    'x402-agentic-payment-settlement-stuck': X402AgenticPaymentSettlementStuckError,
    'x402-agentic-payment-unauthorized': X402AgenticPaymentUnauthorizedError,
    'x402-payment-required': X402PaymentRequiredError,
    'zero-invoice': ZeroInvoiceError,
}


__all__ = [
    'API_ERROR_CLASS_BY_TYPE',
    'AccessRightAlreadyExistsError',
    'ActionNotFoundError',
    'ActorAlreadyRentedError',
    'ActorCanNotBeRentedError',
    'ActorDisabledError',
    'ActorIsNotRentedError',
    'ActorMemoryLimitExceededError',
    'ActorNameExistsNewOwnerError',
    'ActorNameNotUniqueError',
    'ActorNotFoundError',
    'ActorNotGithubActorError',
    'ActorNotPublicError',
    'ActorPermissionLevelNotSupportedForAgenticPaymentsError',
    'ActorReviewAlreadyExistsError',
    'ActorRunFailedError',
    'ActorStandbyNotSupportedForAgenticPaymentsError',
    'ActorTaskNameNotUniqueError',
    'AgenticPaymentInfoRetrievalError',
    'AgenticPaymentInformationMissingError',
    'AgenticPaymentInsufficientAmountError',
    'AgenticPaymentProviderInternalError',
    'AgenticPaymentProviderUnauthorizedError',
    'AirtableWebhookDeprecatedError',
    'AlreadySubscribedToPaidActorError',
    'ApiNotImplementedError',
    'ApifyPlanRequiredToUsePaidActorError',
    'ApifySignupNotAllowedError',
    'AuthMethodNotSupportedError',
    'AuthorizationServerNotFoundError',
    'AutoIssueDateInvalidError',
    'BackgroundCheckRequiredError',
    'BillingSystemError',
    'BlackFridayPlanExpiredError',
    'BraintreeError',
    'BraintreeNotLinkedError',
    'BraintreeOperationTimedOutError',
    'BraintreeUnsupportedCurrencyError',
    'BuildNotFoundError',
    'BuildOutdatedError',
    'CannotAddApifyEventsToPpeActorError',
    'CannotAddMultiplePricingInfosError',
    'CannotAddPricingInfoThatAltersPastError',
    'CannotAddSecondFuturePricingInfoError',
    'CannotBuildActorFromWebhookError',
    'CannotChangeBillingIntervalError',
    'CannotChangeOwnerError',
    'CannotChargeApifyEventError',
    'CannotChargeNonPayPerEventActorError',
    'CannotCommentAsOtherUserError',
    'CannotCopyActorTaskError',
    'CannotCreatePayoutError',
    'CannotCreatePublicActorError',
    'CannotCreateTaxTransactionError',
    'CannotDeleteCriticalActorError',
    'CannotDeleteInvoiceError',
    'CannotDeletePaidActorError',
    'CannotDisableOneTimeEventForApifyStartEventError',
    'CannotDisableOrganizationWithEnabledMembersError',
    'CannotDisableUserWithSubscriptionError',
    'CannotLinkOauthToUnverifiedEmailError',
    'CannotMetamorphToPayPerResultActorError',
    'CannotModifyActorPricingTooFrequentlyError',
    'CannotModifyActorPricingWithImmediateEffectError',
    'CannotOverridePaidActorTrialError',
    'CannotPermanentlyDeleteSubscriptionError',
    'CannotPublishActorError',
    'CannotReduceLastFullTokenError',
    'CannotReimburseMoreThanOriginalChargeError',
    'CannotReimburseNonRentalChargeError',
    'CannotRemoveOwnActorFromRecentlyUsedError',
    'CannotRemovePaymentMethodError',
    'CannotRemovePricingInfoError',
    'CannotRemoveRunningRunError',
    'CannotRemoveUserWithPublicActorsError',
    'CannotRemoveUserWithSubscriptionError',
    'CannotRemoveUserWithUnpaidInvoiceError',
    'CannotRenameEnvVarError',
    'CannotRentPaidActorError',
    'CannotReviewOwnActorError',
    'CannotSetAccessRightsForOwnerError',
    'CannotSetIsStatusMessageTerminalError',
    'CannotUnpublishCriticalActorError',
    'CannotUnpublishPaidActorError',
    'CannotUnpublishProfileError',
    'CannotUpdateInvoiceFieldError',
    'ConcurrentRunsLimitExceededError',
    'ConcurrentUpdateDetectedError',
    'ConferenceTokenNotFoundError',
    'ContentEncodingForbiddenForHtmlError',
    'CouponAlreadyRedeemedError',
    'CouponExpiredError',
    'CouponForNewCustomersError',
    'CouponForSubscribedUsersError',
    'CouponLimitsAreInConflictWithCurrentLimitsError',
    'CouponMaxNumberOfRedemptionsReachedError',
    'CouponNotFoundError',
    'CouponNotUniqueError',
    'CouponsDisabledError',
    'CreateGithubIssueNotAllowedError',
    'CreatorPlanNotAvailableError',
    'CronExpressionInvalidError',
    'DailyAiTokenLimitExceededError',
    'DailyPublicationLimitExceededError',
    'DatasetDoesNotHaveFieldsSchemaError',
    'DatasetDoesNotHaveSchemaError',
    'DatasetLockedError',
    'DatasetSchemaInvalidError',
    'DcrNotSupportedError',
    'DefaultDatasetNotFoundError',
    'DeletingDefaultBuildError',
    'DeletingUnfinishedBuildError',
    'ElevatedPermissionsNeededError',
    'EmailAlreadyTakenError',
    'EmailAlreadyTakenRemovedUserError',
    'EmailDomainNotAllowedForCouponError',
    'EmailInvalidError',
    'EmailNotAllowedError',
    'EmailNotValidError',
    'EmailUpdateTooSoonError',
    'EnvVarAlreadyExistsError',
    'ExchangeRateFetchFailedError',
    'ExpiredConferenceTokenError',
    'FailedToChargeUserError',
    'Field3DSecureAuthFailedError',
    'FinalInvoiceNegativeError',
    'GithubBranchEmptyError',
    'GithubIssueAlreadyExistsError',
    'GithubPublicKeyNotFoundError',
    'GithubRepositoryNotFoundError',
    'GithubSignatureDoesNotMatchPayloadError',
    'GithubUserNotAuthorizedForIssuesError',
    'GmailNotAllowedError',
    'IdDoesNotMatchError',
    'IncompatibleBillingIntervalError',
    'IncompletePayoutBillingInfoError',
    'InconsistentCurrenciesError',
    'IncorrectPricingModifierPrefixError',
    'InputJsonInvalidCharactersError',
    'InputJsonNotObjectError',
    'InputJsonTooLongError',
    'InputUpdateCollisionError',
    'InsufficientPermissionsError',
    'InsufficientPermissionsToChangeFieldError',
    'InsufficientSecurityMeasuresError',
    'InsufficientTaxCountryEvidenceError',
    'IntegrationAuthError',
    'InternalServerError',
    'InvalidBillingInfoError',
    'InvalidBillingPeriodForPayoutError',
    'InvalidBuildError',
    'InvalidClientKeyError',
    'InvalidCollectionError',
    'InvalidConferenceLoginPasswordError',
    'InvalidContentTypeHeaderError',
    'InvalidCredentialsError',
    'InvalidGitAuthTokenError',
    'InvalidGithubIssueUrlError',
    'InvalidHeaderError',
    'InvalidIdError',
    'InvalidIdempotencyKeyError',
    'InvalidInputError',
    'InvalidInputSchemaError',
    'InvalidInvoiceError',
    'InvalidInvoiceTypeError',
    'InvalidIssueDateError',
    'InvalidLabelParamsError',
    'InvalidMainAccountUserIdError',
    'InvalidOauthAppError',
    'InvalidOauthScopeError',
    'InvalidOneTimeInvoiceError',
    'InvalidParameterError',
    'InvalidPayoutStatusError',
    'InvalidPictureUrlError',
    'InvalidRecordKeyError',
    'InvalidRequestError',
    'InvalidResourceTypeError',
    'InvalidSignatureError',
    'InvalidSubscriptionPlanError',
    'InvalidTaxNumberError',
    'InvalidTaxNumberFormatError',
    'InvalidTokenError',
    'InvalidTokenTypeError',
    'InvalidTwoFactorCodeError',
    'InvalidTwoFactorCodeOrRecoveryCodeError',
    'InvalidTwoFactorRecoveryCodeError',
    'InvalidUsernameError',
    'InvalidValueError',
    'InvitationInvalidResourceTypeError',
    'InvitationNoLongerValidError',
    'InvoiceCanceledError',
    'InvoiceCannotBeRefundedDueToTooHighAmountError',
    'InvoiceIncompleteError',
    'InvoiceIsDraftError',
    'InvoiceLockedError',
    'InvoiceMustBeBufferError',
    'InvoiceNotCanceledError',
    'InvoiceNotDraftError',
    'InvoiceNotFoundError',
    'InvoiceOutdatedError',
    'InvoicePaidAlreadyError',
    'IssueAlreadyConnectedToGithubError',
    'IssueNotFoundError',
    'IssuerNotRegisteredError',
    'IssuesBadRequestError',
    'JobFinishedError',
    'LabelAlreadyLinkedError',
    'LastApiTokenError',
    'LimitReachedError',
    'MaxItemsMustBeGreaterThanZeroError',
    'MaxMetamorphsExceededError',
    'MaxTotalChargeUsdBelowMinimumError',
    'MaxTotalChargeUsdMustBeGreaterThanZeroError',
    'MethodNotAllowedError',
    'MigrationDisabledError',
    'MissingActorRightsError',
    'MissingApiTokenError',
    'MissingBillingInfoError',
    'MissingLineItemsError',
    'MissingPaymentDateError',
    'MissingPayoutBillingInfoError',
    'MissingProxyPasswordError',
    'MissingReportingFieldsError',
    'MissingResourceNameError',
    'MissingSettingsError',
    'MissingUsernameError',
    'MonthlyUsageLimitTooLowError',
    'MoreThanOneUpdateNotAllowedError',
    'MultipleRecordsFoundError',
    'MustBeAdminError',
    'NameNotUniqueError',
    'NextRuntimeComputationFailedError',
    'NoColumnsInExportedDatasetError',
    'NoPaymentAttemptForRefundFoundError',
    'NoPaymentMethodAvailableError',
    'NoTeamAccountSeatsAvailableError',
    'NonTemporaryEmailError',
    'NotEnoughUsageToRunPaidActorError',
    'NotSupportedCurrenciesError',
    'OAuthServiceAlreadyConnectedError',
    'OAuthServiceNotConnectedError',
    'OauthResourceAccessFailedError',
    'OneTimeInvoiceAlreadyMarkedPaidError',
    'OnlyDraftsCanBeDeletedError',
    'OperationCanceledError',
    'OperationNotAllowedError',
    'OperationTimedOutError',
    'OrganizationCannotOwnItselfError',
    'OrganizationRoleNotFoundError',
    'OverlappingPayoutBillingPeriodsError',
    'OwnTokenRequiredError',
    'PageNotFoundError',
    'ParamNotOneOfError',
    'ParameterRequiredError',
    'ParametersMismatchedError',
    'PasswordResetEmailAlreadySentError',
    'PasswordResetTokenExpiredError',
    'PayAsYouGoWithoutMonthlyIntervalError',
    'PaymentAttemptStatusMessageRequiredError',
    'PayoutAlreadyPaidError',
    'PayoutCanceledError',
    'PayoutInvalidStateError',
    'PayoutMustBeApprovedToBeMarkedPaidError',
    'PayoutNotFoundError',
    'PayoutNumberAlreadyExistsError',
    'PhoneNumberInvalidError',
    'PhoneNumberLandlineError',
    'PhoneNumberOptedOutError',
    'PhoneVerificationDisabledError',
    'PlatformFeatureDisabledError',
    'PriceOverridesValidationFailedError',
    'PricingModelNotSupportedError',
    'PromotionalPlanNotAvailableError',
    'ProxyAuthIpNotUniqueError',
    'PublicActorDisabledError',
    'QueryTimeoutError',
    'QuotedPriceOutdatedError',
    'RateLimitExceededError',
    'RecaptchaInvalidError',
    'RecaptchaRequiredError',
    'RecordNotFoundError',
    'RecordNotPublicError',
    'RecordOrTokenNotFoundError',
    'RecordTooLargeError',
    'RedirectUriMismatchError',
    'ReducedPlanNotAvailableError',
    'RentalChargeAlreadyReimbursedError',
    'RentalNotAllowedError',
    'RequestAbortedPrematurelyError',
    'RequestHandledOrLockedError',
    'RequestIdInvalidError',
    'RequestQueueDuplicateRequestsError',
    'RequestTooLargeError',
    'RequestedDatasetViewDoesNotExistError',
    'ResumeTokenExpiredError',
    'RunFailedError',
    'RunTimeoutExceededError',
    'RussiaIsEvilError',
    'SameUserError',
    'ScheduleActorNotFoundError',
    'ScheduleActorTaskNotFoundError',
    'ScheduleNameNotUniqueError',
    'SchemaValidationError',
    'SchemaValidationErrorError',
    'SchemaValidationFailedError',
    'SignUpMethodNotAllowedError',
    'SlackIntegrationNotCustomError',
    'SocketClosedError',
    'SocketDestroyedError',
    'StoreSchemaInvalidError',
    'StoreTermsNotAcceptedError',
    'StripeEnabledError',
    'StripeGenericDeclineError',
    'StripeNotEnabledError',
    'StripeNotEnabledForUserError',
    'TaggedBuildRequiredError',
    'TaxCountryInvalidError',
    'TaxNumberInvalidError',
    'TaxNumberValidationFailedError',
    'TaxamoCallFailedError',
    'TaxamoRequestFailedError',
    'TestingError',
    'TokenNotProvidedError',
    'TooFewVersionsError',
    'TooManyActorTasksError',
    'TooManyActorsError',
    'TooManyLabelsOnResourceError',
    'TooManyMcpConnectorsError',
    'TooManyOAuthAppsError',
    'TooManyOrganizationsError',
    'TooManyRequestsError',
    'TooManySchedulesError',
    'TooManyUiAccessKeysError',
    'TooManyUserLabelsError',
    'TooManyValuesError',
    'TooManyVersionsError',
    'TooManyWebhooksError',
    'UnexpectedRouteError',
    'UnknownBuildTagError',
    'UnknownPaymentProviderError',
    'UnsubscribeTokenInvalidError',
    'UnsupportedActorPricingModelForAgenticPaymentsError',
    'UnsupportedContentEncodingError',
    'UnsupportedFileTypeForIssueError',
    'UnsupportedFileTypeImageExpectedError',
    'UnsupportedFileTypeTextOrJsonExpectedError',
    'UnsupportedPermissionError',
    'UpcomingSubscriptionBillNotUpToDateError',
    'UserAlreadyExistsError',
    'UserAlreadyVerifiedError',
    'UserCreatesOrganizationsTooFastError',
    'UserDisabledError',
    'UserEmailIsDisposableError',
    'UserEmailNotSetError',
    'UserEmailNotVerifiedError',
    'UserHasNoSubscriptionError',
    'UserIntegrationNotFoundError',
    'UserIsAlreadyInvitedError',
    'UserIsAlreadyOrganizationMemberError',
    'UserIsNotMemberOfOrganizationError',
    'UserIsNotOrganizationError',
    'UserIsOrganizationError',
    'UserIsOrganizationOwnerError',
    'UserIsRemovedError',
    'UserNotFoundError',
    'UserNotLoggedInError',
    'UserNotVerifiedError',
    'UserOrTokenNotFoundError',
    'UserPlanNotAllowedForCouponError',
    'UserProblemWithCardError',
    'UserRecordNotFoundError',
    'UsernameAlreadyTakenError',
    'UsernameMissingError',
    'UsernameNotAllowedError',
    'UsernameRemovalForbiddenError',
    'UsernameRequiredError',
    'VerificationEmailAlreadySentError',
    'VerificationTokenExpiredError',
    'VersionAlreadyExistsError',
    'VersionsSizeExceededError',
    'WeakPasswordError',
    'X402AgenticPaymentAlreadyFinalizedError',
    'X402AgenticPaymentInsufficientAmountError',
    'X402AgenticPaymentMalformedTokenError',
    'X402AgenticPaymentSettlementFailedError',
    'X402AgenticPaymentSettlementInProgressError',
    'X402AgenticPaymentSettlementStuckError',
    'X402AgenticPaymentUnauthorizedError',
    'X402PaymentRequiredError',
    'ZeroInvoiceError',
]
