# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-01-14T19:13:07+00:00

from __future__ import annotations

from enum import Enum, IntEnum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class PaginationResponse(BaseModel):
    total: Annotated[float, Field(examples=[2])]
    offset: Annotated[float, Field(examples=[0])]
    limit: Annotated[float, Field(examples=[1000])]
    desc: Annotated[bool, Field(examples=[False])]
    count: Annotated[float, Field(examples=[2])]


class ActorStats(BaseModel):
    total_builds: Annotated[float, Field(alias='totalBuilds', examples=[9])]
    total_runs: Annotated[float, Field(alias='totalRuns', examples=[16])]
    total_users: Annotated[float, Field(alias='totalUsers', examples=[6])]
    total_users7_days: Annotated[float, Field(alias='totalUsers7Days', examples=[2])]
    total_users30_days: Annotated[float, Field(alias='totalUsers30Days', examples=[6])]
    total_users90_days: Annotated[float, Field(alias='totalUsers90Days', examples=[6])]
    total_metamorphs: Annotated[float | None, Field(alias='totalMetamorphs', examples=[2])] = None
    last_run_started_at: Annotated[
        str | None, Field(alias='lastRunStartedAt', examples=['2019-07-08T14:01:05.546Z'])
    ] = None


class ActorShort(BaseModel):
    id: Annotated[str, Field(examples=['br9CKmk457'])]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-10-29T07:34:24.202Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2019-10-30T07:34:24.202Z'])]
    name: Annotated[str, Field(examples=['MyAct'])]
    username: Annotated[str, Field(examples=['janedoe'])]
    title: Annotated[str | None, Field(examples=['Hello World Example'])] = None
    stats: ActorStats | None = None


class ListOfActors(PaginationResponse):
    items: list[ActorShort]


class GetListOfActorsResponse(BaseModel):
    data: ListOfActors


class VersionSourceType(Enum):
    SOURCE_FILES = 'SOURCE_FILES'
    GIT_REPO = 'GIT_REPO'
    TARBALL = 'TARBALL'
    GITHUB_GIST = 'GITHUB_GIST'


class EnvVar(BaseModel):
    name: Annotated[str, Field(examples=['MY_ENV_VAR'])]
    value: Annotated[str, Field(examples=['my-value'])]
    is_secret: Annotated[bool | None, Field(alias='isSecret', examples=[False])] = None


class Format(Enum):
    BASE64 = 'BASE64'
    TEXT = 'TEXT'


class SourceCodeFile(BaseModel):
    format: Annotated[Format, Field(examples=['TEXT'])]
    content: Annotated[str, Field(examples=["console.log('This is the main.js file');"])]
    name: Annotated[str, Field(examples=['src/main.js'])]


class Folder(Enum):
    BOOLEAN_TRUE = True


class SourceCodeFolder(BaseModel):
    name: Annotated[str, Field(examples=['src/placeholder'])]
    folder: Annotated[Folder, Field(examples=[True])]


class Version(BaseModel):
    version_number: Annotated[str, Field(alias='versionNumber', examples=['0.0'])]
    source_type: Annotated[Any | VersionSourceType, Field(alias='sourceType')]
    env_vars: Annotated[list[EnvVar] | None, Field(alias='envVars')] = None
    apply_env_vars_to_build: Annotated[bool | None, Field(alias='applyEnvVarsToBuild', examples=[False])] = None
    build_tag: Annotated[str | None, Field(alias='buildTag', examples=['latest'])] = None
    source_files: Annotated[
        list[SourceCodeFile | SourceCodeFolder] | None, Field(alias='sourceFiles', title='VersionSourceFiles')
    ] = None


class CommonActorPricingInfo(BaseModel):
    apify_margin_percentage: Annotated[float, Field(alias='apifyMarginPercentage')]
    """
    In [0, 1], fraction of pricePerUnitUsd that goes to Apify
    """
    created_at: Annotated[AwareDatetime, Field(alias='createdAt')]
    """
    When this pricing info record has been created
    """
    started_at: Annotated[AwareDatetime, Field(alias='startedAt')]
    """
    Since when is this pricing info record effective for a given Actor
    """
    notified_about_future_change_at: Annotated[AwareDatetime | None, Field(alias='notifiedAboutFutureChangeAt')] = None
    notified_about_change_at: Annotated[AwareDatetime | None, Field(alias='notifiedAboutChangeAt')] = None
    reason_for_change: Annotated[str | None, Field(alias='reasonForChange')] = None


class PricingModel(Enum):
    PAY_PER_EVENT = 'PAY_PER_EVENT'
    PRICE_PER_DATASET_ITEM = 'PRICE_PER_DATASET_ITEM'
    FLAT_PRICE_PER_MONTH = 'FLAT_PRICE_PER_MONTH'
    FREE = 'FREE'


class ActorChargeEvent(BaseModel):
    event_price_usd: Annotated[float, Field(alias='eventPriceUsd')]
    event_title: Annotated[str, Field(alias='eventTitle')]
    event_description: Annotated[str, Field(alias='eventDescription')]


class PricingPerEvent(BaseModel):
    actor_charge_events: Annotated[dict[str, ActorChargeEvent] | None, Field(alias='actorChargeEvents')] = None


class PayPerEventActorPricingInfo(CommonActorPricingInfo):
    pricing_model: Annotated[Literal['PAY_PER_EVENT'], Field(alias='pricingModel')]
    pricing_per_event: Annotated[PricingPerEvent, Field(alias='pricingPerEvent')]
    minimal_max_total_charge_usd: Annotated[float | None, Field(alias='minimalMaxTotalChargeUsd')] = None


class PricePerDatasetItemActorPricingInfo(CommonActorPricingInfo):
    pricing_model: Annotated[Literal['PRICE_PER_DATASET_ITEM'], Field(alias='pricingModel')]
    unit_name: Annotated[str, Field(alias='unitName')]
    """
    Name of the unit that is being charged
    """
    price_per_unit_usd: Annotated[float, Field(alias='pricePerUnitUsd')]


class FlatPricePerMonthActorPricingInfo(CommonActorPricingInfo):
    pricing_model: Annotated[Literal['FLAT_PRICE_PER_MONTH'], Field(alias='pricingModel')]
    trial_minutes: Annotated[float, Field(alias='trialMinutes')]
    """
    For how long this Actor can be used for free in trial period
    """
    price_per_unit_usd: Annotated[float, Field(alias='pricePerUnitUsd')]
    """
    Monthly flat price in USD
    """


class FreeActorPricingInfo(CommonActorPricingInfo):
    pricing_model: Annotated[Literal['FREE'], Field(alias='pricingModel')]


class DefaultRunOptions(BaseModel):
    build: Annotated[str, Field(examples=['latest'])]
    timeout_secs: Annotated[float | None, Field(alias='timeoutSecs', examples=[3600])] = None
    memory_mbytes: Annotated[float, Field(alias='memoryMbytes', examples=[2048])]
    restart_on_error: Annotated[bool | None, Field(alias='restartOnError', examples=[False])] = None


class CreateActorRequest(BaseModel):
    name: Annotated[str | None, Field(examples=['MyActor'])] = None
    description: Annotated[str | None, Field(examples=['My favourite actor!'])] = None
    title: Annotated[str | None, Field(examples=['My actor'])] = None
    is_public: Annotated[bool | None, Field(alias='isPublic', examples=[False])] = None
    seo_title: Annotated[str | None, Field(alias='seoTitle', examples=['My actor'])] = None
    seo_description: Annotated[str | None, Field(alias='seoDescription', examples=['My actor is the best'])] = None
    restart_on_error: Annotated[bool | None, Field(alias='restartOnError', examples=[False])] = None
    versions: list[Version] | None = None
    pricing_infos: Annotated[
        list[
            PayPerEventActorPricingInfo
            | PricePerDatasetItemActorPricingInfo
            | FlatPricePerMonthActorPricingInfo
            | FreeActorPricingInfo
        ]
        | None,
        Field(alias='pricingInfos'),
    ] = None
    categories: list[str] | None = None
    default_run_options: Annotated[DefaultRunOptions | None, Field(alias='defaultRunOptions')] = None


class ActorPermissionLevel(Enum):
    """Determines permissions that the Actor requires to run. For more information, see the [Actor permissions documentation](https://docs.apify.com/platform/actors/development/permissions)."""

    LIMITED_PERMISSIONS = 'LIMITED_PERMISSIONS'
    FULL_PERMISSIONS = 'FULL_PERMISSIONS'


class ExampleRunInput(BaseModel):
    body: Annotated[str, Field(examples=[{'helloWorld': 123}])]
    content_type: Annotated[str, Field(alias='contentType', examples=['application/json; charset=utf-8'])]


class Latest(BaseModel):
    build_id: Annotated[str | None, Field(alias='buildId', examples=['z2EryhbfhgSyqj6Hn'])] = None
    build_number: Annotated[str | None, Field(alias='buildNumber', examples=['0.0.2'])] = None
    finished_at: Annotated[str | None, Field(alias='finishedAt', examples=['2019-06-10T11:15:49.286Z'])] = None


class TaggedBuilds(BaseModel):
    latest: Latest | None = None


class Actor(BaseModel):
    id: Annotated[str, Field(examples=['zdc3Pyhyz3m8vjDeM'])]
    user_id: Annotated[str, Field(alias='userId', examples=['wRsJZtadYvn4mBZmm'])]
    name: Annotated[str, Field(examples=['MyActor'])]
    username: Annotated[str, Field(examples=['jane35'])]
    description: Annotated[str | None, Field(examples=['My favourite actor!'])] = None
    restart_on_error: Annotated[bool | None, Field(alias='restartOnError', examples=[False])] = None
    is_public: Annotated[bool, Field(alias='isPublic', examples=[False])]
    actor_permission_level: Annotated[ActorPermissionLevel | None, Field(alias='actorPermissionLevel')] = None
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-07-08T11:27:57.401Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2019-07-08T14:01:05.546Z'])]
    stats: ActorStats
    versions: list[Version]
    pricing_infos: Annotated[
        list[
            PayPerEventActorPricingInfo
            | PricePerDatasetItemActorPricingInfo
            | FlatPricePerMonthActorPricingInfo
            | FreeActorPricingInfo
        ]
        | None,
        Field(alias='pricingInfos'),
    ] = None
    default_run_options: Annotated[DefaultRunOptions, Field(alias='defaultRunOptions')]
    example_run_input: Annotated[ExampleRunInput | None, Field(alias='exampleRunInput')] = None
    is_deprecated: Annotated[bool | None, Field(alias='isDeprecated', examples=[False])] = None
    deployment_key: Annotated[str | None, Field(alias='deploymentKey', examples=['ssh-rsa AAAA ...'])] = None
    title: Annotated[str | None, Field(examples=['My Actor'])] = None
    tagged_builds: Annotated[TaggedBuilds | None, Field(alias='taggedBuilds')] = None


class CreateActorResponse(BaseModel):
    data: Actor


class GetActorResponse(BaseModel):
    data: Actor


class CreateOrUpdateEnvVarRequest(BaseModel):
    name: Annotated[str, Field(examples=['MY_ENV_VAR'])]
    value: Annotated[str, Field(examples=['my-new-value'])]
    is_secret: Annotated[bool | None, Field(alias='isSecret', examples=[False])] = None


class BuildTag(BaseModel):
    build_id: Annotated[str, Field(alias='buildId')]


class UpdateActorRequest(BaseModel):
    name: Annotated[str, Field(examples=['MyActor'])]
    description: Annotated[str | None, Field(examples=['My favourite actor!'])] = None
    is_public: Annotated[bool, Field(alias='isPublic', examples=[False])]
    actor_permission_level: Annotated[ActorPermissionLevel | None, Field(alias='actorPermissionLevel')] = None
    seo_title: Annotated[str | None, Field(alias='seoTitle', examples=['My actor'])] = None
    seo_description: Annotated[str | None, Field(alias='seoDescription', examples=['My actor is the best'])] = None
    title: Annotated[str | None, Field(examples=['My Actor'])] = None
    restart_on_error: Annotated[bool | None, Field(alias='restartOnError', examples=[False])] = None
    versions: list[CreateOrUpdateEnvVarRequest]
    pricing_infos: Annotated[
        list[
            PayPerEventActorPricingInfo
            | PricePerDatasetItemActorPricingInfo
            | FlatPricePerMonthActorPricingInfo
            | FreeActorPricingInfo
        ]
        | None,
        Field(alias='pricingInfos'),
    ] = None
    categories: list[str] | None = None
    default_run_options: Annotated[DefaultRunOptions | None, Field(alias='defaultRunOptions')] = None
    tagged_builds: Annotated[
        dict[str, BuildTag] | None,
        Field(alias='taggedBuilds', examples=[{'latest': {'buildId': 'z2EryhbfhgSyqj6Hn'}, 'beta': None}]),
    ] = None
    """
    An object to modify tags on the Actor's builds. The key is the tag name (e.g., _latest_), and the value is either an object with a `buildId` or `null`.

    This operation is a patch; any existing tags that you omit from this object will be preserved.

    - **To create or reassign a tag**, provide the tag name with a `buildId`. e.g., to assign the _latest_ tag:

      &nbsp;

      ```json
      {
        "latest": {
          "buildId": "z2EryhbfhgSyqj6Hn"
        }
      }
      ```

    - **To remove a tag**, provide the tag name with a `null` value. e.g., to remove the _beta_ tag:

      &nbsp;

      ```json
      {
        "beta": null
      }
      ```

    - **To perform multiple operations**, combine them. The following reassigns _latest_ and removes _beta_, while preserving any other existing tags.

      &nbsp;

      ```json
      {
        "latest": {
          "buildId": "z2EryhbfhgSyqj6Hn"
        },
        "beta": null
      }
      ```

    """


class UpdateActorResponse(BaseModel):
    data: Actor


class VersionList(BaseModel):
    total: Annotated[float, Field(examples=[5])]
    items: list[Version]


class GetVersionListResponse(BaseModel):
    data: VersionList


class CreateOrUpdateVersionRequest(BaseModel):
    version_number: Annotated[str | None, Field(alias='versionNumber', examples=['0.0'])] = None
    source_type: Annotated[Any | VersionSourceType | None, Field(alias='sourceType')] = None
    env_vars: Annotated[list[EnvVar] | None, Field(alias='envVars')] = None
    apply_env_vars_to_build: Annotated[bool | None, Field(alias='applyEnvVarsToBuild', examples=[False])] = None
    build_tag: Annotated[str | None, Field(alias='buildTag', examples=['latest'])] = None
    source_files: Annotated[
        list[SourceCodeFile | SourceCodeFolder] | None, Field(alias='sourceFiles', title='VersionSourceFiles')
    ] = None


class GetVersionResponse(BaseModel):
    data: Version


class EnvVarList(BaseModel):
    total: Annotated[float, Field(examples=[5])]
    items: list[EnvVar]


class GetEnvVarListResponse(BaseModel):
    data: EnvVarList


class GetEnvVarResponse(BaseModel):
    data: EnvVar


class WebhookEventType(Enum):
    """Type of event that triggers the webhook."""

    ACTOR_BUILD_ABORTED = 'ACTOR.BUILD.ABORTED'
    ACTOR_BUILD_CREATED = 'ACTOR.BUILD.CREATED'
    ACTOR_BUILD_FAILED = 'ACTOR.BUILD.FAILED'
    ACTOR_BUILD_SUCCEEDED = 'ACTOR.BUILD.SUCCEEDED'
    ACTOR_BUILD_TIMED_OUT = 'ACTOR.BUILD.TIMED_OUT'
    ACTOR_RUN_ABORTED = 'ACTOR.RUN.ABORTED'
    ACTOR_RUN_CREATED = 'ACTOR.RUN.CREATED'
    ACTOR_RUN_FAILED = 'ACTOR.RUN.FAILED'
    ACTOR_RUN_RESURRECTED = 'ACTOR.RUN.RESURRECTED'
    ACTOR_RUN_SUCCEEDED = 'ACTOR.RUN.SUCCEEDED'
    ACTOR_RUN_TIMED_OUT = 'ACTOR.RUN.TIMED_OUT'


class WebhookCondition(BaseModel):
    actor_id: Annotated[str | None, Field(alias='actorId', examples=['hksJZtadYvn4mBuin'])] = None
    actor_task_id: Annotated[str | None, Field(alias='actorTaskId', examples=['asdLZtadYvn4mBZmm'])] = None
    actor_run_id: Annotated[str | None, Field(alias='actorRunId', examples=['hgdKZtadYvn4mBpoi'])] = None


class ExampleWebhookDispatch(BaseModel):
    status: Annotated[str, Field(examples=['SUCCEEDED'])]
    finished_at: Annotated[str, Field(alias='finishedAt', examples=['2019-12-13T08:36:13.202Z'])]


class WebhookStats(BaseModel):
    total_dispatches: Annotated[float, Field(alias='totalDispatches', examples=[1])]


class WebhookShort(BaseModel):
    id: Annotated[str, Field(examples=['YiKoxjkaS9gjGTqhF'])]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-12-12T07:34:14.202Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2019-12-13T08:36:13.202Z'])]
    user_id: Annotated[str, Field(alias='userId', examples=['wRsJZtadYvn4mBZmm'])]
    is_ad_hoc: Annotated[bool | None, Field(alias='isAdHoc', examples=[False])] = None
    should_interpolate_strings: Annotated[bool | None, Field(alias='shouldInterpolateStrings', examples=[False])] = None
    event_types: Annotated[list[WebhookEventType], Field(alias='eventTypes', examples=['ACTOR.RUN.SUCCEEDED'])]
    condition: WebhookCondition
    ignore_ssl_errors: Annotated[bool, Field(alias='ignoreSslErrors', examples=[False])]
    do_not_retry: Annotated[bool, Field(alias='doNotRetry', examples=[False])]
    request_url: Annotated[str, Field(alias='requestUrl', examples=['http://example.com/'])]
    last_dispatch: Annotated[ExampleWebhookDispatch | None, Field(alias='lastDispatch')] = None
    stats: WebhookStats | None = None


class ListOfWebhooks(PaginationResponse):
    items: list[WebhookShort]


class GetListOfWebhooksResponse(BaseModel):
    data: ListOfWebhooks


class ActorJobStatus(Enum):
    """Status of an Actor job (run or build)."""

    READY = 'READY'
    RUNNING = 'RUNNING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    TIMING_OUT = 'TIMING-OUT'
    TIMED_OUT = 'TIMED-OUT'
    ABORTING = 'ABORTING'
    ABORTED = 'ABORTED'


class BuildsMeta(BaseModel):
    origin: Annotated[str, Field(examples=['WEB'])]
    client_ip: Annotated[str | None, Field(alias='clientIp', examples=['172.234.12.34'])] = None
    user_agent: Annotated[str, Field(alias='userAgent', examples=['Mozilla/5.0 (iPad)'])]


class BuildShort(BaseModel):
    id: Annotated[str, Field(examples=['HG7ML7M8z78YcAPEB'])]
    act_id: Annotated[str | None, Field(alias='actId', examples=['janedoe~my-actor'])] = None
    status: ActorJobStatus
    started_at: Annotated[str, Field(alias='startedAt', examples=['2019-11-30T07:34:24.202Z'])]
    finished_at: Annotated[str, Field(alias='finishedAt', examples=['2019-12-12T09:30:12.202Z'])]
    usage_total_usd: Annotated[float, Field(alias='usageTotalUsd', examples=[0.02])]
    meta: BuildsMeta | None = None


class BuildList(PaginationResponse):
    items: list[BuildShort]


class GetBuildListResponse(BaseModel):
    data: BuildList


class BuildStats(BaseModel):
    duration_millis: Annotated[float | None, Field(alias='durationMillis', examples=[1000])] = None
    run_time_secs: Annotated[float | None, Field(alias='runTimeSecs', examples=[45.718])] = None
    compute_units: Annotated[float, Field(alias='computeUnits', examples=[0.0126994444444444])]


class BuildOptions(BaseModel):
    use_cache: Annotated[bool | None, Field(alias='useCache', examples=[False])] = None
    beta_packages: Annotated[bool | None, Field(alias='betaPackages', examples=[False])] = None
    memory_mbytes: Annotated[float | None, Field(alias='memoryMbytes', examples=[1024])] = None
    disk_mbytes: Annotated[float | None, Field(alias='diskMbytes', examples=[2048])] = None


class BuildUsage(BaseModel):
    actor_compute_units: Annotated[float | None, Field(alias='ACTOR_COMPUTE_UNITS', examples=[0.08])] = None


class ActorSpecification(IntEnum):
    """The Actor specification version that this Actor follows. This property must be set to 1."""

    INTEGER_1 = 1


class Storages(BaseModel):
    dataset: dict[str, Any] | None = None
    """
    Defines the schema of items in your dataset, the full specification can be found in [Apify docs](https://docs.apify.com/platform/actors/development/actor-definition/dataset-schema)
    """


class ActorDefinition(BaseModel):
    """The definition of the Actor, the full specification of this field can be found in [Apify docs](https://docs.apify.com/platform/actors/development/actor-definition/actor-json)"""

    actor_specification: Annotated[ActorSpecification | None, Field(alias='actorSpecification')] = None
    """
    The Actor specification version that this Actor follows. This property must be set to 1.
    """
    name: str | None = None
    """
    The name of the Actor.
    """
    version: Annotated[str | None, Field(pattern='^[0-9]+\\\\.[0-9]+$')] = None
    """
    The version of the Actor, specified in the format [Number].[Number], e.g., 0.1, 1.0.
    """
    build_tag: Annotated[str | None, Field(alias='buildTag')] = None
    """
    The tag name to be applied to a successful build of the Actor. Defaults to 'latest' if not specified.
    """
    environment_variables: Annotated[dict[str, str] | None, Field(alias='environmentVariables')] = None
    """
    A map of environment variables to be used during local development and deployment.
    """
    dockerfile: str | None = None
    """
    The path to the Dockerfile used for building the Actor on the platform.
    """
    docker_context_dir: Annotated[str | None, Field(alias='dockerContextDir')] = None
    """
    The path to the directory used as the Docker context when building the Actor.
    """
    readme: str | None = None
    """
    The path to the README file for the Actor.
    """
    input: dict[str, Any] | None = None
    """
    The input schema object, the full specification can be found in [Apify docs](https://docs.apify.com/platform/actors/development/actor-definition/input-schema)
    """
    changelog: str | None = None
    """
    The path to the CHANGELOG file displayed in the Actor's information tab.
    """
    storages: Storages | None = None
    default_memory_mbytes: Annotated[str | int | None, Field(alias='defaultMemoryMbytes')] = None
    """
    Specifies the default amount of memory in megabytes to be used when the Actor is started. Can be an integer or a [dynamic memory expression](/platform/actors/development/actor-definition/dynamic-actor-memory).
    """
    min_memory_mbytes: Annotated[int | None, Field(alias='minMemoryMbytes', ge=256)] = None
    """
    Specifies the minimum amount of memory in megabytes required by the Actor.
    """
    max_memory_mbytes: Annotated[int | None, Field(alias='maxMemoryMbytes', ge=256)] = None
    """
    Specifies the maximum amount of memory in megabytes required by the Actor.
    """
    uses_standby_mode: Annotated[bool | None, Field(alias='usesStandbyMode')] = None
    """
    Specifies whether the Actor will have Standby mode enabled.
    """


class Build(BaseModel):
    id: Annotated[str, Field(examples=['HG7ML7M8z78YcAPEB'])]
    act_id: Annotated[str, Field(alias='actId', examples=['janedoe~my-actor'])]
    user_id: Annotated[str, Field(alias='userId', examples=['klmdEpoiojmdEMlk3'])]
    started_at: Annotated[str, Field(alias='startedAt', examples=['2019-11-30T07:34:24.202Z'])]
    finished_at: Annotated[str | None, Field(alias='finishedAt', examples=['2019-12-12T09:30:12.202Z'])] = None
    status: ActorJobStatus
    meta: BuildsMeta
    stats: BuildStats | None = None
    options: BuildOptions | None = None
    usage: BuildUsage | None = None
    usage_total_usd: Annotated[float | None, Field(alias='usageTotalUsd', examples=[0.02])] = None
    usage_usd: Annotated[BuildUsage | None, Field(alias='usageUsd')] = None
    input_schema: Annotated[
        str | None, Field(alias='inputSchema', examples=['{\\n  \\"title\\": \\"Schema for ... }'])
    ] = None
    readme: Annotated[str | None, Field(examples=['# Magic Actor\\nThis Actor is magic.'])] = None
    build_number: Annotated[str, Field(alias='buildNumber', examples=['0.1.1'])]
    actor_definition: Annotated[ActorDefinition | None, Field(alias='actorDefinition')] = None


class BuildActorResponse(BaseModel):
    data: Build


class GetBuildResponse(BaseModel):
    data: Build


class Id(BaseModel):
    type: Annotated[str | None, Field(examples=['string'])] = None


class ActId(BaseModel):
    type: Annotated[str | None, Field(examples=['string'])] = None


class UserId(BaseModel):
    type: Annotated[str | None, Field(examples=['string'])] = None


class StartedAt(BaseModel):
    type: Annotated[str | None, Field(examples=['string'])] = None
    format: Annotated[str | None, Field(examples=['date-time'])] = None
    example: Annotated[str | None, Field(examples=['2025-01-08T00:00:00.000Z'])] = None


class FinishedAt(BaseModel):
    type: Annotated[str | None, Field(examples=['string'])] = None
    format: Annotated[str | None, Field(examples=['date-time'])] = None
    example: Annotated[str | None, Field(examples=['2025-01-08T00:00:00.000Z'])] = None


class Status(BaseModel):
    type: Annotated[str | None, Field(examples=['string'])] = None
    example: Annotated[str | None, Field(examples=['READY'])] = None


class Origin(BaseModel):
    type: Annotated[str | None, Field(examples=['string'])] = None
    example: Annotated[str | None, Field(examples=['API'])] = None


class UserAgent(BaseModel):
    type: Annotated[str | None, Field(examples=['string'])] = None


class Properties1(BaseModel):
    origin: Origin | None = None
    user_agent: Annotated[UserAgent | None, Field(alias='userAgent')] = None


class Meta(BaseModel):
    type: Annotated[str | None, Field(examples=['object'])] = None
    properties: Properties1 | None = None


class Properties(BaseModel):
    id: Id | None = None
    act_id: Annotated[ActId | None, Field(alias='actId')] = None
    user_id: Annotated[UserId | None, Field(alias='userId')] = None
    started_at: Annotated[StartedAt | None, Field(alias='startedAt')] = None
    finished_at: Annotated[FinishedAt | None, Field(alias='finishedAt')] = None
    status: Status | None = None
    meta: Meta | None = None


class RunsResponseSchemaDataProperties(BaseModel):
    type: Annotated[str | None, Field(examples=['object'])] = None
    properties: Properties | None = None


class Info(BaseModel):
    title: Annotated[str | None, Field(examples=['Your Magic Actor'])] = None
    version: Annotated[str | None, Field(examples=['1.0'])] = None
    x_build_id: Annotated[str | None, Field(alias='x-build-id', examples=['ID of build'])] = None


class Server(BaseModel):
    url: Annotated[str | None, Field(examples=['https://api.apify.com/v2'])] = None


class Schema(BaseModel):
    field_ref: Annotated[str | None, Field(alias='$ref', examples=['#/components/schemas/inputSchema'])] = None


class ApplicationJson(BaseModel):
    schema_: Annotated[Schema | None, Field(alias='schema')] = None


class Content(BaseModel):
    application_json: Annotated[ApplicationJson | None, Field(alias='application/json')] = None


class RequestBody(BaseModel):
    required: Annotated[bool | None, Field(examples=[True])] = None
    content: Content | None = None


class Schema1(BaseModel):
    type: Annotated[str | None, Field(examples=['string'])] = None


class Parameter(BaseModel):
    name: Annotated[str | None, Field(examples=['token'])] = None
    in_: Annotated[str | None, Field(alias='in', examples=['query'])] = None
    required: Annotated[bool | None, Field(examples=[True])] = None
    schema_: Annotated[Schema1 | None, Field(alias='schema')] = None
    description: Annotated[str | None, Field(examples=['Enter your Apify token here'])] = None


class Field200(BaseModel):
    description: Annotated[str | None, Field(examples=['OK'])] = None


class Responses(BaseModel):
    field_200: Annotated[Field200 | None, Field(alias='200')] = None


class Post(BaseModel):
    operation_id: Annotated[str | None, Field(alias='operationId', examples=['run-sync-get-dataset-items'])] = None
    x_openai_is_consequential: Annotated[bool | None, Field(alias='x-openai-isConsequential', examples=[False])] = None
    summary: Annotated[
        str | None,
        Field(examples=["Executes an Actor, waits for its completion, and returns Actor's dataset items in response."]),
    ] = None
    tags: Annotated[list[str] | None, Field(examples=[['Run Actor']])] = None
    request_body: Annotated[RequestBody | None, Field(alias='requestBody')] = None
    parameters: list[Parameter] | None = None
    responses: Responses | None = None


class FieldActsUsernameActorRunSyncGetDatasetItems(BaseModel):
    post: Post | None = None


class Schema2(BaseModel):
    field_ref: Annotated[str | None, Field(alias='$ref', examples=['#/components/schemas/inputSchema'])] = None


class ApplicationJson1(BaseModel):
    schema_: Annotated[Schema2 | None, Field(alias='schema')] = None


class Content1(BaseModel):
    application_json: Annotated[ApplicationJson1 | None, Field(alias='application/json')] = None


class RequestBody1(BaseModel):
    required: Annotated[bool | None, Field(examples=[True])] = None
    content: Content1 | None = None


class Schema3(BaseModel):
    type: str | None = None


class Parameter1(BaseModel):
    name: str | None = None
    in_: Annotated[str | None, Field(alias='in', examples=['query'])] = None
    required: bool | None = None
    schema_: Annotated[Schema3 | None, Field(alias='schema')] = None
    description: str | None = None


class Schema4(BaseModel):
    field_ref: Annotated[str | None, Field(alias='$ref', examples=['#/components/schemas/runsResponseSchema'])] = None


class ApplicationJson2(BaseModel):
    schema_: Annotated[Schema4 | None, Field(alias='schema')] = None


class Content2(BaseModel):
    application_json: Annotated[ApplicationJson2 | None, Field(alias='application/json')] = None


class Field2001(BaseModel):
    description: Annotated[str | None, Field(examples=['OK'])] = None
    content: Content2 | None = None


class Responses1(BaseModel):
    field_200: Annotated[Field2001 | None, Field(alias='200')] = None


class Post1(BaseModel):
    operation_id: Annotated[str | None, Field(alias='operationId', examples=['runs'])] = None
    x_openai_is_consequential: Annotated[bool | None, Field(alias='x-openai-isConsequential', examples=[False])] = None
    summary: Annotated[
        str | None, Field(examples=['Executes an Actor and returns information about the initiated run in response.'])
    ] = None
    tags: Annotated[list[str] | None, Field(examples=[['Run Actor']])] = None
    request_body: Annotated[RequestBody1 | None, Field(alias='requestBody')] = None
    parameters: list[Parameter1] | None = None
    responses: Responses1 | None = None


class FieldActsUsernameActorRuns(BaseModel):
    post: Post1 | None = None


class Schema5(BaseModel):
    field_ref: Annotated[str | None, Field(alias='$ref', examples=['#/components/schemas/inputSchema'])] = None


class ApplicationJson3(BaseModel):
    schema_: Annotated[Schema5 | None, Field(alias='schema')] = None


class Content3(BaseModel):
    application_json: Annotated[ApplicationJson3 | None, Field(alias='application/json')] = None


class RequestBody2(BaseModel):
    required: Annotated[bool | None, Field(examples=[True])] = None
    content: Content3 | None = None


class Schema6(BaseModel):
    type: str | None = None


class Parameter2(BaseModel):
    name: str | None = None
    in_: Annotated[str | None, Field(alias='in', examples=['query'])] = None
    required: bool | None = None
    schema_: Annotated[Schema6 | None, Field(alias='schema')] = None
    description: str | None = None


class Field2002(BaseModel):
    description: Annotated[str | None, Field(examples=['OK'])] = None


class Responses2(BaseModel):
    field_200: Annotated[Field2002 | None, Field(alias='200')] = None


class Post2(BaseModel):
    operation_id: Annotated[str | None, Field(alias='operationId', examples=['run-sync'])] = None
    x_openai_is_consequential: Annotated[bool | None, Field(alias='x-openai-isConsequential', examples=[False])] = None
    summary: Annotated[
        str | None,
        Field(
            examples=[
                'Executes an Actor, waits for completion, and returns the OUTPUT from Key-value store in response.'
            ]
        ),
    ] = None
    tags: Annotated[list[str] | None, Field(examples=[['Run Actor']])] = None
    request_body: Annotated[RequestBody2 | None, Field(alias='requestBody')] = None
    parameters: list[Parameter2] | None = None
    responses: Responses2 | None = None


class FieldActsUsernameActorRunSync(BaseModel):
    post: Post2 | None = None


class Paths(BaseModel):
    field_acts__username___actor__run_sync_get_dataset_items: Annotated[
        FieldActsUsernameActorRunSyncGetDatasetItems | None,
        Field(alias='/acts/<username>~<actor>/run-sync-get-dataset-items'),
    ] = None
    field_acts__username___actor__runs: Annotated[
        FieldActsUsernameActorRuns | None, Field(alias='/acts/<username>~<actor>/runs')
    ] = None
    field_acts__username___actor__run_sync: Annotated[
        FieldActsUsernameActorRunSync | None, Field(alias='/acts/<username>~<actor>/run-sync')
    ] = None


class InputSchema(BaseModel):
    type: Annotated[str | None, Field(examples=['object'])] = None


class Properties2(BaseModel):
    data: RunsResponseSchemaDataProperties | None = None


class RunsResponseSchema(BaseModel):
    type: Annotated[str | None, Field(examples=['object'])] = None
    properties: Properties2 | None = None


class Schemas(BaseModel):
    input_schema: Annotated[InputSchema | None, Field(alias='inputSchema')] = None
    runs_response_schema: Annotated[RunsResponseSchema | None, Field(alias='runsResponseSchema')] = None


class Components(BaseModel):
    schemas: Schemas | None = None


class GetOpenApiResponse(BaseModel):
    openapi: Annotated[str | None, Field(examples=['3.0.1'])] = None
    info: Info | None = None
    servers: list[Server] | None = None
    paths: Paths | None = None
    components: Components | None = None


class PostAbortBuildResponse(BaseModel):
    data: Build


class RunOrigin(Enum):
    DEVELOPMENT = 'DEVELOPMENT'
    WEB = 'WEB'
    API = 'API'
    SCHEDULER = 'SCHEDULER'
    TEST = 'TEST'
    WEBHOOK = 'WEBHOOK'
    ACTOR = 'ACTOR'
    CLI = 'CLI'
    STANDBY = 'STANDBY'


class RunMeta(BaseModel):
    origin: RunOrigin


class RunShort(BaseModel):
    id: Annotated[str, Field(examples=['HG7ML7M8z78YcAPEB'])]
    act_id: Annotated[str, Field(alias='actId', examples=['HDSasDasz78YcAPEB'])]
    actor_task_id: Annotated[str | None, Field(alias='actorTaskId', examples=['KJHSKHausidyaJKHs'])] = None
    status: ActorJobStatus
    started_at: Annotated[str, Field(alias='startedAt', examples=['2019-11-30T07:34:24.202Z'])]
    finished_at: Annotated[str, Field(alias='finishedAt', examples=['2019-12-12T09:30:12.202Z'])]
    build_id: Annotated[str, Field(alias='buildId', examples=['HG7ML7M8z78YcAPEB'])]
    build_number: Annotated[str | None, Field(alias='buildNumber', examples=['0.0.2'])] = None
    meta: RunMeta
    usage_total_usd: Annotated[float, Field(alias='usageTotalUsd', examples=[0.2])]
    default_key_value_store_id: Annotated[str, Field(alias='defaultKeyValueStoreId', examples=['sfAjeR4QmeJCQzTfe'])]
    default_dataset_id: Annotated[str, Field(alias='defaultDatasetId', examples=['3ZojQDdFTsyE7Moy4'])]
    default_request_queue_id: Annotated[str, Field(alias='defaultRequestQueueId', examples=['so93g2shcDzK3pA85'])]


class RunList(PaginationResponse):
    items: list[RunShort]


class GetUserRunsListResponse(BaseModel):
    data: RunList


class RunStats(BaseModel):
    input_body_len: Annotated[float | None, Field(alias='inputBodyLen', examples=[240])] = None
    migration_count: Annotated[float | None, Field(alias='migrationCount', examples=[0])] = None
    reboot_count: Annotated[float | None, Field(alias='rebootCount', examples=[0])] = None
    restart_count: Annotated[float, Field(alias='restartCount', examples=[0])]
    resurrect_count: Annotated[float, Field(alias='resurrectCount', examples=[2])]
    mem_avg_bytes: Annotated[float | None, Field(alias='memAvgBytes', examples=[267874071.9])] = None
    mem_max_bytes: Annotated[float | None, Field(alias='memMaxBytes', examples=[404713472])] = None
    mem_current_bytes: Annotated[float | None, Field(alias='memCurrentBytes', examples=[0])] = None
    cpu_avg_usage: Annotated[float | None, Field(alias='cpuAvgUsage', examples=[33.7532101107538])] = None
    cpu_max_usage: Annotated[float | None, Field(alias='cpuMaxUsage', examples=[169.650735534941])] = None
    cpu_current_usage: Annotated[float | None, Field(alias='cpuCurrentUsage', examples=[0])] = None
    net_rx_bytes: Annotated[float | None, Field(alias='netRxBytes', examples=[103508042])] = None
    net_tx_bytes: Annotated[float | None, Field(alias='netTxBytes', examples=[4854600])] = None
    duration_millis: Annotated[float | None, Field(alias='durationMillis', examples=[248472])] = None
    run_time_secs: Annotated[float | None, Field(alias='runTimeSecs', examples=[248.472])] = None
    metamorph: Annotated[float | None, Field(examples=[0])] = None
    compute_units: Annotated[float, Field(alias='computeUnits', examples=[0.13804])]


class RunOptions(BaseModel):
    build: Annotated[str, Field(examples=['latest'])]
    timeout_secs: Annotated[float, Field(alias='timeoutSecs', examples=[300])]
    memory_mbytes: Annotated[float, Field(alias='memoryMbytes', examples=[1024])]
    disk_mbytes: Annotated[float, Field(alias='diskMbytes', examples=[2048])]
    max_items: Annotated[float | None, Field(alias='maxItems', examples=[1000])] = None
    max_total_charge_usd: Annotated[float | None, Field(alias='maxTotalChargeUsd', examples=[5])] = None


class GeneralAccessEnum(Enum):
    """Defines the general access level for the resource."""

    RESTRICTED = 'RESTRICTED'
    ANYONE_WITH_ID_CAN_READ = 'ANYONE_WITH_ID_CAN_READ'
    FOLLOW_USER_SETTING = 'FOLLOW_USER_SETTING'


class RunUsage(BaseModel):
    actor_compute_units: Annotated[float | None, Field(alias='ACTOR_COMPUTE_UNITS', examples=[3])] = None
    dataset_reads: Annotated[float | None, Field(alias='DATASET_READS', examples=[4])] = None
    dataset_writes: Annotated[float | None, Field(alias='DATASET_WRITES', examples=[4])] = None
    key_value_store_reads: Annotated[float | None, Field(alias='KEY_VALUE_STORE_READS', examples=[5])] = None
    key_value_store_writes: Annotated[float | None, Field(alias='KEY_VALUE_STORE_WRITES', examples=[3])] = None
    key_value_store_lists: Annotated[float | None, Field(alias='KEY_VALUE_STORE_LISTS', examples=[5])] = None
    request_queue_reads: Annotated[float | None, Field(alias='REQUEST_QUEUE_READS', examples=[2])] = None
    request_queue_writes: Annotated[float | None, Field(alias='REQUEST_QUEUE_WRITES', examples=[1])] = None
    data_transfer_internal_gbytes: Annotated[
        float | None, Field(alias='DATA_TRANSFER_INTERNAL_GBYTES', examples=[1])
    ] = None
    data_transfer_external_gbytes_: Annotated[
        float | None, Field(alias='DATA_TRANSFER_EXTERNAL_GBYTES?', examples=[3])
    ] = None
    proxy_residential_transfer_gbytes: Annotated[
        float | None, Field(alias='PROXY_RESIDENTIAL_TRANSFER_GBYTES', examples=[34])
    ] = None
    proxy_serps: Annotated[float | None, Field(alias='PROXY_SERPS', examples=[3])] = None


class Run(BaseModel):
    id: Annotated[str, Field(examples=['HG7ML7M8z78YcAPEB'])]
    act_id: Annotated[str, Field(alias='actId', examples=['HDSasDasz78YcAPEB'])]
    user_id: Annotated[str, Field(alias='userId', examples=['7sT5jcggjjA9fNcxF'])]
    actor_task_id: Annotated[str | None, Field(alias='actorTaskId', examples=['KJHSKHausidyaJKHs'])] = None
    started_at: Annotated[str, Field(alias='startedAt', examples=['2019-11-30T07:34:24.202Z'])]
    finished_at: Annotated[str | None, Field(alias='finishedAt', examples=['2019-12-12T09:30:12.202Z'])] = None
    status: ActorJobStatus
    status_message: Annotated[str | None, Field(alias='statusMessage', examples=['Actor is running'])] = None
    is_status_message_terminal: Annotated[bool | None, Field(alias='isStatusMessageTerminal', examples=[False])] = None
    meta: RunMeta
    pricing_info: Annotated[
        PayPerEventActorPricingInfo
        | PricePerDatasetItemActorPricingInfo
        | FlatPricePerMonthActorPricingInfo
        | FreeActorPricingInfo
        | None,
        Field(alias='pricingInfo', discriminator='pricing_model', title='ActorRunPricingInfo'),
    ] = None
    stats: RunStats
    charged_event_counts: Annotated[dict[str, int] | None, Field(alias='chargedEventCounts')] = None
    options: RunOptions
    build_id: Annotated[str, Field(alias='buildId', examples=['7sT5jcggjjA9fNcxF'])]
    exit_code: Annotated[float | None, Field(alias='exitCode', examples=[0])] = None
    general_access: Annotated[GeneralAccessEnum, Field(alias='generalAccess')]
    default_key_value_store_id: Annotated[str, Field(alias='defaultKeyValueStoreId', examples=['eJNzqsbPiopwJcgGQ'])]
    default_dataset_id: Annotated[str, Field(alias='defaultDatasetId', examples=['wmKPijuyDnPZAPRMk'])]
    default_request_queue_id: Annotated[str, Field(alias='defaultRequestQueueId', examples=['FL35cSF7jrxr3BY39'])]
    build_number: Annotated[str | None, Field(alias='buildNumber', examples=['0.0.36'])] = None
    container_url: Annotated[
        str | None, Field(alias='containerUrl', examples=['https://g8kd8kbc5ge8.runs.apify.net'])
    ] = None
    is_container_server_ready: Annotated[bool | None, Field(alias='isContainerServerReady', examples=[True])] = None
    git_branch_name: Annotated[str | None, Field(alias='gitBranchName', examples=['master'])] = None
    usage: RunUsage | None = None
    usage_total_usd: Annotated[float | None, Field(alias='usageTotalUsd', examples=[0.2654])] = None
    usage_usd: Annotated[RunUsage | None, Field(alias='usageUsd')] = None


class RunResponse(BaseModel):
    data: Run


class Error(BaseModel):
    type: Annotated[str, Field(examples=['run-failed'])]
    message: Annotated[str, Field(examples=['Actor run did not succeed (run ID: 55uatRrZib4xbZs, status: FAILED)'])]


class ErrorResponse(BaseModel):
    error: Error


class TaskStats(BaseModel):
    total_runs: Annotated[float, Field(alias='totalRuns', examples=[15])]


class TaskShort(BaseModel):
    id: Annotated[str, Field(examples=['zdc3Pyhyz3m8vjDeM'])]
    user_id: Annotated[str, Field(alias='userId', examples=['wRsJZtadYvn4mBZmm'])]
    act_id: Annotated[str, Field(alias='actId', examples=['asADASadYvn4mBZmm'])]
    act_name: Annotated[str, Field(alias='actName', examples=['my-actor'])]
    name: Annotated[str, Field(examples=['my-task'])]
    username: Annotated[str | None, Field(examples=['janedoe'])] = None
    act_username: Annotated[str, Field(alias='actUsername', examples=['janedoe'])]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2018-10-26T07:23:14.855Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2018-10-26T13:30:49.578Z'])]
    stats: TaskStats | None = None


class TaskOptions(BaseModel):
    build: Annotated[str | None, Field(examples=['latest'])] = None
    timeout_secs: Annotated[float | None, Field(alias='timeoutSecs', examples=[300])] = None
    memory_mbytes: Annotated[float | None, Field(alias='memoryMbytes', examples=[128])] = None
    restart_on_error: Annotated[bool | None, Field(alias='restartOnError', examples=[False])] = None


class TaskInput(BaseModel):
    hello: Annotated[str | None, Field(examples=['world'])] = None


class CreateTaskRequest(BaseModel):
    act_id: Annotated[str, Field(alias='actId', examples=['asADASadYvn4mBZmm'])]
    name: Annotated[str, Field(examples=['my-task'])]
    options: TaskOptions | None = None
    input: TaskInput | None = None


class Task(BaseModel):
    id: Annotated[str, Field(examples=['zdc3Pyhyz3m8vjDeM'])]
    user_id: Annotated[str, Field(alias='userId', examples=['wRsJZtadYvn4mBZmm'])]
    act_id: Annotated[str, Field(alias='actId', examples=['asADASadYvn4mBZmm'])]
    name: Annotated[str, Field(examples=['my-task'])]
    username: Annotated[str | None, Field(examples=['janedoe'])] = None
    created_at: Annotated[str, Field(alias='createdAt', examples=['2018-10-26T07:23:14.855Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2018-10-26T13:30:49.578Z'])]
    removed_at: Annotated[str | None, Field(alias='removedAt')] = None
    stats: TaskStats | None = None
    options: TaskOptions | None = None
    input: TaskInput | None = None


class CreateTaskResponse(BaseModel):
    data: Task
    standby_url: Annotated[str | None, Field(alias='standbyUrl')] = None


class UpdateTaskRequest(BaseModel):
    id: Annotated[str, Field(examples=['ZxLNxrRaZrSjuhT9y'])]
    user_id: Annotated[str, Field(alias='userId', examples=['BPWZBd7Z9c746JAnF'])]
    act_id: Annotated[str, Field(alias='actId', examples=['asADASadYvn4mBZmm'])]
    name: Annotated[str, Field(examples=['my-task'])]
    username: Annotated[str | None, Field(examples=['janedoe'])] = None
    created_at: Annotated[str, Field(alias='createdAt', examples=['2018-10-26T07:23:14.855Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2018-10-26T13:30:49.578Z'])]
    removed_at: Annotated[str | None, Field(alias='removedAt')] = None
    stats: TaskStats | None = None
    options: TaskOptions | None = None
    input: TaskInput | None = None


class Webhook(BaseModel):
    id: Annotated[str, Field(examples=['YiKoxjkaS9gjGTqhF'])]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-12-12T07:34:14.202Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2019-12-13T08:36:13.202Z'])]
    user_id: Annotated[str, Field(alias='userId', examples=['wRsJZtadYvn4mBZmm'])]
    is_ad_hoc: Annotated[bool | None, Field(alias='isAdHoc', examples=[False])] = None
    should_interpolate_strings: Annotated[bool | None, Field(alias='shouldInterpolateStrings', examples=[False])] = None
    event_types: Annotated[list[WebhookEventType], Field(alias='eventTypes', examples=['ACTOR.RUN.SUCCEEDED'])]
    condition: WebhookCondition
    ignore_ssl_errors: Annotated[bool, Field(alias='ignoreSslErrors', examples=[False])]
    do_not_retry: Annotated[bool | None, Field(alias='doNotRetry', examples=[False])] = None
    request_url: Annotated[str, Field(alias='requestUrl', examples=['http://example.com/'])]
    payload_template: Annotated[
        str | None, Field(alias='payloadTemplate', examples=['{\\n \\"userId\\": {{userId}}...'])
    ] = None
    headers_template: Annotated[
        str | None, Field(alias='headersTemplate', examples=['{\\n \\"Authorization\\": Bearer...'])
    ] = None
    description: Annotated[str | None, Field(examples=['this is webhook description'])] = None
    last_dispatch: Annotated[ExampleWebhookDispatch | None, Field(alias='lastDispatch')] = None
    stats: WebhookStats | None = None


class UpdateRunRequest(BaseModel):
    run_id: Annotated[str | None, Field(alias='runId', examples=['3KH8gEpp4d8uQSe8T'])] = None
    status_message: Annotated[str | None, Field(alias='statusMessage', examples=['Actor has finished'])] = None
    is_status_message_terminal: Annotated[bool | None, Field(alias='isStatusMessageTerminal', examples=[True])] = None
    general_access: Annotated[GeneralAccessEnum | None, Field(alias='generalAccess')] = None


class ChargeRunRequest(BaseModel):
    event_name: Annotated[str, Field(alias='eventName', examples=['ANALYZE_PAGE'])]
    count: Annotated[float, Field(examples=[1])]


class KeyValueStoreStats(BaseModel):
    read_count: Annotated[float, Field(alias='readCount', examples=[9])]
    write_count: Annotated[float, Field(alias='writeCount', examples=[3])]
    delete_count: Annotated[float, Field(alias='deleteCount', examples=[6])]
    list_count: Annotated[float, Field(alias='listCount', examples=[2])]
    s3_storage_bytes: Annotated[float | None, Field(alias='s3StorageBytes', examples=[18])] = None


class KeyValueStore(BaseModel):
    id: Annotated[str, Field(examples=['WkzbQMuFYuamGv3YF'])]
    name: Annotated[str | None, Field(examples=['d7b9MDYsbtX5L7XAj'])] = None
    user_id: Annotated[str | None, Field(alias='userId', examples=['BPWDBd7Z9c746JAnF'])] = None
    username: Annotated[str | None, Field(examples=['janedoe'])] = None
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-12-12T07:34:14.202Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2019-12-13T08:36:13.202Z'])]
    accessed_at: Annotated[str, Field(alias='accessedAt', examples=['2019-12-14T08:36:13.202Z'])]
    act_id: Annotated[str | None, Field(alias='actId', examples=[None])] = None
    act_run_id: Annotated[str | None, Field(alias='actRunId', examples=[None])] = None
    console_url: Annotated[
        str,
        Field(alias='consoleUrl', examples=['https://console.apify.com/storage/key-value-stores/27TmTznX9YPeAYhkC']),
    ]
    keys_public_url: Annotated[
        str,
        Field(
            alias='keysPublicUrl',
            examples=['https://api.apify.com/v2/key-value-stores/WkzbQMuFYuamGv3YF/keys?signature=abc123'],
        ),
    ]
    """
    A public link to access keys of the key-value store directly.
    """
    url_signing_secret_key: Annotated[str | None, Field(alias='urlSigningSecretKey')] = None
    """
    A secret key for generating signed public URLs. It is only provided to clients with WRITE permission for the key-value store.
    """
    general_access: Annotated[GeneralAccessEnum | None, Field(alias='generalAccess')] = None
    stats: KeyValueStoreStats | None = None


class ListOfKeyValueStores(PaginationResponse):
    items: list[KeyValueStore]


class GetListOfKeyValueStoresResponse(BaseModel):
    data: ListOfKeyValueStores


class CreateKeyValueStoreResponse(BaseModel):
    data: KeyValueStore


class GetStoreResponse(BaseModel):
    data: KeyValueStore


class UpdateStoreRequest(BaseModel):
    name: str | None = None
    general_access: Annotated[GeneralAccessEnum | None, Field(alias='generalAccess')] = None


class UpdateStoreResponse(BaseModel):
    data: KeyValueStore


class KeyValueStoreKey(BaseModel):
    key: Annotated[str, Field(examples=['second-key'])]
    size: Annotated[float, Field(examples=[36])]
    record_public_url: Annotated[
        str,
        Field(
            alias='recordPublicUrl',
            examples=['https://api.apify.com/v2/key-value-stores/WkzbQMuFYuamGv3YF/records/some-key?signature=abc123'],
        ),
    ]
    """
    A public link to access this record directly.
    """


class ListOfKeys(BaseModel):
    items: list[KeyValueStoreKey]
    count: Annotated[float, Field(examples=[2])]
    limit: Annotated[float, Field(examples=[2])]
    exclusive_start_key: Annotated[str | None, Field(alias='exclusiveStartKey', examples=['some-key'])] = None
    is_truncated: Annotated[bool, Field(alias='isTruncated', examples=[True])]
    next_exclusive_start_key: Annotated[str | None, Field(alias='nextExclusiveStartKey', examples=['third-key'])] = None


class GetListOfKeysResponse(BaseModel):
    data: ListOfKeys


class GetRecordResponse(BaseModel):
    foo: str


class PutRecordRequest(BaseModel):
    foo: Annotated[str | None, Field(examples=['bar'])] = None


class DatasetListItem(BaseModel):
    id: Annotated[str, Field(examples=['WkzbQMuFYuamGv3YF'])]
    name: Annotated[str, Field(examples=['d7b9MDYsbtX5L7XAj'])]
    user_id: Annotated[str, Field(alias='userId', examples=['tbXmWu7GCxnyYtSiL'])]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-12-12T07:34:14.202Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2019-12-13T08:36:13.202Z'])]
    accessed_at: Annotated[str, Field(alias='accessedAt', examples=['2019-12-14T08:36:13.202Z'])]
    item_count: Annotated[float, Field(alias='itemCount', examples=[7])]
    clean_item_count: Annotated[float, Field(alias='cleanItemCount', examples=[5])]
    act_id: Annotated[str | None, Field(alias='actId')] = None
    act_run_id: Annotated[str | None, Field(alias='actRunId')] = None


class ListOfDatasets(PaginationResponse):
    items: list[DatasetListItem]


class GetListOfDatasetsResponse(BaseModel):
    data: ListOfDatasets


class DatasetStats(BaseModel):
    read_count: Annotated[float, Field(alias='readCount', examples=[22])]
    write_count: Annotated[float, Field(alias='writeCount', examples=[3])]
    storage_bytes: Annotated[float, Field(alias='storageBytes', examples=[783])]


class Dataset(BaseModel):
    id: Annotated[str, Field(examples=['WkzbQMuFYuamGv3YF'])]
    name: Annotated[str | None, Field(examples=['d7b9MDYsbtX5L7XAj'])] = None
    user_id: Annotated[str, Field(alias='userId', examples=['wRsJZtadYvn4mBZmm'])]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-12-12T07:34:14.202Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2019-12-13T08:36:13.202Z'])]
    accessed_at: Annotated[str, Field(alias='accessedAt', examples=['2019-12-14T08:36:13.202Z'])]
    item_count: Annotated[float, Field(alias='itemCount', examples=[7])]
    clean_item_count: Annotated[float, Field(alias='cleanItemCount', examples=[5])]
    act_id: Annotated[str | None, Field(alias='actId')] = None
    act_run_id: Annotated[str | None, Field(alias='actRunId')] = None
    fields: list[str] | None = None
    schema_: Annotated[
        dict[str, Any] | None,
        Field(
            alias='schema',
            examples=[
                {
                    'actorSpecification': 1,
                    'title': 'My dataset',
                    'views': {
                        'overview': {
                            'title': 'Overview',
                            'transformation': {'fields': ['linkUrl']},
                            'display': {
                                'component': 'table',
                                'properties': {'linkUrl': {'label': 'Link URL', 'format': 'link'}},
                            },
                        }
                    },
                }
            ],
        ),
    ] = None
    """
    Defines the schema of items in your dataset, the full specification can be found in [Apify docs](/platform/actors/development/actor-definition/dataset-schema)
    """
    console_url: Annotated[
        str, Field(alias='consoleUrl', examples=['https://console.apify.com/storage/datasets/27TmTznX9YPeAYhkC'])
    ]
    items_public_url: Annotated[
        str | None,
        Field(
            alias='itemsPublicUrl',
            examples=['https://api.apify.com/v2/datasets/WkzbQMuFYuamGv3YF/items?signature=abc123'],
        ),
    ] = None
    """
    A public link to access the dataset items directly.
    """
    url_signing_secret_key: Annotated[str | None, Field(alias='urlSigningSecretKey')] = None
    """
    A secret key for generating signed public URLs. It is only provided to clients with WRITE permission for the dataset.
    """
    general_access: Annotated[GeneralAccessEnum | None, Field(alias='generalAccess')] = None
    stats: DatasetStats | None = None


class DatasetResponse(BaseModel):
    data: Dataset


class UpdateDatasetRequest(BaseModel):
    name: str | None = None
    general_access: Annotated[GeneralAccessEnum | None, Field(alias='generalAccess')] = None


class PutItemsRequest(BaseModel):
    foo: str


class ValidationError(BaseModel):
    instance_path: Annotated[str | None, Field(alias='instancePath')] = None
    """
    The path to the instance being validated.
    """
    schema_path: Annotated[str | None, Field(alias='schemaPath')] = None
    """
    The path to the schema that failed the validation.
    """
    keyword: str | None = None
    """
    The validation keyword that caused the error.
    """
    message: str | None = None
    """
    A message describing the validation error.
    """
    params: dict[str, Any] | None = None
    """
    Additional parameters specific to the validation error.
    """


class InvalidItem(BaseModel):
    item_position: Annotated[float | None, Field(alias='itemPosition', examples=[2])] = None
    """
    The position of the invalid item in the array.
    """
    validation_errors: Annotated[list[ValidationError] | None, Field(alias='validationErrors')] = None
    """
    A complete list of AJV validation error objects for the invalid item.
    """


class SchemaValidationErrorData(BaseModel):
    invalid_items: Annotated[list[InvalidItem], Field(alias='invalidItems')]
    """
    A list of invalid items in the received array of items.
    """


class DatasetSchemaValidationErrorDetails(BaseModel):
    type: Annotated[str, Field(examples=['schema-validation-error'])]
    """
    The type of the error.
    """
    message: Annotated[str, Field(examples=['Schema validation failed'])]
    """
    A human-readable message describing the error.
    """
    data: SchemaValidationErrorData


class DatasetSchemaValidationError(BaseModel):
    error: DatasetSchemaValidationErrorDetails | None = None


class PutItemResponseError(BaseModel):
    error: DatasetSchemaValidationError


class DatasetFieldStatistics(BaseModel):
    min: float | None = None
    """
    Minimum value of the field. For numbers, this is calculated directly. For strings, this is the length of the shortest string. For arrays, this is the length of the shortest array. For objects, this is the number of keys in the smallest object.
    """
    max: float | None = None
    """
    Maximum value of the field. For numbers, this is calculated directly. For strings, this is the length of the longest string. For arrays, this is the length of the longest array. For objects, this is the number of keys in the largest object.
    """
    null_count: Annotated[float | None, Field(alias='nullCount')] = None
    """
    How many items in the dataset have a null value for this field.
    """
    empty_count: Annotated[float | None, Field(alias='emptyCount')] = None
    """
    How many items in the dataset are `undefined`, meaning that for example empty string is not considered empty.
    """


class DatasetStatistics(BaseModel):
    field_statistics: Annotated[dict[str, DatasetFieldStatistics] | None, Field(alias='fieldStatistics')] = None
    """
    When you configure the dataset [fields schema](https://docs.apify.com/platform/actors/development/actor-definition/dataset-schema/validation), we measure the statistics such as `min`, `max`, `nullCount` and `emptyCount` for each field. This property provides statistics for each field from dataset fields schema. <br/></br>See dataset field statistics [documentation](https://docs.apify.com/platform/actors/development/actor-definition/dataset-schema/validation#dataset-field-statistics) for more information.
    """


class GetDatasetStatisticsResponse(BaseModel):
    data: DatasetStatistics


class RequestQueueShort(BaseModel):
    id: Annotated[str, Field(examples=['WkzbQMuFYuamGv3YF'])]
    name: Annotated[str, Field(examples=['some-name'])]
    user_id: Annotated[str, Field(alias='userId', examples=['wRsJZtadYvn4mBZmm'])]
    username: Annotated[str, Field(examples=['janedoe'])]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-12-12T07:34:14.202Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2019-12-13T08:36:13.202Z'])]
    accessed_at: Annotated[str, Field(alias='accessedAt', examples=['2019-12-14T08:36:13.202Z'])]
    expire_at: Annotated[str, Field(alias='expireAt', examples=['2019-06-02T17:15:06.751Z'])]
    total_request_count: Annotated[float, Field(alias='totalRequestCount', examples=[100])]
    handled_request_count: Annotated[float, Field(alias='handledRequestCount', examples=[50])]
    pending_request_count: Annotated[float, Field(alias='pendingRequestCount', examples=[50])]
    act_id: Annotated[str | None, Field(alias='actId')] = None
    act_run_id: Annotated[str | None, Field(alias='actRunId')] = None
    had_multiple_clients: Annotated[bool, Field(alias='hadMultipleClients', examples=[True])]


class ListOfRequestQueues(PaginationResponse):
    items: list[RequestQueueShort]


class GetListOfRequestQueuesResponse(BaseModel):
    data: ListOfRequestQueues


class RequestQueueStats(BaseModel):
    delete_count: Annotated[float | None, Field(alias='deleteCount', examples=[0])] = None
    head_item_read_count: Annotated[float | None, Field(alias='headItemReadCount', examples=[5])] = None
    read_count: Annotated[float | None, Field(alias='readCount', examples=[100])] = None
    storage_bytes: Annotated[float | None, Field(alias='storageBytes', examples=[1024])] = None
    write_count: Annotated[float | None, Field(alias='writeCount', examples=[10])] = None


class RequestQueue(BaseModel):
    id: Annotated[str, Field(examples=['WkzbQMuFYuamGv3YF'])]
    name: Annotated[str | None, Field(examples=['some-name'])] = None
    user_id: Annotated[str, Field(alias='userId', examples=['wRsJZtadYvn4mBZmm'])]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-12-12T07:34:14.202Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2030-12-13T08:36:13.202Z'])]
    """
    The modifiedAt is updated whenever the queue is modified. Modifications include adding, updating, or removing requests, as well as locking or unlocking requests in the queue.
    """
    accessed_at: Annotated[str, Field(alias='accessedAt', examples=['2019-12-14T08:36:13.202Z'])]
    total_request_count: Annotated[float, Field(alias='totalRequestCount', examples=[870])]
    handled_request_count: Annotated[float, Field(alias='handledRequestCount', examples=[100])]
    pending_request_count: Annotated[float, Field(alias='pendingRequestCount', examples=[670])]
    had_multiple_clients: Annotated[bool, Field(alias='hadMultipleClients', examples=[True])]
    console_url: Annotated[
        str, Field(alias='consoleUrl', examples=['https://api.apify.com/v2/request-queues/27TmTznX9YPeAYhkC'])
    ]
    stats: RequestQueueStats | None = None
    general_access: Annotated[GeneralAccessEnum | None, Field(alias='generalAccess')] = None


class CreateRequestQueueResponse(BaseModel):
    data: RequestQueue


class GetRequestQueueResponse(BaseModel):
    data: RequestQueue


class UpdateRequestQueueRequest(BaseModel):
    name: str | None = None
    general_access: Annotated[GeneralAccessEnum | None, Field(alias='generalAccess')] = None


class UpdateRequestQueueResponse(BaseModel):
    data: RequestQueue


class RequestWithoutId(BaseModel):
    unique_key: Annotated[str, Field(alias='uniqueKey', examples=['http://example.com'])]
    url: Annotated[str, Field(examples=['http://example.com'])]
    method: Annotated[str, Field(examples=['GET'])]


class ProcessedRequest(BaseModel):
    request_id: Annotated[str | None, Field(alias='requestId', examples=['sbJ7klsdf7ujN9l'])] = None
    unique_key: Annotated[str, Field(alias='uniqueKey', examples=['http://example.com'])]
    was_already_present: Annotated[bool | None, Field(alias='wasAlreadyPresent', examples=[False])] = None
    was_already_handled: Annotated[bool | None, Field(alias='wasAlreadyHandled', examples=[False])] = None


class UnprocessedRequest(BaseModel):
    unique_key: Annotated[str, Field(alias='uniqueKey', examples=['http://example.com'])]
    url: Annotated[str, Field(examples=['http://example.com'])]
    method: Annotated[str, Field(examples=['GET'])]


class BatchOperationResult(BaseModel):
    processed_requests: Annotated[list[ProcessedRequest], Field(alias='processedRequests')]
    unprocessed_requests: Annotated[list[UnprocessedRequest], Field(alias='unprocessedRequests')]


class BatchOperationResponse(BaseModel):
    data: BatchOperationResult


class UserData(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    label: Annotated[str | None, Field(examples=['DETAIL'])] = None
    image: Annotated[str | None, Field(examples=['https://picserver1.eu'])] = None


class RequestQueueItems(BaseModel):
    id: Annotated[str, Field(examples=['dnjkDMKLmdlkmlkmld'])]
    retry_count: Annotated[float | None, Field(alias='retryCount', examples=[0])] = None
    unique_key: Annotated[str, Field(alias='uniqueKey', examples=['http://example.com'])]
    url: Annotated[str, Field(examples=['http://example.com'])]
    method: Annotated[str | None, Field(examples=['GET'])] = None
    loaded_url: Annotated[str | None, Field(alias='loadedUrl', examples=['http://example.com/example-1'])] = None
    payload: dict[str, Any] | None = None
    no_retry: Annotated[bool | None, Field(alias='noRetry', examples=[False])] = None
    error_messages: Annotated[list[str] | None, Field(alias='errorMessages')] = None
    headers: dict[str, Any] | None = None
    user_data: Annotated[UserData | None, Field(alias='userData')] = None
    handled_at: Annotated[str | None, Field(alias='handledAt', examples=['2019-06-16T10:23:31.607Z'])] = None


class ListOfRequests(BaseModel):
    items: list[RequestQueueItems]
    count: Annotated[float | None, Field(examples=[2])] = None
    limit: Annotated[float, Field(examples=[2])]
    exclusive_start_id: Annotated[str | None, Field(alias='exclusiveStartId', examples=['Ihnsp8YrvJ8102Kj'])] = None


class ListRequestsResponse(BaseModel):
    data: ListOfRequests


class RequestOperationInfo(BaseModel):
    request_id: Annotated[str, Field(alias='requestId', examples=['YiKoxjkaS9gjGTqhF'])]
    was_already_present: Annotated[bool, Field(alias='wasAlreadyPresent', examples=[True])]
    was_already_handled: Annotated[bool, Field(alias='wasAlreadyHandled', examples=[False])]


class AddRequestResponse(BaseModel):
    data: RequestOperationInfo


class GetRequestResponse(BaseModel):
    data: RequestQueueItems


class UpdateRequestResponse(BaseModel):
    data: RequestOperationInfo


class QueueHeadItem(BaseModel):
    id: Annotated[str, Field(examples=['8OamqXBCpPHxyH9'])]
    retry_count: Annotated[float | None, Field(alias='retryCount', examples=[0])] = None
    unique_key: Annotated[str, Field(alias='uniqueKey', examples=['http://example.com'])]
    url: Annotated[str, Field(examples=['http://example.com'])]
    method: Annotated[str | None, Field(examples=['GET'])] = None


class QueueHead(BaseModel):
    limit: Annotated[float, Field(examples=[1000])]
    queue_modified_at: Annotated[str, Field(alias='queueModifiedAt', examples=['2018-03-14T23:00:00.000Z'])]
    had_multiple_clients: Annotated[bool, Field(alias='hadMultipleClients', examples=[False])]
    items: list[QueueHeadItem]


class GetHeadResponse(BaseModel):
    data: QueueHead


class LockedQueueHeadItem(BaseModel):
    id: Annotated[str, Field(examples=['8OamqXBCpPHxyj9'])]
    retry_count: Annotated[float | None, Field(alias='retryCount', examples=[0])] = None
    unique_key: Annotated[str, Field(alias='uniqueKey', examples=['http://example.com'])]
    url: Annotated[str, Field(examples=['http://example.com'])]
    method: Annotated[str | None, Field(examples=['GET'])] = None
    lock_expires_at: Annotated[str, Field(alias='lockExpiresAt', examples=['2022-06-14T23:00:00.000Z'])]


class LockedQueueHead(BaseModel):
    limit: Annotated[float, Field(examples=[1000])]
    queue_modified_at: Annotated[str, Field(alias='queueModifiedAt', examples=['2018-03-14T23:00:00.000Z'])]
    """
    The modifiedAt is updated whenever the queue is modified. Modifications include adding, updating, or removing requests, as well as locking or unlocking requests in the queue.
    """
    queue_has_locked_requests: Annotated[bool | None, Field(alias='queueHasLockedRequests', examples=[True])] = None
    """
    Whether the queue contains requests locked by any client (either the one calling the endpoint or a different one).
    """
    client_key: Annotated[str | None, Field(alias='clientKey', examples=['client-one'])] = None
    had_multiple_clients: Annotated[bool, Field(alias='hadMultipleClients', examples=[True])]
    lock_secs: Annotated[float, Field(alias='lockSecs', examples=[60])]
    items: list[LockedQueueHeadItem]


class GetHeadAndLockResponse(BaseModel):
    data: LockedQueueHead


class RequestLockInfo(BaseModel):
    lock_expires_at: Annotated[str, Field(alias='lockExpiresAt', examples=['2022-01-01T00:00:00.000Z'])]
    """
    Date when lock expires.
    """


class ProlongRequestLockResponse(BaseModel):
    data: RequestLockInfo | None = None


class WebhookCreate(BaseModel):
    is_ad_hoc: Annotated[bool | None, Field(alias='isAdHoc', examples=[False])] = None
    event_types: Annotated[list[WebhookEventType], Field(alias='eventTypes', examples=['ACTOR.RUN.SUCCEEDED'])]
    condition: WebhookCondition
    idempotency_key: Annotated[str | None, Field(alias='idempotencyKey', examples=['fdSJmdP3nfs7sfk3y'])] = None
    ignore_ssl_errors: Annotated[bool | None, Field(alias='ignoreSslErrors', examples=[False])] = None
    do_not_retry: Annotated[bool | None, Field(alias='doNotRetry', examples=[False])] = None
    request_url: Annotated[str, Field(alias='requestUrl', examples=['http://example.com/'])]
    payload_template: Annotated[
        str | None, Field(alias='payloadTemplate', examples=['{\\n \\"userId\\": {{userId}}...'])
    ] = None
    headers_template: Annotated[
        str | None, Field(alias='headersTemplate', examples=['{\\n \\"Authorization\\": Bearer...'])
    ] = None
    description: Annotated[str | None, Field(examples=['this is webhook description'])] = None
    should_interpolate_strings: Annotated[bool | None, Field(alias='shouldInterpolateStrings', examples=[False])] = None


class CreateWebhookResponse(BaseModel):
    data: Webhook


class GetWebhookResponse(BaseModel):
    data: Webhook


class WebhookUpdate(BaseModel):
    is_ad_hoc: Annotated[bool | None, Field(alias='isAdHoc', examples=[False])] = None
    event_types: Annotated[
        list[WebhookEventType] | None, Field(alias='eventTypes', examples=['ACTOR.RUN.SUCCEEDED'])
    ] = None
    condition: WebhookCondition | None = None
    ignore_ssl_errors: Annotated[bool | None, Field(alias='ignoreSslErrors', examples=[False])] = None
    do_not_retry: Annotated[bool | None, Field(alias='doNotRetry', examples=[False])] = None
    request_url: Annotated[str | None, Field(alias='requestUrl', examples=['http://example.com/'])] = None
    payload_template: Annotated[
        str | None, Field(alias='payloadTemplate', examples=['{\\n \\"userId\\": {{userId}}...'])
    ] = None
    headers_template: Annotated[
        str | None, Field(alias='headersTemplate', examples=['{\\n \\"Authorization\\": Bearer...'])
    ] = None
    description: Annotated[str | None, Field(examples=['this is webhook description'])] = None
    should_interpolate_strings: Annotated[bool | None, Field(alias='shouldInterpolateStrings', examples=[False])] = None


class UpdateWebhookResponse(BaseModel):
    data: Webhook


class EventData(BaseModel):
    actor_id: Annotated[str, Field(alias='actorId', examples=['vvE7iMKuMc5qTHHsR'])]
    actor_run_id: Annotated[str, Field(alias='actorRunId', examples=['JgwXN9BdwxGcu9MMF'])]


class Calls(BaseModel):
    started_at: Annotated[str | None, Field(alias='startedAt', examples=['2019-12-12T07:34:14.202Z'])] = None
    finished_at: Annotated[str | None, Field(alias='finishedAt', examples=['2019-12-12T07:34:14.202Z'])] = None
    error_message: Annotated[str | None, Field(alias='errorMessage', examples=['Cannot send request'])] = None
    response_status: Annotated[float | None, Field(alias='responseStatus', examples=[200])] = None
    response_body: Annotated[str | None, Field(alias='responseBody', examples=[{'foo': 'bar'}])] = None


class WebhookDispatch(BaseModel):
    id: Annotated[str, Field(examples=['asdLZtadYvn4mBZmm'])]
    user_id: Annotated[str, Field(alias='userId', examples=['wRsJZtadYvn4mBZmm'])]
    webhook_id: Annotated[str, Field(alias='webhookId', examples=['asdLZtadYvn4mBZmm'])]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-12-12T07:34:14.202Z'])]
    status: Annotated[str, Field(examples=['SUCCEEDED'])]
    event_type: Annotated[str, Field(alias='eventType', examples=['ACTOR.RUN.SUCCEEDED'])]
    event_data: Annotated[EventData, Field(alias='eventData', title='eventData')]
    calls: Annotated[Calls | None, Field(title='calls')] = None


class TestWebhookResponse(BaseModel):
    data: WebhookDispatch


class ListOfWebhookDispatches(PaginationResponse):
    items: list[WebhookDispatch]


class WebhookDispatchList(BaseModel):
    data: ListOfWebhookDispatches | None = None


class GetWebhookDispatchResponse(BaseModel):
    data: WebhookDispatch


class GetListOfSchedulesResponseDataItemsActions(BaseModel):
    id: Annotated[str, Field(examples=['ZReCs7hkdieq8ZUki'])]
    type: Annotated[str, Field(examples=['RUN_ACTOR'])]
    actor_id: Annotated[str, Field(alias='actorId', examples=['HKhKmiCMrDgu9eXeE'])]


class GetListOfSchedulesResponseDataItems(BaseModel):
    id: Annotated[str, Field(examples=['asdLZtadYvn4mBZmm'])]
    user_id: Annotated[str, Field(alias='userId', examples=['wRsJZtadYvn4mBZmm'])]
    name: Annotated[str, Field(examples=['my-schedule'])]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-12-12T07:34:14.202Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2019-12-20T06:33:11.202Z'])]
    last_run_at: Annotated[str, Field(alias='lastRunAt', examples=['2019-04-12T07:33:10.202Z'])]
    next_run_at: Annotated[str, Field(alias='nextRunAt', examples=['2019-04-12T07:34:10.202Z'])]
    is_enabled: Annotated[bool, Field(alias='isEnabled', examples=[True])]
    is_exclusive: Annotated[bool, Field(alias='isExclusive', examples=[True])]
    cron_expression: Annotated[str, Field(alias='cronExpression', examples=['* * * * *'])]
    timezone: Annotated[str, Field(examples=['UTC'])]
    actions: list[GetListOfSchedulesResponseDataItemsActions]


class GetListOfSchedulesResponseData(BaseModel):
    total: Annotated[float, Field(examples=[2])]
    offset: Annotated[float, Field(examples=[0])]
    limit: Annotated[float, Field(examples=[1000])]
    desc: Annotated[bool, Field(examples=[False])]
    count: Annotated[float, Field(examples=[2])]
    items: list[GetListOfSchedulesResponseDataItems]


class GetListOfSchedulesResponse(BaseModel):
    data: GetListOfSchedulesResponseData


class ScheduleActionsRunInput(BaseModel):
    body: Annotated[str | None, Field(examples=['{\\n   \\"foo\\": \\"actor\\"\\n}'])] = None
    content_type: Annotated[str | None, Field(alias='contentType', examples=['application/json; charset=utf-8'])] = None


class ScheduleActionsRunOptions(BaseModel):
    build: Annotated[str | None, Field(examples=['latest'])] = None
    timeout_secs: Annotated[float | None, Field(alias='timeoutSecs', examples=[60])] = None
    memory_mbytes: Annotated[float | None, Field(alias='memoryMbytes', examples=[1024])] = None
    restart_on_error: Annotated[bool | None, Field(alias='restartOnError', examples=[False])] = None


class ScheduleCreateActions(BaseModel):
    type: Annotated[str, Field(examples=['RUN_ACTOR'])]
    actor_id: Annotated[str, Field(alias='actorId', examples=['jF8GGEvbEg4Au3NLA'])]
    run_input: Annotated[ScheduleActionsRunInput | None, Field(alias='runInput')] = None
    run_options: Annotated[ScheduleActionsRunOptions | None, Field(alias='runOptions')] = None


class ScheduleCreate(BaseModel):
    name: Annotated[str | None, Field(examples=['my-schedule'])] = None
    is_enabled: Annotated[bool | None, Field(alias='isEnabled', examples=[True])] = None
    is_exclusive: Annotated[bool | None, Field(alias='isExclusive', examples=[True])] = None
    cron_expression: Annotated[str | None, Field(alias='cronExpression', examples=['* * * * *'])] = None
    timezone: Annotated[str | None, Field(examples=['UTC'])] = None
    description: Annotated[str | None, Field(examples=['Schedule of actor ...'])] = None
    actions: list[ScheduleCreateActions] | None = None


class ScheduleResponseDataActions(BaseModel):
    id: Annotated[str, Field(examples=['c6KfSgoQzFhMk3etc'])]
    type: Annotated[str, Field(examples=['RUN_ACTOR'])]
    actor_id: Annotated[str, Field(alias='actorId', examples=['jF8GGEvbEg4Au3NLA'])]
    run_input: Annotated[ScheduleActionsRunInput | None, Field(alias='runInput')] = None
    run_options: Annotated[ScheduleActionsRunOptions | None, Field(alias='runOptions')] = None


class ScheduleResponseData(BaseModel):
    id: Annotated[str, Field(examples=['asdLZtadYvn4mBZmm'])]
    user_id: Annotated[str, Field(alias='userId', examples=['wRsJZtadYvn4mBZmm'])]
    name: Annotated[str, Field(examples=['my-schedule'])]
    cron_expression: Annotated[str, Field(alias='cronExpression', examples=['* * * * *'])]
    timezone: Annotated[str, Field(examples=['UTC'])]
    is_enabled: Annotated[bool, Field(alias='isEnabled', examples=[True])]
    is_exclusive: Annotated[bool, Field(alias='isExclusive', examples=[True])]
    description: Annotated[str | None, Field(examples=['Schedule of actor ...'])] = None
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-12-12T07:34:14.202Z'])]
    modified_at: Annotated[str, Field(alias='modifiedAt', examples=['2019-12-20T06:33:11.202Z'])]
    next_run_at: Annotated[str | None, Field(alias='nextRunAt', examples=['2019-04-12T07:34:10.202Z'])] = None
    last_run_at: Annotated[str | None, Field(alias='lastRunAt', examples=['2019-04-12T07:33:10.202Z'])] = None
    actions: list[ScheduleResponseDataActions]


class ScheduleResponse(BaseModel):
    data: ScheduleResponseData


class ScheduleInvoked(BaseModel):
    message: Annotated[str, Field(examples=['Schedule invoked'])]
    level: Annotated[str, Field(examples=['INFO'])]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2019-03-26T12:28:00.370Z'])]


class GetScheduleLogResponse(BaseModel):
    data: list[ScheduleInvoked]


class CurrentPricingInfo(BaseModel):
    pricing_model: Annotated[str, Field(alias='pricingModel', examples=['FREE'])]


class StoreListActor(BaseModel):
    id: Annotated[str, Field(examples=['zdc3Pyhyz3m8vjDeM'])]
    title: Annotated[str, Field(examples=['My Public Actor'])]
    name: Annotated[str, Field(examples=['my-public-actor'])]
    username: Annotated[str, Field(examples=['jane35'])]
    user_full_name: Annotated[str, Field(alias='userFullName', examples=['Jane H. Doe'])]
    description: Annotated[str, Field(examples=['My public actor!'])]
    categories: Annotated[list[str] | None, Field(examples=[['MARKETING', 'LEAD_GENERATION']])] = None
    notice: str | None = None
    picture_url: Annotated[str | None, Field(alias='pictureUrl', examples=['https://...'])] = None
    user_picture_url: Annotated[str | None, Field(alias='userPictureUrl', examples=['https://...'])] = None
    url: Annotated[str | None, Field(examples=['https://...'])] = None
    stats: ActorStats
    current_pricing_info: Annotated[CurrentPricingInfo, Field(alias='currentPricingInfo')]


class StoreData(BaseModel):
    total: Annotated[float, Field(examples=[100])]
    offset: Annotated[float, Field(examples=[0])]
    limit: Annotated[float, Field(examples=[1000])]
    desc: Annotated[bool, Field(examples=[False])]
    count: Annotated[float, Field(examples=[1])]
    items: list[StoreListActor]


class GetListOfActorsInStoreResponse(BaseModel):
    data: StoreData


class Profile(BaseModel):
    bio: Annotated[str | None, Field(examples=['I started web scraping in 1985 using Altair BASIC.'])] = None
    name: Annotated[str | None, Field(examples=['Jane Doe'])] = None
    picture_url: Annotated[str | None, Field(alias='pictureUrl', examples=['/img/anonymous_user_picture.png'])] = None
    github_username: Annotated[str | None, Field(alias='githubUsername', examples=['torvalds.'])] = None
    website_url: Annotated[str | None, Field(alias='websiteUrl', examples=['http://www.example.com'])] = None
    twitter_username: Annotated[str | None, Field(alias='twitterUsername', examples=['@BillGates'])] = None


class UserPublicInfo(BaseModel):
    username: Annotated[str, Field(examples=['d7b9MDYsbtX5L7XAj'])]
    profile: Profile


class GetPublicUserDataResponse(BaseModel):
    data: UserPublicInfo


class ProxyGroup(BaseModel):
    name: Annotated[str, Field(examples=['Group1'])]
    description: Annotated[str, Field(examples=['Group1 description'])]
    available_count: Annotated[float, Field(alias='availableCount', examples=[10])]


class Proxy(BaseModel):
    password: Annotated[str, Field(examples=['ad78knd9Jkjd86'])]
    groups: list[ProxyGroup]


class AvailableProxyGroups(BaseModel):
    somegroup: Annotated[float, Field(alias='SOMEGROUP', examples=[20])]
    anothergroup: Annotated[float, Field(alias='ANOTHERGROUP', examples=[200])]


class Plan(BaseModel):
    id: Annotated[str, Field(examples=['Personal'])]
    description: Annotated[str, Field(examples=['Cost-effective plan for freelancers, developers and students.'])]
    is_enabled: Annotated[bool, Field(alias='isEnabled', examples=[True])]
    monthly_base_price_usd: Annotated[float, Field(alias='monthlyBasePriceUsd', examples=[49])]
    monthly_usage_credits_usd: Annotated[float, Field(alias='monthlyUsageCreditsUsd', examples=[49])]
    usage_discount_percent: Annotated[float, Field(alias='usageDiscountPercent', examples=[0])]
    enabled_platform_features: Annotated[
        list[list[Any]],
        Field(
            alias='enabledPlatformFeatures',
            examples=[[['ACTORS'], ['STORAGE'], ['PROXY_SERPS'], ['SCHEDULER'], ['WEBHOOKS']]],
        ),
    ]
    max_monthly_usage_usd: Annotated[float, Field(alias='maxMonthlyUsageUsd', examples=[9999])]
    max_actor_memory_gbytes: Annotated[float, Field(alias='maxActorMemoryGbytes', examples=[32])]
    max_monthly_actor_compute_units: Annotated[float, Field(alias='maxMonthlyActorComputeUnits', examples=[1000])]
    max_monthly_residential_proxy_gbytes: Annotated[
        float, Field(alias='maxMonthlyResidentialProxyGbytes', examples=[10])
    ]
    max_monthly_proxy_serps: Annotated[float, Field(alias='maxMonthlyProxySerps', examples=[30000])]
    max_monthly_external_data_transfer_gbytes: Annotated[
        float, Field(alias='maxMonthlyExternalDataTransferGbytes', examples=[1000])
    ]
    max_actor_count: Annotated[float, Field(alias='maxActorCount', examples=[100])]
    max_actor_task_count: Annotated[float, Field(alias='maxActorTaskCount', examples=[1000])]
    data_retention_days: Annotated[float, Field(alias='dataRetentionDays', examples=[14])]
    available_proxy_groups: Annotated[AvailableProxyGroups, Field(alias='availableProxyGroups')]
    team_account_seat_count: Annotated[float, Field(alias='teamAccountSeatCount', examples=[1])]
    support_level: Annotated[str, Field(alias='supportLevel', examples=['COMMUNITY'])]
    available_add_ons: Annotated[list[str], Field(alias='availableAddOns', examples=[[]])]


class EffectivePlatformFeature(BaseModel):
    is_enabled: Annotated[bool, Field(alias='isEnabled', examples=[True])]
    disabled_reason: Annotated[
        str,
        Field(
            alias='disabledReason',
            examples=[
                'The "Selected public Actors for developers" feature is not enabled for your account. Please upgrade your plan or contact support@apify.com'
            ],
        ),
    ]
    disabled_reason_type: Annotated[str, Field(alias='disabledReasonType', examples=['DISABLED'])]
    is_trial: Annotated[bool, Field(alias='isTrial', examples=[False])]
    trial_expiration_at: Annotated[str, Field(alias='trialExpirationAt', examples=['2025-01-01T14:00:00.000Z'])]


class EffectivePlatformFeatures(BaseModel):
    actors: Annotated[EffectivePlatformFeature, Field(alias='ACTORS')]
    storage: Annotated[EffectivePlatformFeature, Field(alias='STORAGE')]
    scheduler: Annotated[EffectivePlatformFeature, Field(alias='SCHEDULER')]
    proxy: Annotated[EffectivePlatformFeature, Field(alias='PROXY')]
    proxy_external_access: Annotated[EffectivePlatformFeature, Field(alias='PROXY_EXTERNAL_ACCESS')]
    proxy_residential: Annotated[EffectivePlatformFeature, Field(alias='PROXY_RESIDENTIAL')]
    proxy_serps: Annotated[EffectivePlatformFeature, Field(alias='PROXY_SERPS')]
    webhooks: Annotated[EffectivePlatformFeature, Field(alias='WEBHOOKS')]
    actors_public_all: Annotated[EffectivePlatformFeature, Field(alias='ACTORS_PUBLIC_ALL')]
    actors_public_developer: Annotated[EffectivePlatformFeature, Field(alias='ACTORS_PUBLIC_DEVELOPER')]


class UserPrivateInfo(BaseModel):
    id: Annotated[str, Field(examples=['YiKoxjkaS9gjGTqhF'])]
    username: Annotated[str, Field(examples=['myusername'])]
    profile: Profile
    email: Annotated[str, Field(examples=['bob@example.com'])]
    proxy: Proxy
    plan: Plan
    effective_platform_features: Annotated[EffectivePlatformFeatures, Field(alias='effectivePlatformFeatures')]
    created_at: Annotated[str, Field(alias='createdAt', examples=['2022-11-29T14:48:29.381Z'])]
    is_paying: Annotated[bool, Field(alias='isPaying', examples=[True])]


class GetPrivateUserDataResponse(BaseModel):
    data: UserPrivateInfo


class UsageCycle(BaseModel):
    start_at: Annotated[str, Field(alias='startAt', examples=['2022-10-02T00:00:00.000Z'])]
    end_at: Annotated[str, Field(alias='endAt', examples=['2022-11-01T23:59:59.999Z'])]


class PriceTiers(BaseModel):
    quantity_above: Annotated[float, Field(alias='quantityAbove', examples=[0])]
    discount_percent: Annotated[float, Field(alias='discountPercent', examples=[100])]
    tier_quantity: Annotated[float, Field(alias='tierQuantity', examples=[0.39])]
    unit_price_usd: Annotated[float, Field(alias='unitPriceUsd', examples=[0])]
    price_usd: Annotated[float, Field(alias='priceUsd', examples=[0])]


class UsageItem(BaseModel):
    quantity: Annotated[float, Field(examples=[2.784475])]
    base_amount_usd: Annotated[float, Field(alias='baseAmountUsd', examples=[0.69611875])]
    base_unit_price_usd: Annotated[float, Field(alias='baseUnitPriceUsd', examples=[0.25])]
    amount_after_volume_discount_usd: Annotated[
        float, Field(alias='amountAfterVolumeDiscountUsd', examples=[0.69611875])
    ]
    price_tiers: Annotated[list[PriceTiers], Field(alias='priceTiers')]


class MonthlyServiceUsage(BaseModel):
    usage_item: Annotated[UsageItem, Field(alias='USAGE_ITEM')]


class ServiceUsage(BaseModel):
    service_usage_item: Annotated[UsageItem, Field(alias='SERVICE_USAGE_ITEM')]


class DailyServiceUsages(BaseModel):
    date: Annotated[str, Field(examples=['2022-10-02T00:00:00.000Z'])]
    service_usage: Annotated[ServiceUsage, Field(alias='serviceUsage')]
    total_usage_credits_usd: Annotated[float, Field(alias='totalUsageCreditsUsd', examples=[0.0474385791970591])]


class MonthlyUsage(BaseModel):
    usage_cycle: Annotated[UsageCycle, Field(alias='usageCycle')]
    monthly_service_usage: Annotated[MonthlyServiceUsage, Field(alias='monthlyServiceUsage')]
    daily_service_usages: Annotated[list[DailyServiceUsages], Field(alias='dailyServiceUsages')]
    total_usage_credits_usd_before_volume_discount: Annotated[
        float, Field(alias='totalUsageCreditsUsdBeforeVolumeDiscount', examples=[0.786143673840067])
    ]
    total_usage_credits_usd_after_volume_discount: Annotated[
        float, Field(alias='totalUsageCreditsUsdAfterVolumeDiscount', examples=[0.786143673840067])
    ]


class GetMonthlyUsageResponse(BaseModel):
    data: MonthlyUsage


class MonthlyUsageCycle(BaseModel):
    start_at: Annotated[str, Field(alias='startAt', examples=['2022-10-02T00:00:00.000Z'])]
    end_at: Annotated[str, Field(alias='endAt', examples=['2022-11-01T23:59:59.999Z'])]


class Limits(BaseModel):
    max_monthly_usage_usd: Annotated[float, Field(alias='maxMonthlyUsageUsd', examples=[300])]
    max_monthly_actor_compute_units: Annotated[float, Field(alias='maxMonthlyActorComputeUnits', examples=[1000])]
    max_monthly_external_data_transfer_gbytes: Annotated[
        float, Field(alias='maxMonthlyExternalDataTransferGbytes', examples=[7])
    ]
    max_monthly_proxy_serps: Annotated[float, Field(alias='maxMonthlyProxySerps', examples=[50])]
    max_monthly_residential_proxy_gbytes: Annotated[
        float, Field(alias='maxMonthlyResidentialProxyGbytes', examples=[0.5])
    ]
    max_actor_memory_gbytes: Annotated[float, Field(alias='maxActorMemoryGbytes', examples=[16])]
    max_actor_count: Annotated[float, Field(alias='maxActorCount', examples=[100])]
    max_actor_task_count: Annotated[float, Field(alias='maxActorTaskCount', examples=[1000])]
    max_concurrent_actor_jobs: Annotated[float, Field(alias='maxConcurrentActorJobs', examples=[256])]
    max_team_account_seat_count: Annotated[float, Field(alias='maxTeamAccountSeatCount', examples=[9])]
    data_retention_days: Annotated[float, Field(alias='dataRetentionDays', examples=[90])]


class Current(BaseModel):
    monthly_usage_usd: Annotated[float, Field(alias='monthlyUsageUsd', examples=[43])]
    monthly_actor_compute_units: Annotated[float, Field(alias='monthlyActorComputeUnits', examples=[500.784475])]
    monthly_external_data_transfer_gbytes: Annotated[
        float, Field(alias='monthlyExternalDataTransferGbytes', examples=[3.00861903931946])
    ]
    monthly_proxy_serps: Annotated[float, Field(alias='monthlyProxySerps', examples=[34])]
    monthly_residential_proxy_gbytes: Annotated[float, Field(alias='monthlyResidentialProxyGbytes', examples=[0.4])]
    actor_memory_gbytes: Annotated[float, Field(alias='actorMemoryGbytes', examples=[8])]
    actor_count: Annotated[float, Field(alias='actorCount', examples=[31])]
    actor_task_count: Annotated[float, Field(alias='actorTaskCount', examples=[130])]
    active_actor_job_count: Annotated[float, Field(alias='activeActorJobCount', examples=[0])]
    team_account_seat_count: Annotated[float, Field(alias='teamAccountSeatCount', examples=[5])]


class AccountLimits(BaseModel):
    monthly_usage_cycle: Annotated[MonthlyUsageCycle, Field(alias='monthlyUsageCycle')]
    limits: Limits
    current: Current


class GetLimitsResponse(BaseModel):
    data: AccountLimits


class UpdateLimitsRequest(BaseModel):
    max_monthly_usage_usd: Annotated[float | None, Field(alias='maxMonthlyUsageUsd', examples=[300])] = None
    """
    If your platform usage in the billing period exceeds the prepaid usage, you will be charged extra. Setting this property you can update your hard limit on monthly platform usage to prevent accidental overage or to limit the extra charges.

    """
    data_retention_days: Annotated[float | None, Field(alias='dataRetentionDays', examples=[90])] = None
    """
    Apify securely stores your ten most recent Actor runs indefinitely, ensuring they are always accessible. Unnamed storages and other Actor runs are automatically deleted after the retention period. If you're subscribed, you can change it to keep data for longer or to limit your usage. [Lear more](https://docs.apify.com/platform/storage/usage#data-retention).

    """
