# generated by datamodel-codegen

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypeAlias, TypedDict

from apify_client._docs import docs_group


@docs_group('Typed dicts')
class RequestBaseDict(TypedDict):
    unique_key: NotRequired[str]
    """
    A unique key used for request de-duplication. Requests with the same unique key are considered identical.
    """
    url: NotRequired[str]
    """
    The URL of the request.
    """
    method: NotRequired[Literal['GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'CONNECT', 'OPTIONS', 'TRACE', 'PATCH']]
    retry_count: NotRequired[int]
    """
    The number of times this request has been retried.
    """
    loaded_url: NotRequired[str | None]
    """
    The final URL that was loaded, after redirects (if any).
    """
    payload: NotRequired[str | dict[str, Any] | None]
    """
    The request payload, typically used with POST or PUT requests.
    """
    headers: NotRequired[dict[str, Any] | None]
    """
    HTTP headers sent with the request.
    """
    user_data: NotRequired[RequestUserDataDict]
    no_retry: NotRequired[bool | None]
    """
    Indicates whether the request should not be retried if processing fails.
    """
    error_messages: NotRequired[list[str]]
    """
    Error messages recorded from failed processing attempts.
    """
    handled_at: NotRequired[str | None]
    """
    The timestamp when the request was marked as handled, if applicable.
    """


@docs_group('Typed dicts')
class RequestDict(RequestBaseDict):
    """A request stored in the request queue, including its metadata and processing state."""

    id: NotRequired[str]
    """
    A unique identifier assigned to the request.
    """


RequestUserDataDict: TypeAlias = dict[str, Any]


TaskInputDict: TypeAlias = dict[str, Any]


@docs_group('Typed dicts')
class WebhookConditionDict(TypedDict):
    actor_id: NotRequired[str | None]
    actor_task_id: NotRequired[str | None]
    actor_run_id: NotRequired[str | None]


@docs_group('Typed dicts')
class WebhookCreateDict(TypedDict):
    is_ad_hoc: NotRequired[bool | None]
    event_types: list[
        Literal[
            'ACTOR.BUILD.ABORTED',
            'ACTOR.BUILD.CREATED',
            'ACTOR.BUILD.FAILED',
            'ACTOR.BUILD.SUCCEEDED',
            'ACTOR.BUILD.TIMED_OUT',
            'ACTOR.RUN.ABORTED',
            'ACTOR.RUN.CREATED',
            'ACTOR.RUN.FAILED',
            'ACTOR.RUN.RESURRECTED',
            'ACTOR.RUN.SUCCEEDED',
            'ACTOR.RUN.TIMED_OUT',
            'TEST',
        ]
    ]
    condition: WebhookConditionDict
    idempotency_key: NotRequired[str | None]
    ignore_ssl_errors: NotRequired[bool | None]
    do_not_retry: NotRequired[bool | None]
    request_url: str
    payload_template: NotRequired[str | None]
    headers_template: NotRequired[str | None]
    description: NotRequired[str | None]
    should_interpolate_strings: NotRequired[bool | None]
