module.exports = {
    sidebar: [
        'quick-start',
        'features',
        'usage-concepts',
        // {
        //     type: 'category',
        //     label: 'Examples',
        //     items: [
        //         {
        //             type: 'autogenerated',
        //             dirName: 'examples',
        //         },
        //     ],
        // },
        {
            type: 'doc',
            id: 'changelog',
        },
    ],
};
