# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2025-10-30T16:49:20+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class PaginationResponse(BaseModel):
    total: float = Field(..., examples=[2])
    offset: float = Field(..., examples=[0])
    limit: float = Field(..., examples=[1000])
    desc: bool = Field(..., examples=[False])
    count: float = Field(..., examples=[2])


class ActorShort(BaseModel):
    id: str = Field(..., examples=['br9CKmk457'])
    createdAt: str = Field(..., examples=['2019-10-29T07:34:24.202Z'])
    modifiedAt: str = Field(..., examples=['2019-10-30T07:34:24.202Z'])
    name: str = Field(..., examples=['MyAct'])
    username: str = Field(..., examples=['janedoe'])


class Data(PaginationResponse):
    items: List[ActorShort]


class GetListOfActorsResponse(BaseModel):
    data: Data


class VersionSourceType(Enum):
    SOURCE_FILES = 'SOURCE_FILES'
    GIT_REPO = 'GIT_REPO'
    TARBALL = 'TARBALL'
    GITHUB_GIST = 'GITHUB_GIST'


class EnvVar(BaseModel):
    name: str = Field(..., examples=['MY_ENV_VAR'])
    value: str = Field(..., examples=['my-value'])
    isSecret: Optional[bool] = Field(None, examples=[False])


class Format(Enum):
    BASE64 = 'BASE64'
    TEXT = 'TEXT'


class VersionSourceFiles1(BaseModel):
    format: Format = Field(..., examples=['TEXT'])
    content: str = Field(..., examples=["console.log('This is the main.js file');"])
    name: str = Field(..., examples=['src/main.js'])


class Folder(Enum):
    boolean_True = True


class VersionSourceFiles2(BaseModel):
    name: str = Field(..., examples=['src/placeholder'])
    folder: Folder = Field(..., examples=[True])


class VersionSourceFiles(
    RootModel[List[Union[VersionSourceFiles1, VersionSourceFiles2]]]
):
    root: List[Union[VersionSourceFiles1, VersionSourceFiles2]] = Field(
        ..., title='VersionSourceFiles'
    )


class Version(BaseModel):
    versionNumber: str = Field(..., examples=['0.0'])
    sourceType: Union[Any, VersionSourceType]
    envVars: Optional[List[EnvVar]] = None
    applyEnvVarsToBuild: Optional[bool] = Field(None, examples=[False])
    buildTag: str = Field(..., examples=['latest'])
    sourceFiles: Optional[VersionSourceFiles] = None


class CommonActorPricingInfo(BaseModel):
    apifyMarginPercentage: float
    """
    In [0, 1], fraction of pricePerUnitUsd that goes to Apify
    """
    createdAt: AwareDatetime
    """
    When this pricing info record has been created
    """
    startedAt: AwareDatetime
    """
    Since when is this pricing info record effective for a given Actor
    """
    notifiedAboutFutureChangeAt: Optional[AwareDatetime] = None
    notifiedAboutChangeAt: Optional[AwareDatetime] = None
    reasonForChange: Optional[str] = None


class ActorChargeEvent(BaseModel):
    eventPriceUsd: float
    eventTitle: str
    eventDescription: str


class PricingModel(Enum):
    PAY_PER_EVENT = 'PAY_PER_EVENT'


class PricingPerEvent(BaseModel):
    actorChargeEvents: Optional[Dict[str, ActorChargeEvent]] = None


class PayPerEventActorPricingInfo(CommonActorPricingInfo):
    pricingModel: Literal['PAY_PER_EVENT']
    pricingPerEvent: PricingPerEvent
    minimalMaxTotalChargeUsd: Optional[float] = None


class PricingModel1(Enum):
    PRICE_PER_DATASET_ITEM = 'PRICE_PER_DATASET_ITEM'


class PricePerDatasetItemActorPricingInfo(CommonActorPricingInfo):
    pricingModel: Literal['PRICE_PER_DATASET_ITEM']
    unitName: str
    """
    Name of the unit that is being charged
    """
    pricePerUnitUsd: float


class PricingModel2(Enum):
    FLAT_PRICE_PER_MONTH = 'FLAT_PRICE_PER_MONTH'


class FlatPricePerMonthActorPricingInfo(CommonActorPricingInfo):
    pricingModel: Literal['FLAT_PRICE_PER_MONTH']
    trialMinutes: float
    """
    For how long this Actor can be used for free in trial period
    """
    pricePerUnitUsd: float
    """
    Monthly flat price in USD
    """


class PricingModel3(Enum):
    FREE = 'FREE'


class FreeActorPricingInfo(CommonActorPricingInfo):
    pricingModel: Literal['FREE']


class ActorRunPricingInfo(
    RootModel[
        Union[
            PayPerEventActorPricingInfo,
            PricePerDatasetItemActorPricingInfo,
            FlatPricePerMonthActorPricingInfo,
            FreeActorPricingInfo,
        ]
    ]
):
    root: Union[
        PayPerEventActorPricingInfo,
        PricePerDatasetItemActorPricingInfo,
        FlatPricePerMonthActorPricingInfo,
        FreeActorPricingInfo,
    ] = Field(..., discriminator='pricingModel', title='ActorRunPricingInfo')


class DefaultRunOptions(BaseModel):
    build: str = Field(..., examples=['latest'])
    timeoutSecs: float = Field(..., examples=[3600])
    memoryMbytes: float = Field(..., examples=[2048])
    restartOnError: Optional[bool] = Field(None, examples=[False])


class CreateActorRequest(BaseModel):
    name: Optional[str] = Field(None, examples=['MyActor'])
    description: Optional[str] = Field(None, examples=['My favourite actor!'])
    title: Optional[str] = Field(None, examples=['My actor'])
    isPublic: Optional[bool] = Field(None, examples=[False])
    seoTitle: Optional[str] = Field(None, examples=['My actor'])
    seoDescription: Optional[str] = Field(None, examples=['My actor is the best'])
    restartOnError: Optional[bool] = Field(None, examples=[False])
    versions: Optional[List[Version]] = None
    pricingInfos: Optional[List[ActorRunPricingInfo]] = None
    categories: Optional[List[str]] = None
    defaultRunOptions: Optional[DefaultRunOptions] = None


class ActorStats(BaseModel):
    totalBuilds: float = Field(..., examples=[9])
    totalRuns: float = Field(..., examples=[16])
    totalUsers: float = Field(..., examples=[6])
    totalUsers7Days: float = Field(..., examples=[2])
    totalUsers30Days: float = Field(..., examples=[6])
    totalUsers90Days: float = Field(..., examples=[6])
    totalMetamorphs: float = Field(..., examples=[2])
    lastRunStartedAt: str = Field(..., examples=['2019-07-08T14:01:05.546Z'])


class ExampleRunInput(BaseModel):
    body: str = Field(..., examples=[{'helloWorld': 123}])
    contentType: str = Field(..., examples=['application/json; charset=utf-8'])


class Latest(BaseModel):
    buildId: Optional[str] = Field(None, examples=['z2EryhbfhgSyqj6Hn'])
    buildNumber: Optional[str] = Field(None, examples=['0.0.2'])
    finishedAt: Optional[str] = Field(None, examples=['2019-06-10T11:15:49.286Z'])


class TaggedBuilds(BaseModel):
    latest: Optional[Union[Any, Latest]] = None


class Actor(BaseModel):
    id: str = Field(..., examples=['zdc3Pyhyz3m8vjDeM'])
    userId: str = Field(..., examples=['wRsJZtadYvn4mBZmm'])
    name: str = Field(..., examples=['MyActor'])
    username: str = Field(..., examples=['jane35'])
    description: Optional[str] = Field(None, examples=['My favourite actor!'])
    restartOnError: Optional[bool] = Field(None, examples=[False])
    isPublic: bool = Field(..., examples=[False])
    createdAt: str = Field(..., examples=['2019-07-08T11:27:57.401Z'])
    modifiedAt: str = Field(..., examples=['2019-07-08T14:01:05.546Z'])
    stats: ActorStats
    versions: List[Version]
    pricingInfos: Optional[List[ActorRunPricingInfo]] = None
    defaultRunOptions: DefaultRunOptions
    exampleRunInput: Optional[Union[Any, ExampleRunInput]] = None
    isDeprecated: Optional[bool] = Field(None, examples=[False])
    deploymentKey: str = Field(..., examples=['ssh-rsa AAAA ...'])
    title: Optional[str] = Field(None, examples=['My Actor'])
    taggedBuilds: Optional[Union[Any, TaggedBuilds]] = None


class CreateActorResponse(BaseModel):
    data: Actor


class GetActorResponse(BaseModel):
    data: Actor


class CreateOrUpdateEnvVarRequest(BaseModel):
    name: str = Field(..., examples=['MY_ENV_VAR'])
    value: str = Field(..., examples=['my-new-value'])
    isSecret: Optional[bool] = Field(None, examples=[False])


class TaggedBuilds1(BaseModel):
    buildId: str


class UpdateActorRequest(BaseModel):
    name: str = Field(..., examples=['MyActor'])
    description: Optional[str] = Field(None, examples=['My favourite actor!'])
    isPublic: bool = Field(..., examples=[False])
    seoTitle: Optional[str] = Field(None, examples=['My actor'])
    seoDescription: Optional[str] = Field(None, examples=['My actor is the best'])
    title: Optional[str] = Field(None, examples=['My Actor'])
    restartOnError: Optional[bool] = Field(None, examples=[False])
    versions: List[CreateOrUpdateEnvVarRequest]
    pricingInfos: Optional[List[ActorRunPricingInfo]] = None
    categories: Optional[List[str]] = None
    defaultRunOptions: Optional[DefaultRunOptions] = None
    taggedBuilds: Optional[Dict[str, TaggedBuilds1]] = Field(
        None, examples=[{'latest': {'buildId': 'z2EryhbfhgSyqj6Hn'}, 'beta': None}]
    )
    """
    An object to modify tags on the Actor's builds. The key is the tag name (e.g., _latest_), and the value is either an object with a `buildId` or `null`.

    This operation is a patch; any existing tags that you omit from this object will be preserved.

    - **To create or reassign a tag**, provide the tag name with a `buildId`. e.g., to assign the _latest_ tag:

      &nbsp;

      ```json
      {
        "latest": {
          "buildId": "z2EryhbfhgSyqj6Hn"
        }
      }
      ```

    - **To remove a tag**, provide the tag name with a `null` value. e.g., to remove the _beta_ tag:

      &nbsp;

      ```json
      {
        "beta": null
      }
      ```

    - **To perform multiple operations**, combine them. The following reassigns _latest_ and removes _beta_, while preserving any other existing tags.

      &nbsp;

      ```json
      {
        "latest": {
          "buildId": "z2EryhbfhgSyqj6Hn"
        },
        "beta": null
      }
      ```

    """


class UpdateActorResponse(BaseModel):
    data: Actor


class Data1(BaseModel):
    total: float = Field(..., examples=[5])
    items: List[Version]


class GetVersionListResponse(BaseModel):
    data: Data1


class CreateOrUpdateVersionRequest(BaseModel):
    versionNumber: Optional[str] = Field(None, examples=['0.0'])
    sourceType: Optional[Union[Any, VersionSourceType]] = None
    envVars: Optional[List[EnvVar]] = None
    applyEnvVarsToBuild: Optional[bool] = Field(None, examples=[False])
    buildTag: Optional[str] = Field(None, examples=['latest'])
    sourceFiles: Optional[VersionSourceFiles] = None


class GetVersionResponse(BaseModel):
    data: Version


class Data2(BaseModel):
    total: float = Field(..., examples=[5])
    items: List[EnvVar]


class GetEnvVarListResponse(BaseModel):
    data: Data2


class GetEnvVarResponse(BaseModel):
    data: EnvVar


class WebhookCondition(BaseModel):
    actorId: Optional[str] = Field(None, examples=['hksJZtadYvn4mBuin'])
    actorTaskId: Optional[str] = Field(None, examples=['asdLZtadYvn4mBZmm'])
    actorRunId: Optional[str] = Field(None, examples=['hgdKZtadYvn4mBpoi'])


class ExampleWebhookDispatch(BaseModel):
    status: str = Field(..., examples=['SUCCEEDED'])
    finishedAt: str = Field(..., examples=['2019-12-13T08:36:13.202Z'])


class WebhookStats(BaseModel):
    totalDispatches: float = Field(..., examples=[1])


class WebhookShort(BaseModel):
    id: str = Field(..., examples=['YiKoxjkaS9gjGTqhF'])
    createdAt: str = Field(..., examples=['2019-12-12T07:34:14.202Z'])
    modifiedAt: str = Field(..., examples=['2019-12-13T08:36:13.202Z'])
    userId: str = Field(..., examples=['wRsJZtadYvn4mBZmm'])
    isAdHoc: Optional[bool] = Field(None, examples=[False])
    shouldInterpolateStrings: Optional[bool] = Field(None, examples=[False])
    eventTypes: List[str] = Field(..., examples=[['ACTOR.RUN.SUCCEEDED']])
    condition: WebhookCondition
    ignoreSslErrors: bool = Field(..., examples=[False])
    doNotRetry: bool = Field(..., examples=[False])
    requestUrl: str = Field(..., examples=['http://example.com/'])
    lastDispatch: Optional[ExampleWebhookDispatch] = None
    stats: Optional[WebhookStats] = None


class Data3(PaginationResponse):
    items: Optional[List[WebhookShort]] = None


class GetListOfWebhooksResponse(BaseModel):
    data: Data3


class BuildsMeta(BaseModel):
    origin: str = Field(..., examples=['WEB'])
    clientIp: str = Field(..., examples=['172.234.12.34'])
    userAgent: str = Field(..., examples=['Mozilla/5.0 (iPad)'])


class BuildShort(BaseModel):
    id: str = Field(..., examples=['HG7ML7M8z78YcAPEB'])
    actId: Optional[str] = Field(None, examples=['janedoe~my-actor'])
    status: str = Field(..., examples=['SUCCEEDED'])
    startedAt: str = Field(..., examples=['2019-11-30T07:34:24.202Z'])
    finishedAt: str = Field(..., examples=['2019-12-12T09:30:12.202Z'])
    usageTotalUsd: float = Field(..., examples=[0.02])
    meta: Optional[BuildsMeta] = None


class Data4(BaseModel):
    total: float = Field(..., examples=[2])
    offset: float = Field(..., examples=[0])
    limit: float = Field(..., examples=[1000])
    desc: bool = Field(..., examples=[False])
    count: float = Field(..., examples=[2])
    items: List[BuildShort]


class GetBuildListResponse(BaseModel):
    data: Data4


class BuildStats(BaseModel):
    durationMillis: float = Field(..., examples=[1000])
    runTimeSecs: float = Field(..., examples=[45.718])
    computeUnits: float = Field(..., examples=[0.0126994444444444])


class BuildOptions(BaseModel):
    useCache: Optional[bool] = Field(None, examples=[False])
    betaPackages: Optional[bool] = Field(None, examples=[False])
    memoryMbytes: Optional[float] = Field(None, examples=[1024])
    diskMbytes: Optional[float] = Field(None, examples=[2048])


class BuildUsage(BaseModel):
    ACTOR_COMPUTE_UNITS: Optional[float] = Field(None, examples=[0.08])


class ActorSpecification(Enum):
    """
    The Actor specification version that this Actor follows. This property must be set to 1.
    """

    integer_1 = 1


class Storages(BaseModel):
    dataset: Optional[Dict[str, Any]] = None
    """
    Defines the schema of items in your dataset, the full specification can be found in [Apify docs](https://docs.apify.com/platform/actors/development/actor-definition/dataset-schema)
    """


class ActorDefinition(BaseModel):
    """
    The definition of the Actor, the full specification of this field can be found in [Apify docs](https://docs.apify.com/platform/actors/development/actor-definition/actor-json)
    """

    actorSpecification: ActorSpecification
    """
    The Actor specification version that this Actor follows. This property must be set to 1.
    """
    name: str
    """
    The name of the Actor.
    """
    version: str = Field(..., pattern='^[0-9]+\\\\.[0-9]+$')
    """
    The version of the Actor, specified in the format [Number].[Number], e.g., 0.1, 1.0.
    """
    buildTag: Optional[str] = None
    """
    The tag name to be applied to a successful build of the Actor. Defaults to 'latest' if not specified.
    """
    environmentVariables: Optional[Dict[str, str]] = None
    """
    A map of environment variables to be used during local development and deployment.
    """
    dockerfile: Optional[str] = None
    """
    The path to the Dockerfile used for building the Actor on the platform.
    """
    dockerContextDir: Optional[str] = None
    """
    The path to the directory used as the Docker context when building the Actor.
    """
    readme: Optional[str] = None
    """
    The path to the README file for the Actor.
    """
    input: Optional[Dict[str, Any]] = None
    """
    The input schema object, the full specification can be found in [Apify docs](https://docs.apify.com/platform/actors/development/actor-definition/input-schema)
    """
    changelog: Optional[str] = None
    """
    The path to the CHANGELOG file displayed in the Actor's information tab.
    """
    storages: Optional[Storages] = None
    minMemoryMbytes: Optional[int] = Field(None, ge=256)
    """
    Specifies the minimum amount of memory in megabytes required by the Actor.
    """
    maxMemoryMbytes: Optional[int] = Field(None, ge=256)
    """
    Specifies the maximum amount of memory in megabytes required by the Actor.
    """
    usesStandbyMode: Optional[bool] = None
    """
    Specifies whether the Actor will have Standby mode enabled.
    """


class Stats1(BaseModel):
    pass


class Stats2(BuildStats, Stats1):
    pass


class Stats(RootModel[Stats2]):
    root: Stats2


class Options1(BaseModel):
    pass


class Options2(BuildOptions, Options1):
    pass


class Options(RootModel[Options2]):
    root: Options2


class Usage1(BaseModel):
    pass


class Usage2(BuildUsage, Usage1):
    pass


class Usage(RootModel[Usage2]):
    root: Usage2


class UsageUsd1(BaseModel):
    pass


class UsageUsd2(BuildUsage, UsageUsd1):
    pass


class UsageUsd(RootModel[UsageUsd2]):
    root: UsageUsd2


class Build(BaseModel):
    id: str = Field(..., examples=['HG7ML7M8z78YcAPEB'])
    actId: str = Field(..., examples=['janedoe~my-actor'])
    userId: str = Field(..., examples=['klmdEpoiojmdEMlk3'])
    startedAt: str = Field(..., examples=['2019-11-30T07:34:24.202Z'])
    finishedAt: Optional[str] = Field(None, examples=['2019-12-12T09:30:12.202Z'])
    status: str = Field(..., examples=['SUCCEEDED'])
    meta: BuildsMeta
    stats: Optional[Stats] = None
    options: Optional[Options] = None
    usage: Optional[Usage] = None
    usageTotalUsd: Optional[float] = Field(None, examples=[0.02])
    usageUsd: Optional[UsageUsd] = None
    inputSchema: Optional[str] = Field(
        None, examples=['{\\n  \\"title\\": \\"Schema for ... }']
    )
    readme: Optional[str] = Field(
        None, examples=['# Magic Actor\\nThis Actor is magic.']
    )
    buildNumber: str = Field(..., examples=['0.1.1'])
    actorDefinition: Optional[ActorDefinition] = None


class BuildActorResponse(BaseModel):
    data: Build


class GetBuildResponse(BaseModel):
    data: Build


class Info(BaseModel):
    title: Optional[str] = Field(None, examples=['Your Magic Actor'])
    version: Optional[str] = Field(None, examples=['1.0'])
    x_build_id: Optional[str] = Field(
        None, alias='x-build-id', examples=['ID of build']
    )


class Server(BaseModel):
    url: Optional[str] = Field(None, examples=['https://api.apify.com/v2'])


class Schema(BaseModel):
    field_ref: Optional[str] = Field(
        None, alias='$ref', examples=['#/components/schemas/inputSchema']
    )


class ApplicationJson(BaseModel):
    schema_: Optional[Schema] = Field(None, alias='schema')


class Content(BaseModel):
    application_json: Optional[ApplicationJson] = Field(None, alias='application/json')


class RequestBody(BaseModel):
    required: Optional[bool] = Field(None, examples=[True])
    content: Optional[Content] = None


class Schema1(BaseModel):
    type: Optional[str] = Field(None, examples=['string'])


class Parameter(BaseModel):
    name: Optional[str] = Field(None, examples=['token'])
    in_: Optional[str] = Field(None, alias='in', examples=['query'])
    required: Optional[bool] = Field(None, examples=[True])
    schema_: Optional[Schema1] = Field(None, alias='schema')
    description: Optional[str] = Field(None, examples=['Enter your Apify token here'])


class Field200(BaseModel):
    description: Optional[str] = Field(None, examples=['OK'])


class Responses(BaseModel):
    field_200: Optional[Field200] = Field(None, alias='200')


class Post(BaseModel):
    operationId: Optional[str] = Field(None, examples=['run-sync-get-dataset-items'])
    x_openai_isConsequential: Optional[bool] = Field(
        None, alias='x-openai-isConsequential', examples=[False]
    )
    summary: Optional[str] = Field(
        None,
        examples=[
            "Executes an Actor, waits for its completion, and returns Actor's dataset items in response."
        ],
    )
    tags: Optional[List[str]] = Field(None, examples=[['Run Actor']])
    requestBody: Optional[RequestBody] = None
    parameters: Optional[List[Parameter]] = None
    responses: Optional[Responses] = None


class FieldActsUsernameActorRunSyncGetDatasetItems(BaseModel):
    post: Optional[Post] = None


class Schema2(BaseModel):
    field_ref: Optional[str] = Field(
        None, alias='$ref', examples=['#/components/schemas/inputSchema']
    )


class ApplicationJson1(BaseModel):
    schema_: Optional[Schema2] = Field(None, alias='schema')


class Content1(BaseModel):
    application_json: Optional[ApplicationJson1] = Field(None, alias='application/json')


class RequestBody1(BaseModel):
    required: Optional[bool] = Field(None, examples=[True])
    content: Optional[Content1] = None


class Schema3(BaseModel):
    type: Optional[str] = None


class Parameter1(BaseModel):
    name: Optional[str] = None
    in_: Optional[str] = Field(None, alias='in', examples=['query'])
    required: Optional[bool] = None
    schema_: Optional[Schema3] = Field(None, alias='schema')
    description: Optional[str] = None


class Schema4(BaseModel):
    field_ref: Optional[str] = Field(
        None, alias='$ref', examples=['#/components/schemas/runsResponseSchema']
    )


class ApplicationJson2(BaseModel):
    schema_: Optional[Schema4] = Field(None, alias='schema')


class Content2(BaseModel):
    application_json: Optional[ApplicationJson2] = Field(None, alias='application/json')


class Field2001(BaseModel):
    description: Optional[str] = Field(None, examples=['OK'])
    content: Optional[Content2] = None


class Responses1(BaseModel):
    field_200: Optional[Field2001] = Field(None, alias='200')


class Post1(BaseModel):
    operationId: Optional[str] = Field(None, examples=['runs'])
    x_openai_isConsequential: Optional[bool] = Field(
        None, alias='x-openai-isConsequential', examples=[False]
    )
    summary: Optional[str] = Field(
        None,
        examples=[
            'Executes an Actor and returns information about the initiated run in response.'
        ],
    )
    tags: Optional[List[str]] = Field(None, examples=[['Run Actor']])
    requestBody: Optional[RequestBody1] = None
    parameters: Optional[List[Parameter1]] = None
    responses: Optional[Responses1] = None


class FieldActsUsernameActorRuns(BaseModel):
    post: Optional[Post1] = None


class Schema5(BaseModel):
    field_ref: Optional[str] = Field(
        None, alias='$ref', examples=['#/components/schemas/inputSchema']
    )


class ApplicationJson3(BaseModel):
    schema_: Optional[Schema5] = Field(None, alias='schema')


class Content3(BaseModel):
    application_json: Optional[ApplicationJson3] = Field(None, alias='application/json')


class RequestBody2(BaseModel):
    required: Optional[bool] = Field(None, examples=[True])
    content: Optional[Content3] = None


class Schema6(BaseModel):
    type: Optional[str] = None


class Parameter2(BaseModel):
    name: Optional[str] = None
    in_: Optional[str] = Field(None, alias='in', examples=['query'])
    required: Optional[bool] = None
    schema_: Optional[Schema6] = Field(None, alias='schema')
    description: Optional[str] = None


class Field2002(BaseModel):
    description: Optional[str] = Field(None, examples=['OK'])


class Responses2(BaseModel):
    field_200: Optional[Field2002] = Field(None, alias='200')


class Post2(BaseModel):
    operationId: Optional[str] = Field(None, examples=['run-sync'])
    x_openai_isConsequential: Optional[bool] = Field(
        None, alias='x-openai-isConsequential', examples=[False]
    )
    summary: Optional[str] = Field(
        None,
        examples=[
            'Executes an Actor, waits for completion, and returns the OUTPUT from Key-value store in response.'
        ],
    )
    tags: Optional[List[str]] = Field(None, examples=[['Run Actor']])
    requestBody: Optional[RequestBody2] = None
    parameters: Optional[List[Parameter2]] = None
    responses: Optional[Responses2] = None


class FieldActsUsernameActorRunSync(BaseModel):
    post: Optional[Post2] = None


class Paths(BaseModel):
    field_acts__username___actor__run_sync_get_dataset_items: Optional[
        FieldActsUsernameActorRunSyncGetDatasetItems
    ] = Field(None, alias='/acts/<username>~<actor>/run-sync-get-dataset-items')
    field_acts__username___actor__runs: Optional[FieldActsUsernameActorRuns] = Field(
        None, alias='/acts/<username>~<actor>/runs'
    )
    field_acts__username___actor__run_sync: Optional[FieldActsUsernameActorRunSync] = (
        Field(None, alias='/acts/<username>~<actor>/run-sync')
    )


class InputSchema(BaseModel):
    type: Optional[str] = Field(None, examples=['object'])


class Id(BaseModel):
    type: Optional[str] = Field(None, examples=['string'])


class ActId(BaseModel):
    type: Optional[str] = Field(None, examples=['string'])


class UserId(BaseModel):
    type: Optional[str] = Field(None, examples=['string'])


class StartedAt(BaseModel):
    type: Optional[str] = Field(None, examples=['string'])
    format: Optional[str] = Field(None, examples=['date-time'])
    example: Optional[str] = Field(None, examples=['2025-01-08T00:00:00.000Z'])


class FinishedAt(BaseModel):
    type: Optional[str] = Field(None, examples=['string'])
    format: Optional[str] = Field(None, examples=['date-time'])
    example: Optional[str] = Field(None, examples=['2025-01-08T00:00:00.000Z'])


class Status(BaseModel):
    type: Optional[str] = Field(None, examples=['string'])
    example: Optional[str] = Field(None, examples=['READY'])


class Origin(BaseModel):
    type: Optional[str] = Field(None, examples=['string'])
    example: Optional[str] = Field(None, examples=['API'])


class UserAgent(BaseModel):
    type: Optional[str] = Field(None, examples=['string'])


class Properties2(BaseModel):
    origin: Optional[Origin] = None
    userAgent: Optional[UserAgent] = None


class Meta(BaseModel):
    type: Optional[str] = Field(None, examples=['object'])
    properties: Optional[Properties2] = None


class Properties1(BaseModel):
    id: Optional[Id] = None
    actId: Optional[ActId] = None
    userId: Optional[UserId] = None
    startedAt: Optional[StartedAt] = None
    finishedAt: Optional[FinishedAt] = None
    status: Optional[Status] = None
    meta: Optional[Meta] = None


class Data5(BaseModel):
    type: Optional[str] = Field(None, examples=['object'])
    properties: Optional[Properties1] = None


class Properties(BaseModel):
    data: Optional[Data5] = None


class RunsResponseSchema(BaseModel):
    type: Optional[str] = Field(None, examples=['object'])
    properties: Optional[Properties] = None


class Schemas(BaseModel):
    inputSchema: Optional[InputSchema] = None
    runsResponseSchema: Optional[RunsResponseSchema] = None


class Components(BaseModel):
    schemas: Optional[Schemas] = None


class GetOpenApiResponse(BaseModel):
    openapi: Optional[str] = Field(None, examples=['3.0.1'])
    info: Optional[Info] = None
    servers: Optional[List[Server]] = None
    paths: Optional[Paths] = None
    components: Optional[Components] = None


class PostAbortBuildResponse(BaseModel):
    data: Build


class Origin1(Enum):
    DEVELOPMENT = 'DEVELOPMENT'
    WEB = 'WEB'
    API = 'API'
    SCHEDULER = 'SCHEDULER'
    TEST = 'TEST'
    WEBHOOK = 'WEBHOOK'
    ACTOR = 'ACTOR'
    CLI = 'CLI'
    STANDBY = 'STANDBY'


class RunMeta(BaseModel):
    origin: Origin1


class RunShort(BaseModel):
    id: str = Field(..., examples=['HG7ML7M8z78YcAPEB'])
    actId: str = Field(..., examples=['HDSasDasz78YcAPEB'])
    actorTaskId: Optional[str] = Field(None, examples=['KJHSKHausidyaJKHs'])
    status: str = Field(..., examples=['SUCCEEDED'])
    startedAt: str = Field(..., examples=['2019-11-30T07:34:24.202Z'])
    finishedAt: str = Field(..., examples=['2019-12-12T09:30:12.202Z'])
    buildId: str = Field(..., examples=['HG7ML7M8z78YcAPEB'])
    buildNumber: str = Field(..., examples=['0.0.2'])
    meta: RunMeta
    usageTotalUsd: float = Field(..., examples=[0.2])
    defaultKeyValueStoreId: str = Field(..., examples=['sfAjeR4QmeJCQzTfe'])
    defaultDatasetId: str = Field(..., examples=['3ZojQDdFTsyE7Moy4'])
    defaultRequestQueueId: str = Field(..., examples=['so93g2shcDzK3pA85'])


class Data6(PaginationResponse):
    items: List[RunShort]


class GetUserRunsListResponse(BaseModel):
    data: Data6


class RunStats(BaseModel):
    inputBodyLen: Optional[float] = Field(None, examples=[240])
    migrationCount: Optional[float] = Field(None, examples=[0])
    restartCount: float = Field(..., examples=[0])
    resurrectCount: float = Field(..., examples=[2])
    memAvgBytes: Optional[float] = Field(None, examples=[267874071.9])
    memMaxBytes: Optional[float] = Field(None, examples=[404713472])
    memCurrentBytes: Optional[float] = Field(None, examples=[0])
    cpuAvgUsage: Optional[float] = Field(None, examples=[33.7532101107538])
    cpuMaxUsage: Optional[float] = Field(None, examples=[169.650735534941])
    cpuCurrentUsage: Optional[float] = Field(None, examples=[0])
    netRxBytes: Optional[float] = Field(None, examples=[103508042])
    netTxBytes: Optional[float] = Field(None, examples=[4854600])
    durationMillis: Optional[float] = Field(None, examples=[248472])
    runTimeSecs: Optional[float] = Field(None, examples=[248.472])
    metamorph: Optional[float] = Field(None, examples=[0])
    computeUnits: float = Field(..., examples=[0.13804])


class RunOptions(BaseModel):
    build: str = Field(..., examples=['latest'])
    timeoutSecs: float = Field(..., examples=[300])
    memoryMbytes: float = Field(..., examples=[1024])
    diskMbytes: float = Field(..., examples=[2048])


class RunUsage(BaseModel):
    ACTOR_COMPUTE_UNITS: Optional[float] = Field(None, examples=[3])
    DATASET_READS: Optional[float] = Field(None, examples=[4])
    DATASET_WRITES: Optional[float] = Field(None, examples=[4])
    KEY_VALUE_STORE_READS: Optional[float] = Field(None, examples=[5])
    KEY_VALUE_STORE_WRITES: Optional[float] = Field(None, examples=[3])
    KEY_VALUE_STORE_LISTS: Optional[float] = Field(None, examples=[5])
    REQUEST_QUEUE_READS: Optional[float] = Field(None, examples=[2])
    REQUEST_QUEUE_WRITES: Optional[float] = Field(None, examples=[1])
    DATA_TRANSFER_INTERNAL_GBYTES: Optional[float] = Field(None, examples=[1])
    DATA_TRANSFER_EXTERNAL_GBYTES_: Optional[float] = Field(
        None, alias='DATA_TRANSFER_EXTERNAL_GBYTES?', examples=[3]
    )
    PROXY_RESIDENTIAL_TRANSFER_GBYTES: Optional[float] = Field(None, examples=[34])
    PROXY_SERPS: Optional[float] = Field(None, examples=[3])


class Usage31(BaseModel):
    pass


class Usage32(RunUsage, Usage31):
    pass


class Usage3(RootModel[Usage32]):
    root: Usage32


class UsageUsd31(BaseModel):
    pass


class UsageUsd32(RunUsage, UsageUsd31):
    pass


class UsageUsd3(RootModel[UsageUsd32]):
    root: UsageUsd32


class Run(BaseModel):
    id: str = Field(..., examples=['HG7ML7M8z78YcAPEB'])
    actId: str = Field(..., examples=['HDSasDasz78YcAPEB'])
    userId: str = Field(..., examples=['7sT5jcggjjA9fNcxF'])
    actorTaskId: Optional[str] = Field(None, examples=['KJHSKHausidyaJKHs'])
    startedAt: str = Field(..., examples=['2019-11-30T07:34:24.202Z'])
    finishedAt: str = Field(..., examples=['2019-12-12T09:30:12.202Z'])
    status: str = Field(..., examples=['RUNNING'])
    statusMessage: Optional[str] = Field(None, examples=['Actor is running'])
    isStatusMessageTerminal: Optional[bool] = Field(None, examples=[False])
    meta: RunMeta
    pricingInfo: Optional[ActorRunPricingInfo] = None
    stats: RunStats
    chargedEventCounts: Optional[Dict[str, ActorChargeEvent]] = None
    options: RunOptions
    buildId: str = Field(..., examples=['7sT5jcggjjA9fNcxF'])
    exitCode: Optional[float] = Field(None, examples=[0])
    defaultKeyValueStoreId: str = Field(..., examples=['eJNzqsbPiopwJcgGQ'])
    defaultDatasetId: str = Field(..., examples=['wmKPijuyDnPZAPRMk'])
    defaultRequestQueueId: str = Field(..., examples=['FL35cSF7jrxr3BY39'])
    buildNumber: str = Field(..., examples=['0.0.36'])
    containerUrl: str = Field(..., examples=['https://g8kd8kbc5ge8.runs.apify.net'])
    isContainerServerReady: Optional[bool] = Field(None, examples=[True])
    gitBranchName: Optional[str] = Field(None, examples=['master'])
    usage: Optional[Usage3] = None
    usageTotalUsd: Optional[float] = Field(None, examples=[0.2654])
    usageUsd: Optional[UsageUsd3] = None


class RunResponse(BaseModel):
    data: Run


class Error(BaseModel):
    type: str = Field(..., examples=['run-failed'])
    message: str = Field(
        ...,
        examples=[
            'Actor run did not succeed (run ID: 55uatRrZib4xbZs, status: FAILED)'
        ],
    )


class ErrorResponse(BaseModel):
    error: Error


class TaskStats(BaseModel):
    totalRuns: float = Field(..., examples=[15])


class Stats31(BaseModel):
    pass


class Stats32(TaskStats, Stats31):
    pass


class Stats3(RootModel[Stats32]):
    root: Stats32


class TaskShort(BaseModel):
    id: str = Field(..., examples=['zdc3Pyhyz3m8vjDeM'])
    userId: str = Field(..., examples=['wRsJZtadYvn4mBZmm'])
    actId: str = Field(..., examples=['asADASadYvn4mBZmm'])
    actName: str = Field(..., examples=['my-actor'])
    name: str = Field(..., examples=['my-task'])
    username: Optional[str] = Field(None, examples=['janedoe'])
    actUsername: str = Field(..., examples=['janedoe'])
    createdAt: str = Field(..., examples=['2018-10-26T07:23:14.855Z'])
    modifiedAt: str = Field(..., examples=['2018-10-26T13:30:49.578Z'])
    stats: Optional[Stats3] = None


class TaskOptions(BaseModel):
    build: Optional[str] = Field(None, examples=['latest'])
    timeoutSecs: Optional[float] = Field(None, examples=[300])
    memoryMbytes: Optional[float] = Field(None, examples=[128])
    restartOnError: Optional[bool] = Field(None, examples=[False])


class TaskInput(BaseModel):
    hello: Optional[str] = Field(None, examples=['world'])


class Options31(BaseModel):
    pass


class Options32(TaskOptions, Options31):
    pass


class Options3(RootModel[Options32]):
    root: Options32


class Input1(BaseModel):
    pass


class Input2(TaskInput, Input1):
    pass


class Input(RootModel[Input2]):
    root: Input2


class CreateTaskRequest(BaseModel):
    actId: str = Field(..., examples=['asADASadYvn4mBZmm'])
    name: str = Field(..., examples=['my-task'])
    options: Optional[Options3] = None
    input: Optional[Input] = None


class Stats41(BaseModel):
    pass


class Stats42(TaskStats, Stats41):
    pass


class Stats4(RootModel[Stats42]):
    root: Stats42


class Options41(BaseModel):
    pass


class Options42(TaskOptions, Options41):
    pass


class Options4(RootModel[Options42]):
    root: Options42


class Input31(BaseModel):
    pass


class Input32(TaskInput, Input31):
    pass


class Input3(RootModel[Input32]):
    root: Input32


class Task(BaseModel):
    id: str = Field(..., examples=['zdc3Pyhyz3m8vjDeM'])
    userId: str = Field(..., examples=['wRsJZtadYvn4mBZmm'])
    actId: str = Field(..., examples=['asADASadYvn4mBZmm'])
    name: str = Field(..., examples=['my-task'])
    username: Optional[str] = Field(None, examples=['janedoe'])
    createdAt: str = Field(..., examples=['2018-10-26T07:23:14.855Z'])
    modifiedAt: str = Field(..., examples=['2018-10-26T13:30:49.578Z'])
    removedAt: Optional[str] = None
    stats: Optional[Stats4] = None
    options: Optional[Options4] = None
    input: Optional[Input3] = None


class Stats51(BaseModel):
    pass


class Stats52(TaskStats, Stats51):
    pass


class Stats5(RootModel[Stats52]):
    root: Stats52


class Options51(BaseModel):
    pass


class Options52(TaskOptions, Options51):
    pass


class Options5(RootModel[Options52]):
    root: Options52


class Input41(BaseModel):
    pass


class Input42(Task, Input41):
    pass


class Input4(RootModel[Input42]):
    root: Input42


class UpdateTaskRequest(BaseModel):
    id: str = Field(..., examples=['ZxLNxrRaZrSjuhT9y'])
    userId: str = Field(..., examples=['BPWZBd7Z9c746JAnF'])
    actId: str = Field(..., examples=['asADASadYvn4mBZmm'])
    name: str = Field(..., examples=['my-task'])
    username: Optional[str] = Field(None, examples=['janedoe'])
    createdAt: str = Field(..., examples=['2018-10-26T07:23:14.855Z'])
    modifiedAt: str = Field(..., examples=['2018-10-26T13:30:49.578Z'])
    removedAt: Optional[str] = None
    stats: Optional[Stats5] = None
    options: Optional[Options5] = None
    input: Optional[Input4] = None


class Webhook(BaseModel):
    id: str = Field(..., examples=['YiKoxjkaS9gjGTqhF'])
    createdAt: str = Field(..., examples=['2019-12-12T07:34:14.202Z'])
    modifiedAt: str = Field(..., examples=['2019-12-13T08:36:13.202Z'])
    userId: str = Field(..., examples=['wRsJZtadYvn4mBZmm'])
    isAdHoc: Optional[bool] = Field(None, examples=[False])
    shouldInterpolateStrings: Optional[bool] = Field(None, examples=[False])
    eventTypes: List[str] = Field(..., examples=[['ACTOR.RUN.SUCCEEDED']])
    condition: WebhookCondition
    ignoreSslErrors: bool = Field(..., examples=[False])
    doNotRetry: Optional[bool] = Field(None, examples=[False])
    requestUrl: str = Field(..., examples=['http://example.com/'])
    payloadTemplate: Optional[str] = Field(
        None, examples=['{\\n \\"userId\\": {{userId}}...']
    )
    headersTemplate: Optional[str] = Field(
        None, examples=['{\\n \\"Authorization\\": Bearer...']
    )
    description: Optional[str] = Field(None, examples=['this is webhook description'])
    lastDispatch: Optional[ExampleWebhookDispatch] = None
    stats: Optional[WebhookStats] = None


class UpdateRunRequest(BaseModel):
    runId: str = Field(..., examples=['3KH8gEpp4d8uQSe8T'])
    statusMessage: str = Field(..., examples=['Actor has finished'])
    isStatusMessageTerminal: Optional[bool] = Field(None, examples=[True])


class ChargeRunRequest(BaseModel):
    eventName: str = Field(..., examples=['ANALYZE_PAGE'])
    count: float = Field(..., examples=[1])


class KeyValueStoreStats(BaseModel):
    readCount: float = Field(..., examples=[9])
    writeCount: float = Field(..., examples=[3])
    deleteCount: float = Field(..., examples=[6])
    listCount: float = Field(..., examples=[2])
    s3StorageBytes: float = Field(..., examples=[18])


class KeyValueStore(BaseModel):
    id: str = Field(..., examples=['WkzbQMuFYuamGv3YF'])
    name: str = Field(..., examples=['d7b9MDYsbtX5L7XAj'])
    userId: Optional[str] = Field(None, examples=['BPWDBd7Z9c746JAnF'])
    username: Optional[str] = Field(None, examples=['janedoe'])
    createdAt: str = Field(..., examples=['2019-12-12T07:34:14.202Z'])
    modifiedAt: str = Field(..., examples=['2019-12-13T08:36:13.202Z'])
    accessedAt: str = Field(..., examples=['2019-12-14T08:36:13.202Z'])
    actId: Optional[str] = Field(None, examples=[None])
    actRunId: Optional[str] = Field(None, examples=[None])
    consoleUrl: str = Field(
        ...,
        examples=[
            'https://console.apify.com/storage/key-value-stores/27TmTznX9YPeAYhkC'
        ],
    )
    keysPublicUrl: str = Field(
        ...,
        examples=[
            'https://api.apify.com/v2/key-value-stores/WkzbQMuFYuamGv3YF/keys?signature=abc123'
        ],
    )
    """
    A public link to access keys of the key-value store directly.
    """
    urlSigningSecretKey: Optional[str] = None
    """
    A secret key for generating signed public URLs. It is only provided to clients with WRITE permission for the key-value store.
    """
    stats: Optional[KeyValueStoreStats] = None


class Data7(PaginationResponse):
    items: List[KeyValueStore]


class GetListOfKeyValueStoresResponse(BaseModel):
    data: Data7


class CreateKeyValueStoreResponse(BaseModel):
    data: KeyValueStore


class GetStoreResponse(BaseModel):
    data: KeyValueStore


class UpdateStoreRequest(BaseModel):
    name: str


class UpdateStoreResponse(BaseModel):
    data: KeyValueStore


class Item(BaseModel):
    key: str = Field(..., examples=['second-key'])
    size: float = Field(..., examples=[36])
    recordPublicUrl: str = Field(
        ...,
        examples=[
            'https://api.apify.com/v2/key-value-stores/WkzbQMuFYuamGv3YF/records/some-key?signature=abc123'
        ],
    )
    """
    A public link to access this record directly.
    """


class ListOfKeysResponse(BaseModel):
    items: List[Item]
    count: float = Field(..., examples=[2])
    limit: float = Field(..., examples=[2])
    exclusiveStartKey: Optional[str] = Field(None, examples=['some-key'])
    isTruncated: bool = Field(..., examples=[True])
    nextExclusiveStartKey: Optional[str] = Field(None, examples=['third-key'])


class GetListOfKeysResponse(BaseModel):
    data: ListOfKeysResponse


class GetRecordResponse(BaseModel):
    foo: str


class PutRecordRequest(BaseModel):
    foo: Optional[str] = Field(None, examples=['bar'])


class DatasetListItem(BaseModel):
    id: str = Field(..., examples=['WkzbQMuFYuamGv3YF'])
    name: str = Field(..., examples=['d7b9MDYsbtX5L7XAj'])
    userId: str = Field(..., examples=['tbXmWu7GCxnyYtSiL'])
    createdAt: str = Field(..., examples=['2019-12-12T07:34:14.202Z'])
    modifiedAt: str = Field(..., examples=['2019-12-13T08:36:13.202Z'])
    accessedAt: str = Field(..., examples=['2019-12-14T08:36:13.202Z'])
    itemCount: float = Field(..., examples=[7])
    cleanItemCount: float = Field(..., examples=[5])
    actId: Optional[str] = None
    actRunId: Optional[str] = None


class Data8(PaginationResponse):
    items: List[DatasetListItem]


class GetListOfDatasetsResponse(BaseModel):
    data: Data8


class DatasetStats(BaseModel):
    readCount: float = Field(..., examples=[22])
    writeCount: float = Field(..., examples=[3])
    storageBytes: float = Field(..., examples=[783])


class Dataset(BaseModel):
    id: str = Field(..., examples=['WkzbQMuFYuamGv3YF'])
    name: str = Field(..., examples=['d7b9MDYsbtX5L7XAj'])
    userId: str = Field(..., examples=['wRsJZtadYvn4mBZmm'])
    createdAt: str = Field(..., examples=['2019-12-12T07:34:14.202Z'])
    modifiedAt: str = Field(..., examples=['2019-12-13T08:36:13.202Z'])
    accessedAt: str = Field(..., examples=['2019-12-14T08:36:13.202Z'])
    itemCount: float = Field(..., examples=[7])
    cleanItemCount: float = Field(..., examples=[5])
    actId: Optional[str] = None
    actRunId: Optional[str] = None
    fields: Optional[List[str]] = None
    schema_: Optional[Dict[str, Any]] = Field(
        None,
        alias='schema',
        examples=[
            {
                'actorSpecification': 1,
                'title': 'My dataset',
                'views': {
                    'overview': {
                        'title': 'Overview',
                        'transformation': {'fields': ['linkUrl']},
                        'display': {
                            'component': 'table',
                            'properties': {
                                'linkUrl': {'label': 'Link URL', 'format': 'link'}
                            },
                        },
                    }
                },
            }
        ],
    )
    """
    Defines the schema of items in your dataset, the full specification can be found in [Apify docs](/platform/actors/development/actor-definition/dataset-schema)
    """
    consoleUrl: str = Field(
        ..., examples=['https://console.apify.com/storage/datasets/27TmTznX9YPeAYhkC']
    )
    itemsPublicUrl: Optional[str] = Field(
        None,
        examples=[
            'https://api.apify.com/v2/datasets/WkzbQMuFYuamGv3YF/items?signature=abc123'
        ],
    )
    """
    A public link to access the dataset items directly.
    """
    urlSigningSecretKey: Optional[str] = None
    """
    A secret key for generating signed public URLs. It is only provided to clients with WRITE permission for the dataset.
    """
    stats: Optional[DatasetStats] = None


class DatasetResponse(BaseModel):
    data: Dataset


class UpdateDatasetRequest(BaseModel):
    name: str


class PutItemsRequest(BaseModel):
    foo: str


class ValidationError(BaseModel):
    instancePath: Optional[str] = None
    """
    The path to the instance being validated.
    """
    schemaPath: Optional[str] = None
    """
    The path to the schema that failed the validation.
    """
    keyword: Optional[str] = None
    """
    The validation keyword that caused the error.
    """
    message: Optional[str] = None
    """
    A message describing the validation error.
    """
    params: Optional[Dict[str, Any]] = None
    """
    Additional parameters specific to the validation error.
    """


class InvalidItem(BaseModel):
    itemPosition: Optional[float] = Field(None, examples=[2])
    """
    The position of the invalid item in the array.
    """
    validationErrors: Optional[List[ValidationError]] = None
    """
    A complete list of AJV validation error objects for the invalid item.
    """


class Data9(BaseModel):
    invalidItems: List[InvalidItem]
    """
    A list of invalid items in the received array of items.
    """


class Error1(BaseModel):
    type: str = Field(..., examples=['schema-validation-error'])
    """
    The type of the error.
    """
    message: str = Field(..., examples=['Schema validation failed'])
    """
    A human-readable message describing the error.
    """
    data: Data9


class DatasetSchemaValidationError(BaseModel):
    error: Optional[Error1] = None


class PutItemResponseError(BaseModel):
    error: DatasetSchemaValidationError


class DatasetFieldStatistics(BaseModel):
    min: Optional[float] = None
    """
    Minimum value of the field. For numbers, this is calculated directly. For strings, this is the length of the shortest string. For arrays, this is the length of the shortest array. For objects, this is the number of keys in the smallest object.
    """
    max: Optional[float] = None
    """
    Maximum value of the field. For numbers, this is calculated directly. For strings, this is the length of the longest string. For arrays, this is the length of the longest array. For objects, this is the number of keys in the largest object.
    """
    nullCount: Optional[float] = None
    """
    How many items in the dataset have a null value for this field.
    """
    emptyCount: Optional[float] = None
    """
    How many items in the dataset are `undefined`, meaning that for example empty string is not considered empty.
    """


class Data10(BaseModel):
    fieldStatistics: Optional[Dict[str, DatasetFieldStatistics]] = None
    """
    When you configure the dataset [fields schema](https://docs.apify.com/platform/actors/development/actor-definition/dataset-schema/validation), we measure the statistics such as `min`, `max`, `nullCount` and `emptyCount` for each field. This property provides statistics for each field from dataset fields schema. <br/></br>See dataset field statistics [documentation](https://docs.apify.com/platform/actors/development/actor-definition/dataset-schema/validation#dataset-field-statistics) for more information.
    """


class GetDatasetStatisticsResponse(BaseModel):
    data: Data10


class RequestQueueShort(BaseModel):
    id: str = Field(..., examples=['WkzbQMuFYuamGv3YF'])
    name: str = Field(..., examples=['some-name'])
    userId: str = Field(..., examples=['wRsJZtadYvn4mBZmm'])
    username: str = Field(..., examples=['janedoe'])
    createdAt: str = Field(..., examples=['2019-12-12T07:34:14.202Z'])
    modifiedAt: str = Field(..., examples=['2019-12-13T08:36:13.202Z'])
    accessedAt: str = Field(..., examples=['2019-12-14T08:36:13.202Z'])
    expireAt: str = Field(..., examples=['2019-06-02T17:15:06.751Z'])
    totalRequestCount: float = Field(..., examples=[100])
    handledRequestCount: float = Field(..., examples=[50])
    pendingRequestCount: float = Field(..., examples=[50])
    actId: Optional[str] = None
    actRunId: Optional[str] = None
    hadMultipleClients: bool = Field(..., examples=[True])


class Data11(BaseModel):
    total: float = Field(..., examples=[2])
    offset: float = Field(..., examples=[0])
    limit: float = Field(..., examples=[1000])
    desc: bool = Field(..., examples=[False])
    count: float = Field(..., examples=[2])
    items: List[RequestQueueShort]


class GetListOfRequestQueuesResponse(BaseModel):
    data: Data11


class RequestQueue(BaseModel):
    id: str = Field(..., examples=['WkzbQMuFYuamGv3YF'])
    name: Optional[str] = Field(None, examples=['some-name'])
    userId: str = Field(..., examples=['wRsJZtadYvn4mBZmm'])
    createdAt: str = Field(..., examples=['2019-12-12T07:34:14.202Z'])
    modifiedAt: str = Field(..., examples=['2030-12-13T08:36:13.202Z'])
    """
    The modifiedAt is updated whenever the queue is modified. Modifications include adding, updating, or removing requests, as well as locking or unlocking requests in the queue.
    """
    accessedAt: str = Field(..., examples=['2019-12-14T08:36:13.202Z'])
    totalRequestCount: float = Field(..., examples=[870])
    handledRequestCount: float = Field(..., examples=[100])
    pendingRequestCount: float = Field(..., examples=[670])
    hadMultipleClients: bool = Field(..., examples=[True])
    consoleUrl: str = Field(
        ..., examples=['https://api.apify.com/v2/request-queues/27TmTznX9YPeAYhkC']
    )


class CreateRequestQueueResponse(BaseModel):
    data: RequestQueue


class GetRequestQueueResponse(BaseModel):
    data: RequestQueue


class UpdateRequestQueueRequest(BaseModel):
    name: str


class UpdateRequestQueueResponse(BaseModel):
    data: RequestQueue


class RequestWithoutId(BaseModel):
    uniqueKey: str = Field(..., examples=['http://example.com'])
    url: str = Field(..., examples=['http://example.com'])
    method: str = Field(..., examples=['GET'])


class ProcessedRequest(BaseModel):
    requestId: str = Field(..., examples=['sbJ7klsdf7ujN9l'])
    uniqueKey: str = Field(..., examples=['http://example.com'])
    wasAlreadyPresent: bool = Field(..., examples=[False])
    wasAlreadyHandled: bool = Field(..., examples=[False])


class UnprocessedRequest(BaseModel):
    uniqueKey: str = Field(..., examples=['http://example.com'])
    url: str = Field(..., examples=['http://example.com'])
    method: str = Field(..., examples=['GET'])


class Data12(BaseModel):
    processedRequests: List[ProcessedRequest]
    unprocessedRequests: List[UnprocessedRequest]


class BatchOperationResponse(BaseModel):
    data: Data12


class UserData(BaseModel):
    label: Optional[str] = Field(None, examples=['DETAIL'])
    image: Optional[str] = Field(None, examples=['https://picserver1.eu'])


class RequestQueueItems(BaseModel):
    id: str = Field(..., examples=['dnjkDMKLmdlkmlkmld'])
    retryCount: float = Field(..., examples=[0])
    uniqueKey: str = Field(..., examples=['http://example.com'])
    url: str = Field(..., examples=['http://example.com'])
    method: str = Field(..., examples=['GET'])
    loadedUrl: Optional[str] = Field(None, examples=['http://example.com/example-1'])
    payload: Optional[Dict[str, Any]] = None
    noRetry: Optional[bool] = Field(None, examples=[False])
    errorMessages: Optional[List[str]] = None
    headers: Optional[Dict[str, Any]] = None
    userData: Optional[UserData] = None
    handledAt: Optional[str] = Field(None, examples=['2019-06-16T10:23:31.607Z'])


class Data13(BaseModel):
    items: List[RequestQueueItems]
    count: float = Field(..., examples=[2])
    limit: float = Field(..., examples=[2])
    exclusiveStartId: Optional[str] = Field(None, examples=['Ihnsp8YrvJ8102Kj'])


class ListRequestsResponse(BaseModel):
    data: Data13


class RequestOperationInfo(BaseModel):
    requestId: str = Field(..., examples=['YiKoxjkaS9gjGTqhF'])
    wasAlreadyPresent: bool = Field(..., examples=[True])
    wasAlreadyHandled: bool = Field(..., examples=[False])


class AddRequestResponse(BaseModel):
    data: RequestOperationInfo


class GetRequestResponse(BaseModel):
    data: RequestQueueItems


class UpdateRequestResponse(BaseModel):
    data: RequestOperationInfo


class Item1(BaseModel):
    id: str = Field(..., examples=['8OamqXBCpPHxyH9'])
    retryCount: float = Field(..., examples=[0])
    uniqueKey: str = Field(..., examples=['http://example.com'])
    url: str = Field(..., examples=['http://example.com'])
    method: str = Field(..., examples=['GET'])


class Data14(BaseModel):
    limit: float = Field(..., examples=[1000])
    queueModifiedAt: str = Field(..., examples=['2018-03-14T23:00:00.000Z'])
    hadMultipleClients: bool = Field(..., examples=[False])
    items: List[Item1]


class GetHeadResponse(BaseModel):
    data: Data14


class Item2(BaseModel):
    id: str = Field(..., examples=['8OamqXBCpPHxyj9'])
    retryCount: float = Field(..., examples=[0])
    uniqueKey: str = Field(..., examples=['http://example.com'])
    url: str = Field(..., examples=['http://example.com'])
    method: str = Field(..., examples=['GET'])
    lockExpiresAt: str = Field(..., examples=['2022-06-14T23:00:00.000Z'])


class Data15(BaseModel):
    limit: float = Field(..., examples=[1000])
    queueModifiedAt: str = Field(..., examples=['2018-03-14T23:00:00.000Z'])
    """
    The modifiedAt is updated whenever the queue is modified. Modifications include adding, updating, or removing requests, as well as locking or unlocking requests in the queue.
    """
    queueHasLockedRequests: Optional[bool] = Field(None, examples=[True])
    """
    Whether the queue contains requests locked by any client (either the one calling the endpoint or a different one).
    """
    clientKey: Optional[str] = Field(None, examples=['client-one'])
    hadMultipleClients: bool = Field(..., examples=[True])
    lockSecs: float = Field(..., examples=[60])
    items: List[Item2]


class GetHeadAndLockResponse(BaseModel):
    data: Data15


class Data16(BaseModel):
    lockExpiresAt: str = Field(..., examples=['2022-01-01T00:00:00.000Z'])
    """
    Date when lock expires.
    """


class ProlongRequestLockResponse(BaseModel):
    data: Optional[Data16] = None


class WebhookCreate(BaseModel):
    isAdHoc: Optional[bool] = Field(None, examples=[False])
    eventTypes: List[str] = Field(..., examples=[['ACTOR.RUN.SUCCEEDED']])
    condition: WebhookCondition
    idempotencyKey: Optional[str] = Field(None, examples=['fdSJmdP3nfs7sfk3y'])
    ignoreSslErrors: Optional[bool] = Field(None, examples=[False])
    doNotRetry: Optional[bool] = Field(None, examples=[False])
    requestUrl: str = Field(..., examples=['http://example.com/'])
    payloadTemplate: Optional[str] = Field(
        None, examples=['{\\n \\"userId\\": {{userId}}...']
    )
    headersTemplate: Optional[str] = Field(
        None, examples=['{\\n \\"Authorization\\": Bearer...']
    )
    description: Optional[str] = Field(None, examples=['this is webhook description'])
    shouldInterpolateStrings: Optional[bool] = Field(None, examples=[False])


class CreateWebhookResponse(BaseModel):
    data: Webhook


class GetWebhookResponse(BaseModel):
    data: Webhook


class WebhookUpdate(BaseModel):
    isAdHoc: Optional[bool] = Field(None, examples=[False])
    eventTypes: Optional[List[str]] = Field(None, examples=[['ACTOR.RUN.SUCCEEDED']])
    condition: Optional[WebhookCondition] = None
    ignoreSslErrors: Optional[bool] = Field(None, examples=[False])
    doNotRetry: Optional[bool] = Field(None, examples=[False])
    requestUrl: Optional[str] = Field(None, examples=['http://example.com/'])
    payloadTemplate: Optional[str] = Field(
        None, examples=['{\\n \\"userId\\": {{userId}}...']
    )
    headersTemplate: Optional[str] = Field(
        None, examples=['{\\n \\"Authorization\\": Bearer...']
    )
    description: Optional[str] = Field(None, examples=['this is webhook description'])
    shouldInterpolateStrings: Optional[bool] = Field(None, examples=[False])


class UpdateWebhookResponse(BaseModel):
    data: Webhook


class EventData(BaseModel):
    actorId: str = Field(..., examples=['vvE7iMKuMc5qTHHsR'])
    actorRunId: str = Field(..., examples=['JgwXN9BdwxGcu9MMF'])


class Calls(BaseModel):
    startedAt: Optional[str] = Field(None, examples=['2019-12-12T07:34:14.202Z'])
    finishedAt: Optional[str] = Field(None, examples=['2019-12-12T07:34:14.202Z'])
    errorMessage: Optional[str] = Field(None, examples=['Cannot send request'])
    responseStatus: Optional[float] = Field(None, examples=[200])
    responseBody: Optional[str] = Field(None, examples=[{'foo': 'bar'}])


class WebhookDispatch(BaseModel):
    id: str = Field(..., examples=['asdLZtadYvn4mBZmm'])
    userId: str = Field(..., examples=['wRsJZtadYvn4mBZmm'])
    webhookId: str = Field(..., examples=['asdLZtadYvn4mBZmm'])
    createdAt: str = Field(..., examples=['2019-12-12T07:34:14.202Z'])
    status: str = Field(..., examples=['SUCCEEDED'])
    eventType: str = Field(..., examples=['ACTOR.RUN.SUCCEEDED'])
    eventData: EventData = Field(..., title='eventData')
    calls: Optional[Calls] = Field(None, title='calls')


class TestWebhookResponse(BaseModel):
    data: WebhookDispatch


class Data17(PaginationResponse):
    items: List[WebhookDispatch]


class WebhookDispatchList(BaseModel):
    data: Optional[Data17] = None


class GetWebhookDispatchResponse(BaseModel):
    data: WebhookDispatch


class GetListOfSchedulesResponseDataItemsActions(BaseModel):
    id: str = Field(..., examples=['ZReCs7hkdieq8ZUki'])
    type: str = Field(..., examples=['RUN_ACTOR'])
    actorId: str = Field(..., examples=['HKhKmiCMrDgu9eXeE'])


class GetListOfSchedulesResponseDataItems(BaseModel):
    id: str = Field(..., examples=['asdLZtadYvn4mBZmm'])
    userId: str = Field(..., examples=['wRsJZtadYvn4mBZmm'])
    name: str = Field(..., examples=['my-schedule'])
    createdAt: str = Field(..., examples=['2019-12-12T07:34:14.202Z'])
    modifiedAt: str = Field(..., examples=['2019-12-20T06:33:11.202Z'])
    lastRunAt: str = Field(..., examples=['2019-04-12T07:33:10.202Z'])
    nextRunAt: str = Field(..., examples=['2019-04-12T07:34:10.202Z'])
    isEnabled: bool = Field(..., examples=[True])
    isExclusive: bool = Field(..., examples=[True])
    cronExpression: str = Field(..., examples=['* * * * *'])
    timezone: str = Field(..., examples=['UTC'])
    actions: List[GetListOfSchedulesResponseDataItemsActions]


class GetListOfSchedulesResponseData(BaseModel):
    total: float = Field(..., examples=[2])
    offset: float = Field(..., examples=[0])
    limit: float = Field(..., examples=[1000])
    desc: bool = Field(..., examples=[False])
    count: float = Field(..., examples=[2])
    items: List[GetListOfSchedulesResponseDataItems]


class GetListOfSchedulesResponse(BaseModel):
    data: GetListOfSchedulesResponseData


class ScheduleActionsRunInput(BaseModel):
    body: Optional[str] = Field(None, examples=['{\\n   \\"foo\\": \\"actor\\"\\n}'])
    contentType: Optional[str] = Field(
        None, examples=['application/json; charset=utf-8']
    )


class ScheduleActionsRunOptions(BaseModel):
    build: Optional[str] = Field(None, examples=['latest'])
    timeoutSecs: Optional[float] = Field(None, examples=[60])
    memoryMbytes: Optional[float] = Field(None, examples=[1024])
    restartOnError: Optional[bool] = Field(None, examples=[False])


class ScheduleCreateActions(BaseModel):
    type: str = Field(..., examples=['RUN_ACTOR'])
    actorId: str = Field(..., examples=['jF8GGEvbEg4Au3NLA'])
    runInput: Optional[ScheduleActionsRunInput] = None
    runOptions: Optional[ScheduleActionsRunOptions] = None


class ScheduleCreate(BaseModel):
    name: Optional[str] = Field(None, examples=['my-schedule'])
    isEnabled: Optional[bool] = Field(None, examples=[True])
    isExclusive: Optional[bool] = Field(None, examples=[True])
    cronExpression: Optional[str] = Field(None, examples=['* * * * *'])
    timezone: Optional[str] = Field(None, examples=['UTC'])
    description: Optional[str] = Field(None, examples=['Schedule of actor ...'])
    actions: Optional[List[ScheduleCreateActions]] = None


class ScheduleResponseDataActions(BaseModel):
    id: str = Field(..., examples=['c6KfSgoQzFhMk3etc'])
    type: str = Field(..., examples=['RUN_ACTOR'])
    actorId: str = Field(..., examples=['jF8GGEvbEg4Au3NLA'])
    runInput: Optional[ScheduleActionsRunInput] = None
    runOptions: Optional[ScheduleActionsRunOptions] = None


class ScheduleResponseData(BaseModel):
    id: str = Field(..., examples=['asdLZtadYvn4mBZmm'])
    userId: str = Field(..., examples=['wRsJZtadYvn4mBZmm'])
    name: str = Field(..., examples=['my-schedule'])
    cronExpression: str = Field(..., examples=['* * * * *'])
    timezone: str = Field(..., examples=['UTC'])
    isEnabled: bool = Field(..., examples=[True])
    isExclusive: bool = Field(..., examples=[True])
    description: Optional[str] = Field(None, examples=['Schedule of actor ...'])
    createdAt: str = Field(..., examples=['2019-12-12T07:34:14.202Z'])
    modifiedAt: str = Field(..., examples=['2019-12-20T06:33:11.202Z'])
    nextRunAt: Optional[str] = Field(None, examples=['2019-04-12T07:34:10.202Z'])
    lastRunAt: Optional[str] = Field(None, examples=['2019-04-12T07:33:10.202Z'])
    actions: List[ScheduleResponseDataActions]


class ScheduleResponse(BaseModel):
    data: ScheduleResponseData


class ScheduleInvoked(BaseModel):
    message: str = Field(..., examples=['Schedule invoked'])
    level: str = Field(..., examples=['INFO'])
    createdAt: str = Field(..., examples=['2019-03-26T12:28:00.370Z'])


class GetScheduleLogResponse(BaseModel):
    data: List[ScheduleInvoked]


class CurrentPricingInfo(BaseModel):
    pricingModel: str = Field(..., examples=['FREE'])


class StoreListActor(BaseModel):
    id: str = Field(..., examples=['zdc3Pyhyz3m8vjDeM'])
    title: str = Field(..., examples=['My Public Actor'])
    name: str = Field(..., examples=['my-public-actor'])
    username: str = Field(..., examples=['jane35'])
    userFullName: str = Field(..., examples=['Jane H. Doe'])
    description: str = Field(..., examples=['My public actor!'])
    categories: Optional[List[str]] = Field(
        None, examples=[['MARKETING', 'LEAD_GENERATION']]
    )
    notice: Optional[str] = None
    pictureUrl: Optional[str] = Field(None, examples=['https://...'])
    userPictureUrl: Optional[str] = Field(None, examples=['https://...'])
    url: Optional[str] = Field(None, examples=['https://...'])
    stats: ActorStats
    currentPricingInfo: CurrentPricingInfo


class StoreData(BaseModel):
    total: float = Field(..., examples=[100])
    offset: float = Field(..., examples=[0])
    limit: float = Field(..., examples=[1000])
    desc: bool = Field(..., examples=[False])
    count: float = Field(..., examples=[1])
    items: List[StoreListActor]


class GetListOfActorsInStoreResponse(BaseModel):
    data: StoreData


class Profile(BaseModel):
    bio: Optional[str] = Field(
        None, examples=['I started web scraping in 1985 using Altair BASIC.']
    )
    name: Optional[str] = Field(None, examples=['Jane Doe'])
    pictureUrl: Optional[str] = Field(
        None, examples=['/img/anonymous_user_picture.png']
    )
    githubUsername: Optional[str] = Field(None, examples=['torvalds.'])
    websiteUrl: Optional[str] = Field(None, examples=['http://www.example.com'])
    twitterUsername: Optional[str] = Field(None, examples=['@BillGates'])


class UserPublicInfo(BaseModel):
    username: str = Field(..., examples=['d7b9MDYsbtX5L7XAj'])
    profile: Profile


class GetPublicUserDataResponse(BaseModel):
    data: UserPublicInfo


class ProxyGroup(BaseModel):
    name: str = Field(..., examples=['Group1'])
    description: str = Field(..., examples=['Group1 description'])
    availableCount: float = Field(..., examples=[10])


class Proxy(BaseModel):
    password: str = Field(..., examples=['ad78knd9Jkjd86'])
    groups: List[ProxyGroup]


class AvailableProxyGroups(BaseModel):
    SOMEGROUP: float = Field(..., examples=[20])
    ANOTHERGROUP: float = Field(..., examples=[200])


class Plan(BaseModel):
    id: str = Field(..., examples=['Personal'])
    description: str = Field(
        ..., examples=['Cost-effective plan for freelancers, developers and students.']
    )
    isEnabled: bool = Field(..., examples=[True])
    monthlyBasePriceUsd: float = Field(..., examples=[49])
    monthlyUsageCreditsUsd: float = Field(..., examples=[49])
    usageDiscountPercent: float = Field(..., examples=[0])
    enabledPlatformFeatures: List[List] = Field(
        ...,
        examples=[
            [['ACTORS'], ['STORAGE'], ['PROXY_SERPS'], ['SCHEDULER'], ['WEBHOOKS']]
        ],
    )
    maxMonthlyUsageUsd: float = Field(..., examples=[9999])
    maxActorMemoryGbytes: float = Field(..., examples=[32])
    maxMonthlyActorComputeUnits: float = Field(..., examples=[1000])
    maxMonthlyResidentialProxyGbytes: float = Field(..., examples=[10])
    maxMonthlyProxySerps: float = Field(..., examples=[30000])
    maxMonthlyExternalDataTransferGbytes: float = Field(..., examples=[1000])
    maxActorCount: float = Field(..., examples=[100])
    maxActorTaskCount: float = Field(..., examples=[1000])
    dataRetentionDays: float = Field(..., examples=[14])
    availableProxyGroups: AvailableProxyGroups
    teamAccountSeatCount: float = Field(..., examples=[1])
    supportLevel: str = Field(..., examples=['COMMUNITY'])
    availableAddOns: List[str] = Field(..., examples=[[]])


class EffectivePlatformFeature(BaseModel):
    isEnabled: bool = Field(..., examples=[True])
    disabledReason: str = Field(
        ...,
        examples=[
            'The "Selected public Actors for developers" feature is not enabled for your account. Please upgrade your plan or contact support@apify.com'
        ],
    )
    disabledReasonType: str = Field(..., examples=['DISABLED'])
    isTrial: bool = Field(..., examples=[False])
    trialExpirationAt: str = Field(..., examples=['2025-01-01T14:00:00.000Z'])


class EffectivePlatformFeatures(BaseModel):
    ACTORS: EffectivePlatformFeature
    STORAGE: EffectivePlatformFeature
    SCHEDULER: EffectivePlatformFeature
    PROXY: EffectivePlatformFeature
    PROXY_EXTERNAL_ACCESS: EffectivePlatformFeature
    PROXY_RESIDENTIAL: EffectivePlatformFeature
    PROXY_SERPS: EffectivePlatformFeature
    WEBHOOKS: EffectivePlatformFeature
    ACTORS_PUBLIC_ALL: EffectivePlatformFeature
    ACTORS_PUBLIC_DEVELOPER: EffectivePlatformFeature


class UserPrivateInfo(BaseModel):
    id: str = Field(..., examples=['YiKoxjkaS9gjGTqhF'])
    username: str = Field(..., examples=['myusername'])
    profile: Profile
    email: str = Field(..., examples=['bob@example.com'])
    proxy: Proxy
    plan: Plan
    effectivePlatformFeatures: EffectivePlatformFeatures
    createdAt: str = Field(..., examples=['2022-11-29T14:48:29.381Z'])
    isPaying: bool = Field(..., examples=[True])


class GetPrivateUserDataResponse(BaseModel):
    data: UserPrivateInfo


class UsageCycle(BaseModel):
    startAt: str = Field(..., examples=['2022-10-02T00:00:00.000Z'])
    endAt: str = Field(..., examples=['2022-11-01T23:59:59.999Z'])


class PriceTiers(BaseModel):
    quantityAbove: float = Field(..., examples=[0])
    discountPercent: float = Field(..., examples=[100])
    tierQuantity: float = Field(..., examples=[0.39])
    unitPriceUsd: float = Field(..., examples=[0])
    priceUsd: float = Field(..., examples=[0])


class UsageItem(BaseModel):
    quantity: float = Field(..., examples=[2.784475])
    baseAmountUsd: float = Field(..., examples=[0.69611875])
    baseUnitPriceUsd: float = Field(..., examples=[0.25])
    amountAfterVolumeDiscountUsd: float = Field(..., examples=[0.69611875])
    priceTiers: List[PriceTiers]


class MonthlyServiceUsage(BaseModel):
    USAGE_ITEM: UsageItem


class ServiceUsage(BaseModel):
    SERVICE_USAGE_ITEM: UsageItem


class DailyServiceUsages(BaseModel):
    date: str = Field(..., examples=['2022-10-02T00:00:00.000Z'])
    serviceUsage: ServiceUsage
    totalUsageCreditsUsd: float = Field(..., examples=[0.0474385791970591])


class MonthlyUsage(BaseModel):
    usageCycle: UsageCycle
    monthlyServiceUsage: MonthlyServiceUsage
    dailyServiceUsages: List[DailyServiceUsages]
    totalUsageCreditsUsdBeforeVolumeDiscount: float = Field(
        ..., examples=[0.786143673840067]
    )
    totalUsageCreditsUsdAfterVolumeDiscount: float = Field(
        ..., examples=[0.786143673840067]
    )


class GetMonthlyUsageResponse(BaseModel):
    data: MonthlyUsage


class MonthlyUsageCycle(BaseModel):
    startAt: str = Field(..., examples=['2022-10-02T00:00:00.000Z'])
    endAt: str = Field(..., examples=['2022-11-01T23:59:59.999Z'])


class Limits(BaseModel):
    maxMonthlyUsageUsd: float = Field(..., examples=[300])
    maxMonthlyActorComputeUnits: float = Field(..., examples=[1000])
    maxMonthlyExternalDataTransferGbytes: float = Field(..., examples=[7])
    maxMonthlyProxySerps: float = Field(..., examples=[50])
    maxMonthlyResidentialProxyGbytes: float = Field(..., examples=[0.5])
    maxActorMemoryGbytes: float = Field(..., examples=[16])
    maxActorCount: float = Field(..., examples=[100])
    maxActorTaskCount: float = Field(..., examples=[1000])
    maxConcurrentActorJobs: float = Field(..., examples=[256])
    maxTeamAccountSeatCount: float = Field(..., examples=[9])
    dataRetentionDays: float = Field(..., examples=[90])


class Current(BaseModel):
    monthlyUsageUsd: float = Field(..., examples=[43])
    monthlyActorComputeUnits: float = Field(..., examples=[500.784475])
    monthlyExternalDataTransferGbytes: float = Field(..., examples=[3.00861903931946])
    monthlyProxySerps: float = Field(..., examples=[34])
    monthlyResidentialProxyGbytes: float = Field(..., examples=[0.4])
    actorMemoryGbytes: float = Field(..., examples=[8])
    actorCount: float = Field(..., examples=[31])
    actorTaskCount: float = Field(..., examples=[130])
    activeActorJobCount: float = Field(..., examples=[0])
    teamAccountSeatCount: float = Field(..., examples=[5])


class AccountLimits(BaseModel):
    monthlyUsageCycle: MonthlyUsageCycle
    limits: Limits
    current: Current


class GetLimitsResponse(BaseModel):
    data: AccountLimits


class UpdateLimitsRequest(BaseModel):
    maxMonthlyUsageUsd: Optional[float] = Field(None, examples=[300])
    """
    If your platform usage in the billing period exceeds the prepaid usage, you will be charged extra.
    Setting this property you can update your hard limit on monthly platform usage to prevent accidental overage or to limit the extra charges

    """
    dataRetentionDays: Optional[float] = Field(None, examples=[90])
    """
    Apify securely stores your ten most recent Actor runs indefinitely, ensuring they are always accessible.
    Unnamed storages and other Actor runs are automatically deleted after the retention period.
    If you're subscribed, you can change it to keep data for longer or to limit your usage. [Lear more](https://docs.apify.com/platform/storage/usage#data-retention)

    """
