name: Check async docstrings

on:
  workflow_call:

jobs:
  check_async_docstrings:
    name: Check whether doctrings for async methods are up-to-date
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pipx install --python ${{ env.PYTHON_VERSION }} poetry
          make install-dev

      - name: Check async docstrings
        run: make check-async-docstrings
